/* Auto-generated by tools/build-guide-handles.js — DO NOT EDIT.
   Source: every component manifest's `handles` block (lib/components/).
   Rebuild: node tools/build-guide-handles.js */

/** One rendered part a narrated sentence can name, and the token that names it. */
export type GuideHandle = {
	/** The component that declared it — attribution for the sweep, not used for matching. */
	component: string;
	/** The repeated part, already scoped to its own section. */
	part: string;
	/** The naming token, scoped within `part`. */
	names: string;
};

export const GUIDE_HANDLES: readonly GuideHandle[] = [
	{
		"component": "glossary",
		"part": "section.glossary tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "journey",
		"part": "section.journey .journey-actor",
		"names": ".journey-actor-name"
	},
	{
		"component": "journey",
		"part": "section.journey .journey-lane",
		"names": ".journey-lane-label"
	},
	{
		"component": "journey",
		"part": "section.journey .journey-task",
		"names": ".journey-task-label"
	},
	{
		"component": "journey",
		"part": "section.journey .journey-vstage",
		"names": ".journey-vstage-name"
	},
	{
		"component": "matrix-grid",
		"part": "section.matrix-grid tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "obligation-matrix",
		"part": "section.obligation-matrix tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "roadmap",
		"part": "section.roadmap tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "state-chart",
		"part": "section.state-chart .state-node",
		"names": ".state-label"
	},
	{
		"component": "state-chart",
		"part": "section.state-chart .state-node-row",
		"names": ".state-label"
	},
	{
		"component": "statute-stack",
		"part": "section.statute-stack tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "table",
		"part": "section.table tbody > tr",
		"names": ":scope > td:first-child, :scope > th:first-child"
	},
	{
		"component": "team-profile",
		"part": "section.team-profile .person",
		"names": ".person-name"
	}
];
