/**
 * Unit: Export to Marp (tools/export-marp.js).
 *
 * Covers the pure helpers (front-matter theme read, asset localization) and an
 * end-to-end bundle: the exporter produces the expected layout, and the baked
 * deck.md divides into the same slides as the source — the portability contract.
 */

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync, spawnSync } = require('node:child_process');

const REPO = path.join(__dirname, '..', '..', '..');
const TOOL = path.join(REPO, 'tools', 'export-marp.js');
const { localizeAssets, readTheme } = require(TOOL);
const latticeEngine = require('../../../lib/engine');
const { JSDOM } = require('jsdom');
const { readExportSettings } = require('../../../lib/core/export-settings');

describe('export-marp helpers', () => {
  test('readTheme reads the front-matter palette, or null', () => {
    assert.equal(readTheme('---\nmarp: true\ntheme: cuoio\n---\n\n# A'), 'cuoio');
    assert.equal(readTheme('# A\n\nno front matter'), null);
  });

  test('localizeAssets copies local images + rewrites paths; leaves remote alone', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-loc-'));
    const deckDir = path.join(tmp, 'src');
    fs.mkdirSync(deckDir);
    fs.writeFileSync(path.join(deckDir, 'logo.png'), 'PNGDATA');
    const dest = path.join(tmp, 'out');
    fs.mkdirSync(dest);
    const body = '![logo](logo.png)\n\n![remote](https://x/y.png)\n\n![missing](nope.png)';
    const { body: out, count } = localizeAssets(body, deckDir, dest);
    assert.match(out, /!\[logo\]\(assets\/logo\.png\)/, 'local image rewritten to assets/');
    assert.match(out, /!\[remote\]\(https:\/\/x\/y\.png\)/, 'remote URL untouched');
    assert.match(out, /!\[missing\]\(nope\.png\)/, 'dangling ref left as-is');
    assert.equal(count, 1);
    assert.ok(fs.existsSync(path.join(dest, 'assets', 'logo.png')), 'image copied into assets/');
    fs.rmSync(tmp, { recursive: true, force: true });
  });
});

describe('export-marp bundle (end-to-end)', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-e2e-'));
  let dest;
  before(() => {
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), tmp], { stdio: 'pipe' });
    dest = path.join(tmp, 'split-headings');
  });
  after(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test('produces the expected Marp-native bundle layout', () => {
    for (const f of [
      'split-headings.md', 'README.md', 'marp.config.cjs', 'package.json',
      '.vscode/settings.json',
      'lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css',
      'mermaid-v11.min.js', 'lattice-runtime.min.js',
    ]) {
      assert.ok(fs.existsSync(path.join(dest, f)), `bundle is missing ${f}`);
    }
    // No emulator / dist/ folder — the bundle is rendered with Marp.
    assert.ok(!fs.existsSync(path.join(dest, 'dist')), 'bundle must not ship a dist/ folder');
    assert.ok(!fs.existsSync(path.join(dest, 'dist', 'lattice-emulator.js')), 'no bundled emulator');
  });

  test('bundled themes are the minified build; .vscode registers them', () => {
    const carta = fs.readFileSync(path.join(dest, 'themes', 'indaco.css'), 'utf8');
    assert.match(carta, /GENERATED by tools\/build-css\.js \(minified\)/, 'theme is the minified dist build');
    assert.match(carta, /@theme indaco/, 'minified theme keeps its @theme name');
    const settings = JSON.parse(fs.readFileSync(path.join(dest, '.vscode', 'settings.json'), 'utf8'));
    assert.deepEqual(settings['markdown.marp.themes'],
      ['lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css']);
  });

  test('deck ends with the runtime scripts (browser render) under a lint-ignore', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /<!-- markdownlint-disable MD033 -->\n<script src="mermaid-v11\.min\.js"><\/script>\n<script src="lattice-runtime\.min\.js"><\/script>\n/,
      'markdown carries the lint-ignore + mermaid + runtime script tags');
  });

  // Marp strips front matter, and the runtime's old recovery path — fetching the
  // source `.md` beside the document — cannot work over `file://`, which is how
  // both a double-clicked export and marp-cli itself load the deck. So the deck
  // carries its own front matter as an inert data block.
  // The imagery bucket's `![bg]` is a SOURCE transform on the engine path too, so
  // the export bakes it like the splits and the glossary. Left unbaked, Marp's own
  // advanced-background machinery took the `![bg]` instead — photo full-bleed, prose
  // unscrimmed on top. The URL must be the LOCALIZED `assets/…` path: the bake runs
  // after localization, and a bundle that embeds the author's original path ships a
  // panel pointing at a file it doesn't carry.
  test('an `image` slide\'s ![bg] is baked into the .lattice-bg panel, localized', () => {
    const deck = ['---', 'marp: true', 'theme: indaco', '---', '',
      '<!-- _class: image -->', '', '`Eyebrow`', '', '## A lake view.', '',
      'Body prose.', '', '![bg](photo.jpg)', ''].join('\n');
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'export-img-'));
    fs.writeFileSync(path.join(dir, 'photo.jpg'), 'not-really-a-jpeg');
    fs.writeFileSync(path.join(dir, 'img.md'), deck);
    execFileSync('node', [TOOL, path.join(dir, 'img.md'), path.join(dir, 'out')], { stdio: 'pipe' });
    const baked = fs.readFileSync(path.join(dir, 'out', 'img', 'img.md'), 'utf8');
    assert.match(baked, /<div class="lattice-bg lattice-bg-full" style="background-image:url\('assets\/photo\.jpg'\)"><\/div>/);
    assert.doesNotMatch(baked, /!\[bg\]/, 'the markdown image form is gone');
    assert.ok(fs.existsSync(path.join(dir, 'out', 'img', 'assets', 'photo.jpg')), 'and the file came along');
  });

  // The lift needs the `_class: …image…` comment and the `![bg]` in the SAME slide
  // part, so it has to run BEFORE the split bake materializes heading boundaries as
  // literal `---`. Run after, an image slide with TWO top-level headings had its
  // `_class` in one part and its `![bg]` in the next — the lift skipped it silently and
  // Marp's advanced-background machinery took the image, which is the exact defect the
  // bake exists to prevent.
  test('a `split: headings` image slide with two headings still gets its panel', () => {
    const deck = ['---', 'marp: true', 'theme: indaco', 'split: headings', '---', '',
      '<!-- _class: image -->', '', '## First heading', '', 'Prose.', '',
      '## Second heading', '', 'More prose.', '', '![bg](p.jpg)', ''].join('\n');
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'export-split-img-'));
    fs.writeFileSync(path.join(dir, 'p.jpg'), 'x');
    fs.writeFileSync(path.join(dir, 'd.md'), deck);
    execFileSync('node', [TOOL, path.join(dir, 'd.md'), path.join(dir, 'out')], { stdio: 'pipe' });
    const baked = fs.readFileSync(path.join(dir, 'out', 'd', 'd.md'), 'utf8');
    assert.match(baked, /<div class="lattice-bg/, 'the panel was baked');
    assert.doesNotMatch(baked, /!\[bg\]/);
    assert.match(baked, /split: rule/, 'and the splits are still baked');
    // The engine lifts this deck too — that is the parity being kept.
    assert.match(latticeEngine.createEngine().render(deck).html, /lattice-bg/);
  });

  test('deck carries the BAKED front matter, with the deck-wide registers', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    // Parsed through a real HTML parser rather than a tag-shaped regex: the trailer
    // now holds TWO data blocks (the front-matter snapshot and this export's own
    // settings), and an end-anchored regex silently spanned both.
    const doc = new JSDOM(`<body>${baked}</body>`).window.document;
    const el = doc.querySelector('script[type="application/lattice-front-matter"]');
    assert.ok(el, 'the deck carries a baked front-matter block');
    const fm = JSON.parse(el.textContent);
    assert.match(fm, /^marp: true$/m);
    assert.match(fm, /^theme: indaco$/m);
    // It is the EXPORTED front matter, so it states the baked split mode.
    assert.match(fm, /^split: rule$/m);
    // …and it does NOT carry the export's own settings. They are a different kind
    // of thing — the producer's choices, not the author's deck — so they ride in
    // their own block (lib/core/export-settings.js).
    assert.doesNotMatch(fm, /overflow-marker/);
    assert.ok(doc.querySelector('script[type="application/lattice-export-settings"]'),
      'the export-settings block is there too, separately');
  });

  test('baked deck.md states split: rule and divides into the same slides', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /split: rule/, 'splits are baked → split: rule');
    const original = fs.readFileSync(path.join(REPO, 'examples', 'split-headings.md'), 'utf8');
    const engine = latticeEngine.createEngine();
    const count = (src) => (engine.render(src).html.match(/<section[\s>]/g) || []).length;
    assert.equal(count(baked), count(original), 'baked deck divides identically to the source');
  });

  // #1256 — the two defects that made a real exported deck come out wrong.
  test('ships every font lattice.css references, beside the stylesheet', () => {
    const css = fs.readFileSync(path.join(dest, 'lattice.css'), 'utf8');
    const refs = [...css.matchAll(/url\(\s*['"]?fonts\/([^)'"\s]+)['"]?\s*\)/g)].map((m) => m[1]);
    assert.ok(refs.length > 0, 'the bundled stylesheet references fonts at all');
    for (const f of new Set(refs)) {
      assert.ok(fs.existsSync(path.join(dest, 'fonts', f)), `bundle is missing fonts/${f}`);
    }
  });

  test('bundled CSS is marp-scopable: no rule LEADS with :is(section…)', () => {
    // marp-core scopes off the leftmost compound, so a leading
    // `:is(section.x, figure.x)` head becomes a slide-inside-a-slide and matches
    // nothing. Every stylesheet in the bundle goes through the distribution.
    for (const f of ['lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css']) {
      const css = fs.readFileSync(path.join(dest, f), 'utf8');
      const bad = css.match(/(^|[{};])\s*:is\([^)]*section[^)]*\)/g) || [];
      assert.deepEqual(bad, [], `${f} still leads ${bad.length} rule(s) with :is(section…)`);
    }
  });

  // The auto-glossary APPENDS a whole slide from front-matter `acronyms:`. It is a
  // source transform the recipient's Marp will never run, so the export must bake
  // it exactly like splits — before #1256 the exported deck was one slide short,
  // and the slide before it still announced "the next slide is generated".
  test('bakes the auto-glossary slide into the exported deck (no slide is lost)', () => {
    const tmpG = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-gloss-'));
    try {
      const source = path.join(REPO, 'examples', 'auto-glossary.md');
      execFileSync('node', [TOOL, source, tmpG], { stdio: 'pipe' });
      const baked = fs.readFileSync(path.join(tmpG, 'auto-glossary', 'auto-glossary.md'), 'utf8');
      // The generated slide is present, and its own trigger is consumed so a
      // re-render can't append it twice.
      assert.match(baked, /^<!-- _class: glossary/m, 'the generated glossary slide is baked in');
      assert.doesNotMatch(baked, /^\s*glossary:\s*auto\s*$/m, 'the trigger is stripped');
      // Slide-count parity with what the CLI actually renders. `render()` is the
      // raw engine — the emulator runs appendAutoGlossary BEFORE it (the step the
      // export was missing), so that is the baseline the export must match.
      const { appendAutoGlossary } = require('../../../lib/core/glossary-auto.mjs');
      const engine = latticeEngine.createEngine();
      const count = (src) => (engine.render(src).html.match(/<section[\s>]/g) || []).length;
      const original = fs.readFileSync(source, 'utf8');
      assert.equal(count(baked), count(appendAutoGlossary(original)),
        'the exported deck has the same slide count as the CLI renders');
      assert.equal(count(baked), count(original) + 1, 'and it is exactly one MORE than the raw source');
    } finally {
      fs.rmSync(tmpG, { recursive: true, force: true });
    }
  });

  test('marp.config.cjs + .vscode enable HTML so the runtime tags survive', () => {
    assert.match(fs.readFileSync(path.join(dest, 'marp.config.cjs'), 'utf8'), /html:\s*true/);
    const settings = JSON.parse(fs.readFileSync(path.join(dest, '.vscode', 'settings.json'), 'utf8'));
    assert.equal(settings['markdown.marp.enableHtml'], true);
  });

  test('package.json pins marp-cli only', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(dest, 'package.json'), 'utf8'));
    assert.ok(pkg.dependencies['@marp-team/marp-cli']);
    // No @slidewright/lattice dep — it is unpublished, so it would 404 `npm
    // install`; the bundle is rendered with Marp, not a bundled engine.
    assert.strictEqual(pkg.dependencies['@slidewright/lattice'], undefined);
  });

  test('ships the agent kit by default (AGENTS.md + the catalog under agent/)', () => {
    assert.ok(fs.existsSync(path.join(dest, 'AGENTS.md')), 'AGENTS.md present');
    const cat = path.join(dest, 'agent', 'components.json');
    assert.ok(fs.existsSync(cat), 'agent/components.json present');
    const agents = fs.readFileSync(path.join(dest, 'AGENTS.md'), 'utf8');
    assert.match(agents, /split-headings\.md/, "AGENTS.md names this bundle's deck");
    assert.match(agents, /agent\/components\.json/);
    assert.match(agents, /capacity/i);
    const catalog = JSON.parse(fs.readFileSync(cat, 'utf8'));
    assert.ok(Array.isArray(catalog.components) && catalog.components.length > 0, 'catalog has components');
    assert.match(fs.readFileSync(path.join(dest, 'README.md'), 'utf8'), /Extend it with an AI agent/);
  });

  test('--no-agent produces a lean Marp-only bundle', () => {
    const lean = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-lean-'));
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), lean, 'indaco', '--no-agent'], { stdio: 'pipe' });
    const d = path.join(lean, 'split-headings');
    assert.ok(fs.existsSync(path.join(d, 'README.md')), 'still a valid bundle');
    assert.ok(!fs.existsSync(path.join(d, 'AGENTS.md')), 'no AGENTS.md');
    assert.ok(!fs.existsSync(path.join(d, 'agent')), 'no agent/ folder');
    assert.doesNotMatch(fs.readFileSync(path.join(d, 'README.md'), 'utf8'), /Extend it with an AI agent/);
    fs.rmSync(lean, { recursive: true, force: true });
  });
});

/**
 * The overflow-marker EXPORT SETTING the bundle ships with.
 *
 * An Export-to-Marp bundle renders through the browser RUNTIME inside marp-cli's
 * headless browser, so before this it inherited the runtime's authoring default: a
 * recipient opening a delivered deck saw a red ring, an "Overflows" tab, and
 * per-cell "Fix Me" overlays. The fix is not to hide the overflow — that ships a
 * clipped slide that looks finished — but to say who the signal is for.
 *
 * It is resolved from EXPORT inputs only: `--overflow-marker` for this one export,
 * `LATTICE_OVERFLOW_MARKER` for every export from this checkout. Never from the
 * deck — the level is a property of the render target, and a deck key would make a
 * one-time "quiet this for the board" choice a permanent, inherited property of
 * every deck derived from that bundle.
 */
describe('export-marp — the overflow-marker export setting', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-ovf-'));
  const DECK = path.join(REPO, 'examples', 'split-headings.md');
  after(() => fs.rmSync(tmp, { recursive: true, force: true }));

  // Both streams: the policy line is stdout, the `off` warning is stderr (the
  // same split lattice-emulator.js uses for its own overflow report).
  const exportWith = (slug, args = [], { deck = DECK, env = {} } = {}) => {
    const out = path.join(tmp, slug);
    const r = spawnSync('node', [TOOL, deck, out, ...args], {
      encoding: 'utf8',
      env: { ...process.env, LATTICE_OVERFLOW_MARKER: '', ...env },
    });
    assert.equal(r.status, 0, `export failed:\n${r.stderr}`);
    const dir = path.join(out, path.basename(deck).replace(/\.md$/, ''));
    return { said: r.stdout + r.stderr, md: fs.readFileSync(path.join(dir, `${path.basename(deck, '.md')}.md`), 'utf8') };
  };
  const settingsIn = (md) => readExportSettings(new JSDOM(`<body>${md}</body>`).window.document);

  test('defaults to reader, recorded in the export-settings block', () => {
    const { md, said } = exportWith('default');
    assert.match(said, /overflow marker: reader \(default\)/);
    assert.deepEqual(settingsIn(md), { overflowMarker: 'reader' });
    // Nothing that looks like an authoring key — that was the altitude error.
    assert.doesNotMatch(md, /^overflow-marker:/m);
  });

  test('the flag decides this one export, leaving the source deck untouched', () => {
    const { md, said } = exportWith('flag', ['--overflow-marker=off']);
    assert.deepEqual(settingsIn(md), { overflowMarker: 'off' });
    assert.match(said, /overflow marker: off \(--overflow-marker\)/);
    assert.equal(fs.readFileSync(DECK, 'utf8').includes('overflow-marker'), false, 'the source deck is untouched');
  });

  // The CLI's workspace-level answer — what the Studio's settings toggle is for.
  test('LATTICE_OVERFLOW_MARKER is the standing choice for every export', () => {
    const { md, said } = exportWith('env', [], { env: { LATTICE_OVERFLOW_MARKER: 'author' } });
    assert.deepEqual(settingsIn(md), { overflowMarker: 'author' });
    assert.match(said, /overflow marker: author \(workspace setting\)/);
  });

  test('the flag beats the workspace setting', () => {
    const { md } = exportWith('both', ['--overflow-marker=off'], { env: { LATTICE_OVERFLOW_MARKER: 'author' } });
    assert.deepEqual(settingsIn(md), { overflowMarker: 'off' });
  });

  // A stored setting can go stale. It must not break the export, and it must not
  // be swallowed — the deck-key version fell back silently.
  test('a stale workspace value falls back AND is named', () => {
    const { md, said } = exportWith('stale', [], { env: { LATTICE_OVERFLOW_MARKER: 'quiet' } });
    assert.deepEqual(settingsIn(md), { overflowMarker: 'reader' });
    assert.match(said, /LATTICE_OVERFLOW_MARKER='quiet' is not one of/);
  });

  // `off` is the only level where the artifact itself will not tell anyone, so the
  // console has to — and it has to admit that this export did not measure.
  test('off warns on the console and does not claim to have checked', () => {
    const { said } = exportWith('off-warn', ['--overflow-marker=off']);
    assert.match(said, /ONLY channel/);
    assert.match(said, /does not render, so it cannot measure overflow/);
    assert.match(said, /lattice-emulator\.js/, 'and names the command that does measure');
  });

  // A deck key is not an input any more. It does nothing, and `lint:deck` says so
  // (findStrayOverflowMarker) rather than leaving the author to wonder.
  test("a deck's own overflow-marker key is IGNORED", () => {
    const deck = path.join(tmp, 'authored.md');
    fs.writeFileSync(deck, ['---', 'marp: true', 'theme: indaco', 'overflow-marker: author', '---', '', '# A', ''].join('\n'));
    const { md, said } = exportWith('authored', [], { deck });
    assert.deepEqual(settingsIn(md), { overflowMarker: 'reader' }, 'the export default, not the deck key');
    assert.match(said, /overflow marker: reader \(default\)/);
  });

  test('a mistyped flag is a usage error, not a silent fallback', () => {
    for (const bad of ['--overflow-marker=quiet', '--overflow-markerZZZ=off', '--overflow-marker']) {
      const r = spawnSync('node', [TOOL, DECK, path.join(tmp, 'bad'), bad], { encoding: 'utf8' });
      assert.equal(r.status, 1, `expected '${bad}' to be rejected`);
    }
    const dupe = spawnSync('node', [TOOL, DECK, path.join(tmp, 'dupe'), '--overflow-marker=off', '--overflow-marker=author'], { encoding: 'utf8' });
    assert.equal(dupe.status, 1, 'a repeated flag is ambiguous, not first-wins');
  });
});
