/**
 * Unit: Export to Marp (tools/export-marp.js).
 *
 * Covers the pure helpers (front-matter theme read, asset localization) and an
 * end-to-end bundle: the exporter produces the expected layout, and the baked
 * deck.md divides into the same slides as the source — the portability contract.
 */

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const REPO = path.join(__dirname, '..', '..', '..');
const TOOL = path.join(REPO, 'tools', 'export-marp.js');
const { localizeAssets, readTheme } = require(TOOL);
const latticeEngine = require('../../../lib/engine');

describe('export-marp helpers', () => {
  test('readTheme reads the front-matter palette, or null', () => {
    assert.equal(readTheme('---\nmarp: true\ntheme: cuoio\n---\n\n# A'), 'cuoio');
    assert.equal(readTheme('# A\n\nno front matter'), null);
  });

  test('localizeAssets copies local images + rewrites paths; leaves remote alone', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-loc-'));
    const deckDir = path.join(tmp, 'src');
    fs.mkdirSync(deckDir);
    fs.writeFileSync(path.join(deckDir, 'logo.png'), 'PNGDATA');
    const dest = path.join(tmp, 'out');
    fs.mkdirSync(dest);
    const body = '![logo](logo.png)\n\n![remote](https://x/y.png)\n\n![missing](nope.png)';
    const { body: out, count } = localizeAssets(body, deckDir, dest);
    assert.match(out, /!\[logo\]\(assets\/logo\.png\)/, 'local image rewritten to assets/');
    assert.match(out, /!\[remote\]\(https:\/\/x\/y\.png\)/, 'remote URL untouched');
    assert.match(out, /!\[missing\]\(nope\.png\)/, 'dangling ref left as-is');
    assert.equal(count, 1);
    assert.ok(fs.existsSync(path.join(dest, 'assets', 'logo.png')), 'image copied into assets/');
    fs.rmSync(tmp, { recursive: true, force: true });
  });
});

describe('export-marp bundle (end-to-end)', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-e2e-'));
  let dest;
  before(() => {
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), tmp], { stdio: 'pipe' });
    dest = path.join(tmp, 'split-headings');
  });
  after(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test('produces the expected Marp-native bundle layout', () => {
    for (const f of [
      'split-headings.md', 'README.md', 'marp.config.cjs', 'package.json',
      '.vscode/settings.json',
      'lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css',
      'mermaid-v11.min.js', 'lattice-runtime.min.js',
    ]) {
      assert.ok(fs.existsSync(path.join(dest, f)), `bundle is missing ${f}`);
    }
    // No emulator / dist/ folder — the bundle is rendered with Marp.
    assert.ok(!fs.existsSync(path.join(dest, 'dist')), 'bundle must not ship a dist/ folder');
    assert.ok(!fs.existsSync(path.join(dest, 'dist', 'lattice-emulator.js')), 'no bundled emulator');
  });

  test('bundled themes are the minified build; .vscode registers them', () => {
    const carta = fs.readFileSync(path.join(dest, 'themes', 'indaco.css'), 'utf8');
    assert.match(carta, /GENERATED by tools\/build-css\.js \(minified\)/, 'theme is the minified dist build');
    assert.match(carta, /@theme indaco/, 'minified theme keeps its @theme name');
    const settings = JSON.parse(fs.readFileSync(path.join(dest, '.vscode', 'settings.json'), 'utf8'));
    assert.deepEqual(settings['markdown.marp.themes'],
      ['lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css']);
  });

  test('deck ends with the runtime scripts (browser render) under a lint-ignore', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /<!-- markdownlint-disable MD033 -->\n<script src="mermaid-v11\.min\.js"><\/script>\n<script src="lattice-runtime\.min\.js"><\/script>\s*$/,
      'markdown ends with the lint-ignore + mermaid + runtime script tags');
  });

  test('baked deck.md states split: rule and divides into the same slides', () => {
    const baked = fs.readFileSync(path.join(dest, 'split-headings.md'), 'utf8');
    assert.match(baked, /split: rule/, 'splits are baked → split: rule');
    const original = fs.readFileSync(path.join(REPO, 'examples', 'split-headings.md'), 'utf8');
    const engine = latticeEngine.createEngine();
    const count = (src) => (engine.render(src).html.match(/<section[\s>]/g) || []).length;
    assert.equal(count(baked), count(original), 'baked deck divides identically to the source');
  });

  // #1256 — the two defects that made a real exported deck come out wrong.
  test('ships every font lattice.css references, beside the stylesheet', () => {
    const css = fs.readFileSync(path.join(dest, 'lattice.css'), 'utf8');
    const refs = [...css.matchAll(/url\(\s*['"]?fonts\/([^)'"\s]+)['"]?\s*\)/g)].map((m) => m[1]);
    assert.ok(refs.length > 0, 'the bundled stylesheet references fonts at all');
    for (const f of new Set(refs)) {
      assert.ok(fs.existsSync(path.join(dest, 'fonts', f)), `bundle is missing fonts/${f}`);
    }
  });

  test('bundled CSS is marp-scopable: no rule LEADS with :is(section…)', () => {
    // marp-core scopes off the leftmost compound, so a leading
    // `:is(section.x, figure.x)` head becomes a slide-inside-a-slide and matches
    // nothing. Every stylesheet in the bundle goes through the distribution.
    for (const f of ['lattice.css', 'themes/indaco.css', 'themes/indaco-dark.css']) {
      const css = fs.readFileSync(path.join(dest, f), 'utf8');
      const bad = css.match(/(^|[{};])\s*:is\([^)]*section[^)]*\)/g) || [];
      assert.deepEqual(bad, [], `${f} still leads ${bad.length} rule(s) with :is(section…)`);
    }
  });

  // The auto-glossary APPENDS a whole slide from front-matter `acronyms:`. It is a
  // source transform the recipient's Marp will never run, so the export must bake
  // it exactly like splits — before #1256 the exported deck was one slide short,
  // and the slide before it still announced "the next slide is generated".
  test('bakes the auto-glossary slide into the exported deck (no slide is lost)', () => {
    const tmpG = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-gloss-'));
    try {
      const source = path.join(REPO, 'examples', 'auto-glossary.md');
      execFileSync('node', [TOOL, source, tmpG], { stdio: 'pipe' });
      const baked = fs.readFileSync(path.join(tmpG, 'auto-glossary', 'auto-glossary.md'), 'utf8');
      // The generated slide is present, and its own trigger is consumed so a
      // re-render can't append it twice.
      assert.match(baked, /^<!-- _class: glossary/m, 'the generated glossary slide is baked in');
      assert.doesNotMatch(baked, /^\s*glossary:\s*auto\s*$/m, 'the trigger is stripped');
      // Slide-count parity with what the CLI actually renders. `render()` is the
      // raw engine — the emulator runs appendAutoGlossary BEFORE it (the step the
      // export was missing), so that is the baseline the export must match.
      const { appendAutoGlossary } = require('../../../lib/core/glossary-auto.mjs');
      const engine = latticeEngine.createEngine();
      const count = (src) => (engine.render(src).html.match(/<section[\s>]/g) || []).length;
      const original = fs.readFileSync(source, 'utf8');
      assert.equal(count(baked), count(appendAutoGlossary(original)),
        'the exported deck has the same slide count as the CLI renders');
      assert.equal(count(baked), count(original) + 1, 'and it is exactly one MORE than the raw source');
    } finally {
      fs.rmSync(tmpG, { recursive: true, force: true });
    }
  });

  test('marp.config.cjs + .vscode enable HTML so the runtime tags survive', () => {
    assert.match(fs.readFileSync(path.join(dest, 'marp.config.cjs'), 'utf8'), /html:\s*true/);
    const settings = JSON.parse(fs.readFileSync(path.join(dest, '.vscode', 'settings.json'), 'utf8'));
    assert.equal(settings['markdown.marp.enableHtml'], true);
  });

  test('package.json pins marp-cli only', () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(dest, 'package.json'), 'utf8'));
    assert.ok(pkg.dependencies['@marp-team/marp-cli']);
    // No @slidewright/lattice dep — it is unpublished, so it would 404 `npm
    // install`; the bundle is rendered with Marp, not a bundled engine.
    assert.strictEqual(pkg.dependencies['@slidewright/lattice'], undefined);
  });

  test('ships the agent kit by default (AGENTS.md + the catalog under agent/)', () => {
    assert.ok(fs.existsSync(path.join(dest, 'AGENTS.md')), 'AGENTS.md present');
    const cat = path.join(dest, 'agent', 'components.json');
    assert.ok(fs.existsSync(cat), 'agent/components.json present');
    const agents = fs.readFileSync(path.join(dest, 'AGENTS.md'), 'utf8');
    assert.match(agents, /split-headings\.md/, "AGENTS.md names this bundle's deck");
    assert.match(agents, /agent\/components\.json/);
    assert.match(agents, /capacity/i);
    const catalog = JSON.parse(fs.readFileSync(cat, 'utf8'));
    assert.ok(Array.isArray(catalog.components) && catalog.components.length > 0, 'catalog has components');
    assert.match(fs.readFileSync(path.join(dest, 'README.md'), 'utf8'), /Extend it with an AI agent/);
  });

  test('--no-agent produces a lean Marp-only bundle', () => {
    const lean = fs.mkdtempSync(path.join(os.tmpdir(), 'exp-lean-'));
    execFileSync('node', [TOOL, path.join(REPO, 'examples', 'split-headings.md'), lean, 'indaco', '--no-agent'], { stdio: 'pipe' });
    const d = path.join(lean, 'split-headings');
    assert.ok(fs.existsSync(path.join(d, 'README.md')), 'still a valid bundle');
    assert.ok(!fs.existsSync(path.join(d, 'AGENTS.md')), 'no AGENTS.md');
    assert.ok(!fs.existsSync(path.join(d, 'agent')), 'no agent/ folder');
    assert.doesNotMatch(fs.readFileSync(path.join(d, 'README.md'), 'utf8'), /Extend it with an AI agent/);
    fs.rmSync(lean, { recursive: true, force: true });
  });
});
