/**
 * The `dist-kits` branch-root staging files (`tools/kit-branch/root/`).
 *
 * `.github/workflows/publish-kits.yml` copies this folder to the root of the
 * orphan `dist-kits` branch. The Marp kit itself lands one level down, in
 * `marp/`, and its own `.vscode/settings.json` registers stylesheets by
 * WORKSPACE-relative path — so someone who opens the branch ROOT as their VS
 * Code workspace, rather than `marp/`, resolves nothing.
 *
 * THE FAILURE THIS PINS IS SILENT. A wrong theme path does not error; Marp
 * renders the deck unstyled and says nothing. The Marp kit's own README calls
 * that out, and it is the reason the branch root carries a fallback
 * `.vscode/settings.json` at all.
 *
 * The fallback is HAND-WRITTEN while the kit's own copy is GENERATED by
 * `vscodeSettings()` from the `THEME` constant. That is two renderings of one
 * fact. Change `THEME`, or register a fourth stylesheet, and they diverge with
 * nothing to catch it — and the symptom is the silent one above. This test is
 * the catch: it derives what the fallback SHOULD say from the generator and
 * compares, so the drift fails here instead of in someone's editor.
 *
 * It is a test rather than a build step on purpose. Generating the file would
 * move it into the build graph and out of `dist/`, which would break
 * `build-agent-kit.mjs`'s measured `uncommitted` classification
 * (test/unit/tools/uncommitted-steps.test.js) for no gain — the invariant is
 * one-way and cheap to assert.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..', '..', '..');
const STAGE_DIR = path.join(ROOT, 'tools', 'kit-branch', 'root');
const { vscodeSettings } = require('../../../tools/build-marp-kit.js');

test('dist-kits branch-root staging', async (t) => {
  await t.test('the root .vscode fallback matches the kit generator, prefixed with marp/', () => {
    const generated = JSON.parse(vscodeSettings());
    const fallback = JSON.parse(
      fs.readFileSync(path.join(STAGE_DIR, '.vscode', 'settings.json'), 'utf8'),
    );

    const expected = generated['markdown.marp.themes'].map((p) => p.replace(/^\.\//, './marp/'));
    assert.deepEqual(
      fallback['markdown.marp.themes'],
      expected,
      'The branch-root .vscode/settings.json has drifted from tools/build-marp-kit.js ' +
        "vscodeSettings(). Re-derive it: every theme path, with './' replaced by './marp/'. " +
        'Left to drift, opening the dist-kits branch root in VS Code renders slides ' +
        'UNSTYLED WITH NO ERROR.',
    );

    assert.equal(
      fallback['markdown.marp.enableHtml'],
      generated['markdown.marp.enableHtml'],
      'enableHtml must match the kit; without it a deck\'s trailing <script> tags print as ' +
        'literal text across the preview.',
    );
  });

  await t.test('every fallback theme path resolves against the published layout', () => {
    // The published tree is `marp/` + `agent/` + these root files, so a path of
    // the form `./marp/<file>` must name a file the Marp kit actually ships.
    const { buildKit } = require('../../../tools/build-marp-kit.js');
    const kit = buildKit();
    const fallback = JSON.parse(
      fs.readFileSync(path.join(STAGE_DIR, '.vscode', 'settings.json'), 'utf8'),
    );
    for (const p of fallback['markdown.marp.themes']) {
      const rel = p.replace(/^\.\/marp\//, '');
      assert.ok(
        kit.has(rel),
        `${p} names ${rel}, which dist/marp-kit does not contain — the fallback would ` +
          'resolve to nothing and the slides would render unstyled, silently.',
      );
    }
  });

  await t.test('the branch-root README does not promise a trigger the workflow lacks', () => {
    // The claim "republished on every push that changes an input" is only true
    // while publish-kits.yml actually carries a push trigger. The same sentence
    // was wrong about the old marp workflow for two weeks
    // (2026-08-30-agent-kit-and-dist-kits.md §7), which is why it is pinned.
    const readme = fs.readFileSync(path.join(STAGE_DIR, 'README.md'), 'utf8');
    const workflow = fs.readFileSync(
      path.join(ROOT, '.github', 'workflows', 'publish-kits.yml'),
      'utf8',
    );
    if (/republished on every push/i.test(readme)) {
      assert.match(
        workflow,
        /^on:\s*$[\s\S]{0,400}?^\s{2}push:$/m,
        'tools/kit-branch/root/README.md claims the branch is republished on every push, ' +
          'but publish-kits.yml has no push trigger. Fix whichever one is wrong.',
      );
    }
  });
});
