// Unit coverage for tools/build-gotchas-index.js — the gotchas symptom index
// (dist/engineering/gotchas.md is rendered from the entry headings in engineering/gotchas/,
// and never committed).

const { describe, test } = require('node:test');
const assert = require('node:assert/strict');
const { slugify, parseHeadings, collect, render, rowFor, billedRow, rowCostProblems, strayGuideEntries, main, ROW_CAP, LINK_BASE } = require('../../../tools/build-gotchas-index');

// A fixture topic, shaped like what collect() returns — including the anchor map,
// which is what rowFor reads.
const topic = (file, title, entries) => ({
  slug: file.replace(/\.md$/, ''),
  file,
  title,
  entries,
  anchors: new Map(entries.map((e) => [e, slugify(e)])),
});

describe('gotchas-index', () => {
  // Anchors are the whole load-bearing claim of this index: 144 links depend on
  // matching what GitHub mints. These are real headings from the corpus, pinned as
  // literals — a regression in the markdown-stripping layer moves them.
  describe('slugify', () => {
    const cases = [
      ['Pie wedge borders off-by-one (`nth-child` vs `<defs>`)', 'pie-wedge-borders-off-by-one-nth-child-vs-defs'],
      ['`:where(:root)` token blocks are dropped from every rendered slide', 'whereroot-token-blocks-are-dropped-from-every-rendered-slide'],
      // Two spaces around the slash → TWO hyphens. Collapsing whitespace runs here is
      // the single most common way a hand-rolled slugger mints dead links.
      ['Marp / Chromium `foreignObject` creates anonymous grid items', 'marp--chromium-foreignobject-creates-anonymous-grid-items'],
      // Non-ASCII punctuation goes, and the spaces that flanked it each become a hyphen.
      ['`margin` corrupts measured layout (virtual lists, the Fit Spine) — HARD RULE #20', 'margin-corrupts-measured-layout-virtual-lists-the-fit-spine--hard-rule-20'],
      // `_` SURVIVES slugging — stripping it as an emphasis marker mints an anchor
      // GitHub never generates.
      ['The `PORTAL_TOKENS` subset', 'the-portal_tokens-subset'],
    ];
    for (const [heading, want] of cases) {
      test(`${heading.slice(0, 48)}…`, () => assert.equal(slugify(heading), want));
    }

    test('a link contributes only its text, never its URL', () => {
      assert.equal(slugify('See [the note](../decisions/2026-01-01-x.md) first'), 'see-the-note-first');
    });

    // A shared slugger dedupes; collect() therefore uses one per file AND rejects any
    // collision outright, so no anchor is ever positional. Both halves are exercised on
    // fixtures in 'collect — on fixture corpora' below, rather than asserted here about
    // the library.
  });

  describe('render', () => {
    const topics = [
      topic('charts.md', 'Charts', ['Pie wedges misalign', 'Caption is swallowed']),
      topic('css.md', 'CSS', ['A reset declaration does nothing']),
    ];
    const out = render(topics);

    test('one heading per topic, linking to the topic file', () => {
      assert.match(out, /### \[Charts\]\(\.\.\/\.\.\/engineering\/gotchas\/charts\.md\)/);
      assert.match(out, /### \[CSS\]\(\.\.\/\.\.\/engineering\/gotchas\/css\.md\)/);
    });
    test('one row per entry, linking to the entry anchor', () => {
      assert.match(out, /- \[Pie wedges misalign\]\(\.\.\/\.\.\/engineering\/gotchas\/charts\.md#pie-wedges-misalign\)/);
    });
    // The output lives in dist/engineering/; the cap governs the heading an author writes,
    // so the constant link prefix is added at render time and never billed.
    test('the row cap measures the row without the link prefix', () => {
      assert.equal(LINK_BASE, '../../engineering/');
      assert.ok(!rowFor(topics[0], 'Pie wedges misalign').includes(LINK_BASE));
    });
    test('the closing line carries no totals', () => {
      assert.doesNotMatch(out, /\d+ entries —/);
      assert.match(out, /Generated by `npm run gotchas:index`/);
    });
  });

  describe('rowCostProblems (the per-row budget)', () => {
    test('an ordinary row is silent', () => {
      assert.deepEqual(rowCostProblems([topic('css.md', 'CSS', ['A reset declaration does nothing'])]), []);
    });

    // The heading is the lever precisely because it is paid twice — as the link label
    // and again, slugged, as the anchor. A heading a little over HALF the cap is
    // therefore already over it, and that is the number an author has to feel.
    test('a long heading trips it — the heading is paid TWICE per row', () => {
      const long = `A symptom sentence that just keeps going ${'and going '.repeat(11)}forever`;
      assert.ok(long.length < ROW_CAP, 'sanity: the heading ALONE is inside the cap');
      const [problem] = rowCostProblems([topic('css.md', 'CSS', [long])]);
      assert.match(problem, /over the 280 cap/);
      assert.match(problem, /rendered TWICE per row/);
      assert.match(problem, /^css\.md » "A symptom sentence/, 'the message must name the offending entry');
    });

    // THE MERGE-SAFETY PROPERTY, and the reason the filename is not billed. A topic
    // filename is shared by every entry under it, so billing it would let PR A (rename
    // the topic) and PR B (add a near-cap entry) each pass alone while the second to
    // merge fails for the other's change — #1547, with the error blaming a heading its
    // author never touched. The cost of an entry must depend only on that entry.
    test('the topic filename is NOT billed — a rename cannot re-price a sibling entry', () => {
      const heading = `A heading sized to sit just under the cap ${'padding '.repeat(9)}end`;
      const short = topic('ci.md', 'CI', [heading]);
      assert.deepEqual(rowCostProblems([short]), [], 'sanity: this entry fits');
      const renamed = topic(`${'a'.repeat(80)}.md`, 'Renamed', [heading]);
      assert.ok(rowFor(renamed, heading).length > ROW_CAP, 'sanity: the FULL row is over the cap');
      assert.deepEqual(rowCostProblems([renamed]), [], 'a topic rename must not trip a sibling entry');
    });

    test('billedRow is the heading twice and nothing else', () => {
      const b = billedRow(topic('ci.md', 'CI', ['A symptom']), 'A symptom');
      assert.equal(b, '- [A symptom](#a-symptom)');
      assert.ok(!b.includes('ci.md'), 'the topic filename must not be billed');
    });

    // The problem quotes a TRUNCATED heading — an over-cap row is over-cap because its
    // heading is long, so echoing it whole would print the thing it is complaining about.
    test('the message truncates the heading it names', () => {
      const long = 'x'.repeat(400);
      const [problem] = rowCostProblems([topic('css.md', 'CSS', [long])]);
      assert.ok(problem.includes(`"${'x'.repeat(80)}…"`), `got: ${problem.slice(0, 160)}`);
      assert.ok(problem.length < 600, `the message is itself ${problem.length} characters`);
    });

    test('every offending entry is reported, not just the first', () => {
      const long = 'y'.repeat(200);
      assert.equal(rowCostProblems([topic('css.md', 'CSS', [long, `${long}z`])]).length, 2);
    });

    // NO aggregate over the corpus here — not even "the widest row is still near the cap".
    // A PR that shortens or deletes the widest gotcha heading would fail such an assertion
    // for doing exactly what the cap's error message asks of it. Per-entry is the only safe
    // shape (#1547); the cap's ratchet value is a design fact, recorded in the tool's header.
    test('every entry in the live corpus is inside the cap', () => {
      assert.deepEqual(rowCostProblems(collect().topics), []);
    });
  });

  // The cap is only a GATE because of ten lines in `main`. Deleting them, moving them
  // after the write, or weakening the condition leaves every assertion above green — so
  // these drive the real CLI entry point against a fixture corpus instead.
  describe('main — the wiring that makes the cap a gate', () => {
    const fsx = require('node:fs');
    const os = require('node:os');
    const pathx = require('node:path');

    // A fixture repo: one topic file, and an output path that does not exist yet.
    const fixture = (headings) => {
      const root = fsx.mkdtempSync(pathx.join(os.tmpdir(), 'gotchas-gate-'));
      const dir = pathx.join(root, 'gotchas');
      fsx.mkdirSync(dir);
      fsx.writeFileSync(pathx.join(dir, 'ci.md'), `# Gotchas — CI\n\n${headings.map((h) => `## ${h}\n\nbody\n`).join('\n')}`);
      const guide = pathx.join(root, 'gotchas.md');
      fsx.writeFileSync(guide, '# Gotchas\n\n## How to use this file\n\nprose\n');
      return { dir, out: pathx.join(root, 'out', 'gotchas.md'), guide };
    };
    // Captures the tool's stderr rather than only swallowing it: an exit code alone
    // cannot tell a CAP refusal from any other.
    const capture = (fn) => {
      const w = process.stderr.write.bind(process.stderr);
      let err = '';
      process.stderr.write = (chunk) => { err += chunk; return true; };
      try { return { code: fn(), err }; } finally { process.stderr.write = w; }
    };
    const overCap = `A heading well past the cap ${'and then some more '.repeat(12)}end`;

    // Write runs inside `npm install`; one bad heading must not break every install.
    test('write mode WARNS on an over-cap row and still writes', () => {
      const { dir, out, guide } = fixture([overCap, 'A short symptom']);
      const { code, err } = capture(() => main([], { dir, out, guide }));
      assert.equal(code, 0, 'write must not fail an install');
      assert.match(err, /over the 280 cap/, 'it must still say why');
      assert.match(fsx.readFileSync(out, 'utf8'), /A short symptom/);
    });

    test('check mode REFUSES the same row', () => {
      const { dir, out, guide } = fixture([overCap]);
      const { code, err } = capture(() => main(['--check'], { dir, out, guide }));
      assert.equal(code, 1);
      assert.match(err, /over the 280 cap/);
    });

    // The negative control: without it, a `main` that returned 1 unconditionally under
    // --check would pass the assertion above.
    test('an in-cap corpus writes and then checks clean', () => {
      const { dir, out, guide } = fixture(['A short symptom']);
      assert.equal(main([], { dir, out, guide }), 0, 'write must succeed');
      assert.match(fsx.readFileSync(out, 'utf8'), /- \[A short symptom\]\(\.\.\/\.\.\/engineering\/gotchas\/ci\.md#a-short-symptom\)/);
      assert.equal(main(['--check'], { dir, out, guide }), 0, 'check must then pass');
    });

    // Check reads the SOURCES only. With no committed output, a check that read the
    // output would fail every fresh checkout.
    test('check never reads the output, so a missing output is fine', () => {
      const { dir, out, guide } = fixture(['A short symptom']);
      assert.ok(!fsx.existsSync(out));
      assert.equal(main(['--check'], { dir, out, guide }), 0);
    });
  });

  describe('the live engineering/gotchas/ folder', () => {
    const { topics, errors } = collect();
    test('every topic file is well-formed (collect() is clean)', () => {
      assert.deepEqual(errors, [], `malformed topic files:\n${errors.join('\n')}`);
      assert.ok(topics.length >= 5, `expected the split corpus, got ${topics.length} topics`);
    });
    test('every entry has a unique anchor within its file', () => {
      for (const t of topics) {
        const anchors = [...t.anchors.values()];
        assert.equal(new Set(anchors).size, anchors.length, `${t.file}: two entries share an anchor`);
      }
    });
    // The index is the ONLY route to these files now, so every row must resolve. This
    // re-derives each anchor from the topic file INDEPENDENTLY of the row-building path
    // (re-parse the file, re-slug its headings) — the previous version of this test
    // compared collect() against itself and could not fail.
    test('every rendered row resolves to a real heading in a real file', () => {
      const fs2 = require('node:fs');
      const path2 = require('node:path');
      const root = path2.join(__dirname, '../../../engineering');
      const index = render(topics);
      const rows = [...index.matchAll(/^- \[(.+)\]\(\.\.\/\.\.\/engineering\/gotchas\/([^)#]+)#([^)]+)\)$/gm)];
      assert.ok(rows.length >= 100, `expected the full index, parsed ${rows.length} rows`);
      const anchorsOf = new Map();
      for (const [, , file] of rows) {
        if (anchorsOf.has(file)) continue;
        const full = path2.join(root, 'gotchas', file);
        assert.ok(fs2.existsSync(full), `${file}: row points at a file that does not exist`);
        const Slugger = require('github-slugger').default ?? require('github-slugger');
        const slugger = new Slugger();
        const set = new Set();
        for (const h of parseHeadings(fs2.readFileSync(full, 'utf8'))) set.add(slugger.slug(h.text));
        anchorsOf.set(file, set);
      }
      for (const [, label, file, anchor] of rows) {
        assert.ok(anchorsOf.get(file).has(anchor), `${file}#${anchor} does not exist (row: ${label.slice(0, 60)})`);
      }
    });
  });
  // Heading extraction has to agree with a REAL parser about what a heading is. Every
  // case here is one an adversarial pass broke in the line-scanning version that shipped
  // first — and each one failed SILENTLY, with `--check` exiting 0.
  describe('parseHeadings — agreeing with the renderer', () => {
    const h2s = (text) => parseHeadings(text).filter((h) => h.level === 2).map((h) => h.text);

    // The break that mattered: an orphaned closing fence — exactly what a gotcha about a
    // swallowed fence quotes — flipped a parity toggle and deleted the REST OF THE FILE
    // from the index.
    test('an unbalanced fence inside an example does not swallow later entries', () => {
      const doc = ['# T', '', '## A', '', '````md', '```mermaid', 'graph TD; A-->B', '````', '', '## B', '', '## C'].join('\n');
      assert.deepEqual(h2s(doc), ['A', 'B', 'C']);
    });
    test('a heading inside a fence is not an entry', () => {
      assert.deepEqual(h2s(['# T', '', '## Real', '', '```sh', '## not a heading', '```'].join('\n')), ['Real']);
    });
    test('a heading inside an HTML comment is not an entry', () => {
      assert.deepEqual(h2s(['# T', '', '## Real', '', '<!--', '## commented out', '-->'].join('\n')), ['Real']);
    });
    test('a setext heading IS an entry — the renderer says so', () => {
      assert.deepEqual(h2s(['# T', '', 'Underlined heading', '---', '', 'body', '', '## Atx'].join('\n')), ['Underlined heading', 'Atx']);
    });
    test('a closing sequence is not part of the text', () => {
      assert.deepEqual(h2s(['# T', '', '## Closing sequence ##'].join('\n')), ['Closing sequence']);
    });
    test('text is the RENDERED text — code, emphasis and link markup are consumed', () => {
      const [h] = parseHeadings('## A `code` and **bold** and [a link](x.md)\n').filter((x) => x.level === 2);
      assert.equal(h.text, 'A code and bold and a link', 'what GitHub slugs');
      assert.equal(h.raw, 'A `code` and **bold** and [a link](x.md)', 'what the row label keeps');
    });
  });

  // Every guard below was unreachable from the live corpus, so each is exercised on a
  // fixture directory. `collect(dir)` exists for exactly this reason.
  describe('collect — on fixture corpora', () => {
    const os = require('node:os');
    const fsx = require('node:fs');
    const pathx = require('node:path');
    const withCorpus = (files, fn) => {
      const dir = fsx.mkdtempSync(pathx.join(os.tmpdir(), 'gotchas-fixture-'));
      try {
        for (const [name, body] of Object.entries(files)) fsx.writeFileSync(pathx.join(dir, name), body);
        return fn(dir);
      } finally {
        fsx.rmSync(dir, { recursive: true, force: true });
      }
    };

    test('an entry after an unbalanced fence still reaches the index', () => {
      const { topics, errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '## A', '', '````md', '```x', '````', '', '## B'].join('\n') },
        (d) => collect(d),
      );
      assert.deepEqual(errors, []);
      assert.deepEqual(topics[0].entries, ['A', 'B']);
    });

    test('two headings that slug alike are REJECTED, so no anchor is positional', () => {
      // GitHub would mint `dup` and `dup-1` in document order — correct, but inserting an
      // entry above one silently re-anchors the other and rots every deep link to it.
      const { errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '## Dup!', '', 'body', '', '## Dup', '', 'body'].join('\n') },
        (d) => collect(d),
      );
      assert.equal(errors.length, 1, errors.join('\n'));
      assert.match(errors[0], /slug to the same anchor/);
    });

    test('a body heading that collides with an entry is caught too', () => {
      const { errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '### Shared name', '', '## Shared name'].join('\n') },
        (d) => collect(d),
      );
      assert.match(errors.join('\n'), /slug to the same anchor/);
    });

    // A heading ending in an ODD run of backslashes escapes the row template's closing
    // bracket: the link never forms and the row renders as literal text with the URL
    // beside it. Verified by RENDERING, because the source looks fine either way — and
    // note the first fix attempt (reject the raw label, fall back to rendered text)
    // could not work, since the fallback ends in the same backslash.
    test('a heading ending in a backslash still renders as a link', () => {
      const MarkdownIt = require('markdown-it');
      const md = new MarkdownIt();
      const bs = String.fromCharCode(92);
      const { topics, errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', `## A windows path C:${bs}`, '', 'body'].join('\n') },
        (d) => collect(d),
      );
      assert.deepEqual(errors, []);
      const row = render(topics).split('\n').find((l) => l.startsWith('- '));
      assert.match(md.render(row), /<a href="\.\.\/\.\.\/engineering\/gotchas\/f\.md#/, `row did not render as a link: ${row}`);
    });

    test('a folder README is skipped, not treated as a malformed topic', () => {
      const { topics, errors } = withCorpus(
        { 'README.md': '# What this folder is\n\nProse, no entries.\n', 'f.md': '# Gotchas — F\n\n## A\n' },
        (d) => collect(d),
      );
      assert.deepEqual(errors, [], 'a README must not hard-fail the build');
      assert.deepEqual(topics.map((t) => t.file), ['f.md']);
    });

    test('a topic file with no entries is still an error', () => {
      const { errors } = withCorpus({ 'f.md': '# Gotchas — F\n\nprose only\n' }, (d) => collect(d));
      assert.match(errors.join('\n'), /no .* entries/);
    });

    test('the h1 is taken from the document, not from a fenced comment', () => {
      const { topics } = withCorpus(
        { 'f.md': ['```sh', '# not the title', '```', '', '# Gotchas — Real Title', '', '## A'].join('\n') },
        (d) => collect(d),
      );
      assert.equal(topics[0].title, 'Real Title');
    });
  });

  // The guide is hand-written now, so an entry written into it is not destroyed — but it is
  // never listed either, because the index is built from engineering/gotchas/ only.
  describe('strayGuideEntries — a gotcha authored into the guide', () => {
    test('a stray heading is refused, naming where it belongs', () => {
      const problems = strayGuideEntries('# Gotchas\n\n## How to use this file\n\n## A gotcha someone appended here\n');
      assert.equal(problems.length, 1);
      assert.match(problems[0], /written into engineering\/gotchas\.md/);
    });
    test('the guide\'s own headings and fenced examples are not entries', () => {
      assert.deepEqual(strayGuideEntries('# Gotchas\n\n## How to use this file\n\n```md\n## an example\n```\n'), []);
    });
    test('the live guide is clean', () => {
      const fs = require('node:fs');
      const path = require('node:path');
      assert.deepEqual(strayGuideEntries(fs.readFileSync(path.join(__dirname, '../../../engineering/gotchas.md'), 'utf8')), []);
    });
  });

});
