// Unit coverage for tools/build-gotchas-index.js — the gotchas symptom index
// (engineering/gotchas.md is rendered from the entry headings in engineering/gotchas/).

const { describe, test } = require('node:test');
const assert = require('node:assert/strict');
const { slugify, parseHeadings, collect, render, rowFor, headingFor, verify, splice, FOOTER } = require('../../../tools/build-gotchas-index');

// A fixture topic, shaped like what collect() returns — including the anchor map,
// which is what rowFor reads.
const topic = (file, title, entries) => ({
  slug: file.replace(/\.md$/, ''),
  file,
  title,
  entries,
  anchors: new Map(entries.map((e) => [e, slugify(e)])),
});

describe('gotchas-index', () => {
  // Anchors are the whole load-bearing claim of this index: 144 links depend on
  // matching what GitHub mints. These are real headings from the corpus, pinned as
  // literals — a regression in the markdown-stripping layer moves them.
  describe('slugify', () => {
    const cases = [
      ['Pie wedge borders off-by-one (`nth-child` vs `<defs>`)', 'pie-wedge-borders-off-by-one-nth-child-vs-defs'],
      ['`:where(:root)` token blocks are dropped from every rendered slide', 'whereroot-token-blocks-are-dropped-from-every-rendered-slide'],
      // Two spaces around the slash → TWO hyphens. Collapsing whitespace runs here is
      // the single most common way a hand-rolled slugger mints dead links.
      ['Marp / Chromium `foreignObject` creates anonymous grid items', 'marp--chromium-foreignobject-creates-anonymous-grid-items'],
      // Non-ASCII punctuation goes, and the spaces that flanked it each become a hyphen.
      ['`margin` corrupts measured layout (virtual lists, the Fit Spine) — HARD RULE #20', 'margin-corrupts-measured-layout-virtual-lists-the-fit-spine--hard-rule-20'],
      // `_` SURVIVES slugging — stripping it as an emphasis marker mints an anchor
      // GitHub never generates.
      ['The `PORTAL_TOKENS` subset', 'the-portal_tokens-subset'],
    ];
    for (const [heading, want] of cases) {
      test(`${heading.slice(0, 48)}…`, () => assert.equal(slugify(heading), want));
    }

    test('a link contributes only its text, never its URL', () => {
      assert.equal(slugify('See [the note](../decisions/2026-01-01-x.md) first'), 'see-the-note-first');
    });

    // A shared slugger dedupes; collect() therefore uses one per file AND rejects any
    // collision outright, so no anchor is ever positional. Both halves are exercised on
    // fixtures in 'collect — on fixture corpora' below, rather than asserted here about
    // the library.
  });

  describe('render', () => {
    const topics = [
      topic('charts.md', 'Charts', ['Pie wedges misalign', 'Caption is swallowed']),
      topic('css.md', 'CSS', ['A reset declaration does nothing']),
    ];
    const out = render(topics);

    test('one heading per topic, linking to the topic file', () => {
      assert.match(out, /### \[Charts\]\(gotchas\/charts\.md\)/);
      assert.match(out, /### \[CSS\]\(gotchas\/css\.md\)/);
    });
    test('one row per entry, linking to the entry anchor', () => {
      assert.match(out, /- \[Pie wedges misalign\]\(gotchas\/charts\.md#pie-wedges-misalign\)/);
    });
    test('the closing line carries no totals', () => {
      assert.doesNotMatch(out, /\d+ entries —/);
      assert.match(out, /Generated by `npm run gotchas:index`/);
    });
  });

  // Same relaxation as the decisions index, for the same reason (#1547): this file is
  // generated from EVERY topic file and committed, so two PRs each adding a gotcha
  // both regenerate it and the second to merge is rebased onto a `main` it never saw.
  describe('verify (the --check assertion)', () => {
    const topics = [
      topic('charts.md', 'Charts', ['Pie wedges misalign', 'Caption is swallowed']),
      topic('css.md', 'CSS', ['A reset declaration does nothing']),
    ];
    const index = (t) => `# Gotchas\n\n## Symptom index\n\n${render(t)}\n\ntrailer\n`;

    test('the canonical rendering verifies clean', () => {
      assert.deepEqual(verify(index(topics), topics), []);
    });

    describe('states two concurrent PRs actually produce', () => {
      test('passes when a rebase brought in another PR\'s entry and its row', () => {
        const theirs = [...topics, topic('ci.md', 'CI', ['A job times out'])];
        assert.deepEqual(verify(index(theirs), theirs), []);
      });
      test('passes when rows sit in merge order rather than file order', () => {
        const canonical = index(topics);
        const [a, b] = topics[0].entries;
        const swapped = canonical.replace(
          `${rowFor(topics[0], a)}\n${rowFor(topics[0], b)}`,
          `${rowFor(topics[0], b)}\n${rowFor(topics[0], a)}`,
        );
        assert.notEqual(swapped, canonical, 'the fixture must actually have reordered two rows');
        assert.deepEqual(verify(swapped, topics), []);
      });
    });

    describe('still fails on what a PR IS responsible for', () => {
      test('a new entry has no row', () => {
        const withNew = [topic('charts.md', 'Charts', [...topics[0].entries, 'A brand new symptom']), topics[1]];
        const problems = verify(index(topics), withNew);
        assert.equal(problems.length, 1, problems.join('\n'));
        assert.match(problems[0], /A brand new symptom": no row/);
      });
      test('a heading was reworded, so the row and its anchor drifted', () => {
        const reworded = [topic('charts.md', 'Charts', ['Pie wedges misalign badly', 'Caption is swallowed']), topics[1]];
        const problems = verify(index(topics), reworded);
        assert.ok(problems.some((p) => /no row in the index/.test(p)), problems.join('\n'));
        assert.ok(problems.some((p) => /delete the row/.test(p)), problems.join('\n'));
      });
      test('a row survives an entry that was deleted', () => {
        const fewer = [topic('charts.md', 'Charts', ['Pie wedges misalign']), topics[1]];
        const problems = verify(index(topics), fewer);
        assert.equal(problems.length, 1, problems.join('\n'));
        assert.match(problems[0], /Caption is swallowed" is listed under gotchas\/charts\.md but no such entry/);
      });
      test('an entry is listed twice', () => {
        const doubled = index(topics).replace(rowFor(topics[1], topics[1].entries[0]), `${rowFor(topics[1], topics[1].entries[0])}\n${rowFor(topics[1], topics[1].entries[0])}`);
        assert.match(verify(doubled, topics).join('\n'), /2 rows/);
      });
      test('a topic file exists with no heading in the index', () => {
        const more = [...topics, topic('ci.md', 'CI', ['A job times out'])];
        assert.match(verify(index(topics), more).join('\n'), /missing topic heading/);
      });
      test('a topic heading is duplicated', () => {
        const doubled = index(topics).replace(headingFor(topics[0]), `${headingFor(topics[0])}\n\n${headingFor(topics[0])}`);
        assert.match(verify(doubled, topics).join('\n'), /appears 2 times/);
      });
      test('an unresolved conflict marker is left inside the block', () => {
        const conflicted = index(topics).replace(rowFor(topics[1], topics[1].entries[0]), `<<<<<<< HEAD\n${rowFor(topics[1], topics[1].entries[0])}\n>>>>>>> main`);
        assert.match(verify(conflicted, topics).join('\n'), /unrecognized line inside the index block/);
      });
      test('the closing line was deleted', () => {
        const noFooter = index(topics).split('\n').filter((l) => !l.startsWith('_Generated by')).join('\n');
        assert.match(verify(noFooter, topics).join('\n'), /closing line is missing/);
      });
      test('the closing line is duplicated', () => {
        assert.match(verify(index(topics).replace(FOOTER, `${FOOTER}\n${FOOTER}`), topics).join('\n'), /closing line appears 2 times/);
      });
      test('the block lost its blank lines', () => {
        const squashed = index(topics).replace(/<!-- gotchas-index:begin -->[\s\S]*?<!-- gotchas-index:end -->/,
          (m) => m.split('\n').filter((l) => l.trim()).join('\n'));
        assert.match(verify(squashed, topics).join('\n'), /no blank lines/);
      });
      test('a SECOND marker pair was appended — splice would never rewrite it', () => {
        const extra = `${index(topics)}\n<!-- gotchas-index:begin -->\n- [ghost](gotchas/ghost.md#ghost)\n<!-- gotchas-index:end -->\n`;
        assert.match(verify(extra, topics).join('\n'), /second gotchas-index marker pair/);
      });
      // A gate that cannot fail is also a claim.
      test('fails loud on an empty block rather than reporting clean', () => {
        const problems = verify(index([]), topics);
        assert.ok(problems.length, 'an empty index against a non-empty corpus must not pass');
        assert.match(problems[0], /no entries at all/);
      });
    });

    test('a CRLF-saved index verifies the same as an LF one', () => {
      assert.deepEqual(verify(index(topics).replace(/\n/g, '\r\n'), topics), []);
    });
    test('markers missing entirely still throws', () => {
      assert.throws(() => verify('# no markers here\n', topics), /markers/);
    });
  });

  describe('splice', () => {
    test('replaces only the marked region', () => {
      const before = 'pre\n<!-- gotchas-index:begin -->\nOLD\n<!-- gotchas-index:end -->\npost\n';
      assert.equal(
        splice(before, '<!-- gotchas-index:begin -->\nNEW\n<!-- gotchas-index:end -->'),
        'pre\n<!-- gotchas-index:begin -->\nNEW\n<!-- gotchas-index:end -->\npost\n',
      );
    });
    test('throws when markers are missing', () => {
      assert.throws(() => splice('no markers here', 'x'), /markers/);
    });
  });

  describe('the live engineering/gotchas/ folder', () => {
    const { topics, errors } = collect();
    test('every topic file is well-formed (collect() is clean)', () => {
      assert.deepEqual(errors, [], `malformed topic files:\n${errors.join('\n')}`);
      assert.ok(topics.length >= 5, `expected the split corpus, got ${topics.length} topics`);
    });
    test('every entry has a unique anchor within its file', () => {
      for (const t of topics) {
        const anchors = [...t.anchors.values()];
        assert.equal(new Set(anchors).size, anchors.length, `${t.file}: two entries share an anchor`);
      }
    });
    // The index is the ONLY route to these files now, so every row must resolve. This
    // re-derives each anchor from the topic file INDEPENDENTLY of the row-building path
    // (re-parse the file, re-slug its headings) — the previous version of this test
    // compared collect() against itself and could not fail.
    test('every committed row resolves to a real heading in a real file', () => {
      const fs2 = require('node:fs');
      const path2 = require('node:path');
      const root = path2.join(__dirname, '../../../engineering');
      const index = fs2.readFileSync(path2.join(root, 'gotchas.md'), 'utf8');
      const rows = [...index.matchAll(/^- \[(.+)\]\(gotchas\/([^)#]+)#([^)]+)\)$/gm)];
      assert.ok(rows.length >= 100, `expected the full index, parsed ${rows.length} rows`);
      const anchorsOf = new Map();
      for (const [, , file] of rows) {
        if (anchorsOf.has(file)) continue;
        const full = path2.join(root, 'gotchas', file);
        assert.ok(fs2.existsSync(full), `${file}: row points at a file that does not exist`);
        const Slugger = require('github-slugger').default ?? require('github-slugger');
        const slugger = new Slugger();
        const set = new Set();
        for (const h of parseHeadings(fs2.readFileSync(full, 'utf8'))) set.add(slugger.slug(h.text));
        anchorsOf.set(file, set);
      }
      for (const [, label, file, anchor] of rows) {
        assert.ok(anchorsOf.get(file).has(anchor), `${file}#${anchor} does not exist (row: ${label.slice(0, 60)})`);
      }
    });
  });
  // Heading extraction has to agree with a REAL parser about what a heading is. Every
  // case here is one an adversarial pass broke in the line-scanning version that shipped
  // first — and each one failed SILENTLY, with `--check` exiting 0.
  describe('parseHeadings — agreeing with the renderer', () => {
    const h2s = (text) => parseHeadings(text).filter((h) => h.level === 2).map((h) => h.text);

    // The break that mattered: an orphaned closing fence — exactly what a gotcha about a
    // swallowed fence quotes — flipped a parity toggle and deleted the REST OF THE FILE
    // from the index.
    test('an unbalanced fence inside an example does not swallow later entries', () => {
      const doc = ['# T', '', '## A', '', '````md', '```mermaid', 'graph TD; A-->B', '````', '', '## B', '', '## C'].join('\n');
      assert.deepEqual(h2s(doc), ['A', 'B', 'C']);
    });
    test('a heading inside a fence is not an entry', () => {
      assert.deepEqual(h2s(['# T', '', '## Real', '', '```sh', '## not a heading', '```'].join('\n')), ['Real']);
    });
    test('a heading inside an HTML comment is not an entry', () => {
      assert.deepEqual(h2s(['# T', '', '## Real', '', '<!--', '## commented out', '-->'].join('\n')), ['Real']);
    });
    test('a setext heading IS an entry — the renderer says so', () => {
      assert.deepEqual(h2s(['# T', '', 'Underlined heading', '---', '', 'body', '', '## Atx'].join('\n')), ['Underlined heading', 'Atx']);
    });
    test('a closing sequence is not part of the text', () => {
      assert.deepEqual(h2s(['# T', '', '## Closing sequence ##'].join('\n')), ['Closing sequence']);
    });
    test('text is the RENDERED text — code, emphasis and link markup are consumed', () => {
      const [h] = parseHeadings('## A `code` and **bold** and [a link](x.md)\n').filter((x) => x.level === 2);
      assert.equal(h.text, 'A code and bold and a link', 'what GitHub slugs');
      assert.equal(h.raw, 'A `code` and **bold** and [a link](x.md)', 'what the row label keeps');
    });
  });

  // Every guard below was unreachable from the live corpus, so each is exercised on a
  // fixture directory. `collect(dir)` exists for exactly this reason.
  describe('collect — on fixture corpora', () => {
    const os = require('node:os');
    const fsx = require('node:fs');
    const pathx = require('node:path');
    const withCorpus = (files, fn) => {
      const dir = fsx.mkdtempSync(pathx.join(os.tmpdir(), 'gotchas-fixture-'));
      try {
        for (const [name, body] of Object.entries(files)) fsx.writeFileSync(pathx.join(dir, name), body);
        return fn(dir);
      } finally {
        fsx.rmSync(dir, { recursive: true, force: true });
      }
    };

    test('an entry after an unbalanced fence still reaches the index', () => {
      const { topics, errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '## A', '', '````md', '```x', '````', '', '## B'].join('\n') },
        (d) => collect(d),
      );
      assert.deepEqual(errors, []);
      assert.deepEqual(topics[0].entries, ['A', 'B']);
    });

    test('two headings that slug alike are REJECTED, so no anchor is positional', () => {
      // GitHub would mint `dup` and `dup-1` in document order — correct, but inserting an
      // entry above one silently re-anchors the other and rots every deep link to it.
      const { errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '## Dup!', '', 'body', '', '## Dup', '', 'body'].join('\n') },
        (d) => collect(d),
      );
      assert.equal(errors.length, 1, errors.join('\n'));
      assert.match(errors[0], /slug to the same anchor/);
    });

    test('a body heading that collides with an entry is caught too', () => {
      const { errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '### Shared name', '', '## Shared name'].join('\n') },
        (d) => collect(d),
      );
      assert.match(errors.join('\n'), /slug to the same anchor/);
    });

    test('an entry heading quoting an index marker is rejected, not spliced', () => {
      const { errors } = withCorpus(
        { 'f.md': ['# Gotchas — F', '', '## A heading quoting <!-- gotchas-index:end --> in prose'].join('\n') },
        (d) => collect(d),
      );
      assert.match(errors.join('\n'), /contains an index marker/);
    });

    test('a folder README is skipped, not treated as a malformed topic', () => {
      const { topics, errors } = withCorpus(
        { 'README.md': '# What this folder is\n\nProse, no entries.\n', 'f.md': '# Gotchas — F\n\n## A\n' },
        (d) => collect(d),
      );
      assert.deepEqual(errors, [], 'a README must not hard-fail the build');
      assert.deepEqual(topics.map((t) => t.file), ['f.md']);
    });

    test('a topic file with no entries is still an error', () => {
      const { errors } = withCorpus({ 'f.md': '# Gotchas — F\n\nprose only\n' }, (d) => collect(d));
      assert.match(errors.join('\n'), /no .* entries/);
    });

    test('the h1 is taken from the document, not from a fenced comment', () => {
      const { topics } = withCorpus(
        { 'f.md': ['```sh', '# not the title', '```', '', '# Gotchas — Real Title', '', '## A'].join('\n') },
        (d) => collect(d),
      );
      assert.equal(topics[0].title, 'Real Title');
    });
  });

  // An entry written INTO the generated index is invisible to the generator and is
  // destroyed on the next run. Two docs used to instruct exactly that.
  describe('verify — an entry authored into the generated index', () => {
    const topics = [topic('charts.md', 'Charts', ['Pie wedges misalign'])];
    test('fails, naming where the entry belongs', () => {
      const withStray = `# Gotchas\n\n## Symptom index\n\n${render(topics)}\n\n## A gotcha someone appended here\n\n- **Symptom:** it vanishes.\n`;
      const problems = verify(withStray, topics);
      assert.equal(problems.length, 1, problems.join('\n'));
      assert.match(problems[0], /written into engineering\/gotchas\.md itself/);
    });
    test('the file\'s own headings are not mistaken for entries', () => {
      assert.deepEqual(verify(`# Gotchas\n\n## How to use this file\n\nprose\n\n## Symptom index\n\n${render(topics)}\n`, topics), []);
    });
    test('a heading inside a fenced example in the prose is not an entry', () => {
      const doc = `# Gotchas\n\n## How to use this file\n\n\`\`\`md\n## an example heading\n\`\`\`\n\n## Symptom index\n\n${render(topics)}\n`;
      assert.deepEqual(verify(doc, topics), []);
    });
  });

});
