// Generated by tools/build-segno-grammar.js from notation-grammar.ts with Segno's code generator
// (codegen.ts). DO NOT EDIT — change the grammar and run `npm run segno-lib:build`.

const T0 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1]);
const T1 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T2 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T3 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);
const T4 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);

export interface GenError { at: number; expected: string; found: string | null }
export interface GenTree { buf: Int32Array; top: number; kinds: readonly string[] }

const KINDS: readonly string[] = ["record","list","quoted","bare","word"];
let s = '';
let n = 0;
let i = 0;
let depth = 0;
let err: GenError | null = null;
let buf = new Int32Array(256);
let top = 0;

function grow(): void {
  const next = new Int32Array(buf.length * 2);
  next.set(buf);
  buf = next;
}

function fail(expected: string): false {
  if (!err) err = { at: i, expected, found: i < n ? s[i] : null };
  return false;
}

function r_span(): boolean {
  { let c0 = s.charCodeAt(i); while ((c0 === 9 || c0 === 32)) { i++; c0 = s.charCodeAt(i); } }
  if (depth >= 64) return fail("at most 64 levels of nesting");
  depth++;
  if (!r_item()) return false;
  depth--;
  return true;
}

function r_value(): boolean {
  {
    const c2 = s.charCodeAt(i);
    if ((c2 === 123)) {
      {
        const c3 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c3] = 0;
        buf[c3 + 1] = i;
        if (s.charCodeAt(i) !== 123) return fail("\"{\"");
        i++;
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_item()) return false;
        depth--;
        for (let c4 = s.charCodeAt(i); (c4 === 44); c4 = s.charCodeAt(i)) {
          if (s.charCodeAt(i) !== 44) return fail("\",\"");
          i++;
          { let c5 = s.charCodeAt(i); while ((c5 === 9 || c5 === 32)) { i++; c5 = s.charCodeAt(i); } }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_item()) return false;
          depth--;
        }
        if (s.charCodeAt(i) !== 125) return fail("\"}\"");
        i++;
        buf[c3 + 2] = i;
        buf[c3 + 3] = top;
      }
      { let c7 = s.charCodeAt(i); while ((c7 === 9 || c7 === 32)) { i++; c7 = s.charCodeAt(i); } }
    }
    else if ((c2 === 91)) {
      {
        const c9 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c9] = 1;
        buf[c9 + 1] = i;
        if (s.charCodeAt(i) !== 91) return fail("\"[\"");
        i++;
        { let c10 = s.charCodeAt(i); while ((c10 === 9 || c10 === 32)) { i++; c10 = s.charCodeAt(i); } }
        { const c12 = s.charCodeAt(i); if (((c12 < 128 && T0[c12] === 1) || (c12 >= 128 && c12 <= 65535))) {
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_item()) return false;
          depth--;
        } }
        for (let c13 = s.charCodeAt(i); (c13 === 44); c13 = s.charCodeAt(i)) {
          if (s.charCodeAt(i) !== 44) return fail("\",\"");
          i++;
          { let c14 = s.charCodeAt(i); while ((c14 === 9 || c14 === 32)) { i++; c14 = s.charCodeAt(i); } }
          { const c16 = s.charCodeAt(i); if (((c16 < 128 && T0[c16] === 1) || (c16 >= 128 && c16 <= 65535))) {
            if (depth >= 64) return fail("at most 64 levels of nesting");
            depth++;
            if (!r_item()) return false;
            depth--;
          } }
        }
        if (s.charCodeAt(i) !== 93) return fail("\"]\"");
        i++;
        buf[c9 + 2] = i;
        buf[c9 + 3] = top;
      }
      { let c17 = s.charCodeAt(i); while ((c17 === 9 || c17 === 32)) { i++; c17 = s.charCodeAt(i); } }
    }
    else if ((c2 === 34)) {
      {
        const c19 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c19] = 2;
        buf[c19 + 1] = i;
        if (s.charCodeAt(i) !== 34) return fail("\"\\\"\"");
        i++;
        for (let c20 = s.charCodeAt(i); ((c20 < 128 && T2[c20] === 1) || (c20 >= 128 && c20 <= 65535)); c20 = s.charCodeAt(i)) {
          {
            const c21 = s.charCodeAt(i);
            if ((c21 === 92)) {
              if (s.charCodeAt(i) !== 92) return fail("\"\\\\\"");
              i++;
              { const c22 = s.charCodeAt(i); if (!(c22 >= 0)) return fail("any character"); i++; }
            }
            else if (((c21 < 128 && T1[c21] === 1) || (c21 >= 128 && c21 <= 65535))) {
              { const c23 = s.charCodeAt(i); if (!((c23 < 128 && T1[c23] === 1) || (c23 >= 128 && c23 <= 65535))) return fail("text"); i++; }
            }
            else return fail("\"\\\\\" or text");
          }
        }
        if (s.charCodeAt(i) !== 34) return fail("\"\\\"\"");
        i++;
        buf[c19 + 2] = i;
        buf[c19 + 3] = top;
      }
      { let c24 = s.charCodeAt(i); while ((c24 === 9 || c24 === 32)) { i++; c24 = s.charCodeAt(i); } }
    }
    else if (((c2 < 128 && T3[c2] === 1) || (c2 >= 128 && c2 <= 65535))) {
      {
        const c26 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c26] = 3;
        buf[c26 + 1] = i;
        { const c27 = s.charCodeAt(i); if (!((c27 < 128 && T3[c27] === 1) || (c27 >= 128 && c27 <= 65535))) return fail("a value"); i++; }
        { let c28 = s.charCodeAt(i); while (((c28 < 128 && T4[c28] === 1) || (c28 >= 128 && c28 <= 65535))) { i++; c28 = s.charCodeAt(i); } }
        buf[c26 + 2] = i;
        buf[c26 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_item(): boolean {
  {
    const c30 = s.charCodeAt(i);
    if ((c30 === 123)) {
      {
        const c31 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c31] = 0;
        buf[c31 + 1] = i;
        if (s.charCodeAt(i) !== 123) return fail("\"{\"");
        i++;
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_item()) return false;
        depth--;
        for (let c32 = s.charCodeAt(i); (c32 === 44); c32 = s.charCodeAt(i)) {
          if (s.charCodeAt(i) !== 44) return fail("\",\"");
          i++;
          { let c33 = s.charCodeAt(i); while ((c33 === 9 || c33 === 32)) { i++; c33 = s.charCodeAt(i); } }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_item()) return false;
          depth--;
        }
        if (s.charCodeAt(i) !== 125) return fail("\"}\"");
        i++;
        buf[c31 + 2] = i;
        buf[c31 + 3] = top;
      }
      { let c35 = s.charCodeAt(i); while ((c35 === 9 || c35 === 32)) { i++; c35 = s.charCodeAt(i); } }
    }
    else if ((c30 === 91)) {
      {
        const c37 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c37] = 1;
        buf[c37 + 1] = i;
        if (s.charCodeAt(i) !== 91) return fail("\"[\"");
        i++;
        { let c38 = s.charCodeAt(i); while ((c38 === 9 || c38 === 32)) { i++; c38 = s.charCodeAt(i); } }
        { const c40 = s.charCodeAt(i); if (((c40 < 128 && T0[c40] === 1) || (c40 >= 128 && c40 <= 65535))) {
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_item()) return false;
          depth--;
        } }
        for (let c41 = s.charCodeAt(i); (c41 === 44); c41 = s.charCodeAt(i)) {
          if (s.charCodeAt(i) !== 44) return fail("\",\"");
          i++;
          { let c42 = s.charCodeAt(i); while ((c42 === 9 || c42 === 32)) { i++; c42 = s.charCodeAt(i); } }
          { const c44 = s.charCodeAt(i); if (((c44 < 128 && T0[c44] === 1) || (c44 >= 128 && c44 <= 65535))) {
            if (depth >= 64) return fail("at most 64 levels of nesting");
            depth++;
            if (!r_item()) return false;
            depth--;
          } }
        }
        if (s.charCodeAt(i) !== 93) return fail("\"]\"");
        i++;
        buf[c37 + 2] = i;
        buf[c37 + 3] = top;
      }
      { let c45 = s.charCodeAt(i); while ((c45 === 9 || c45 === 32)) { i++; c45 = s.charCodeAt(i); } }
    }
    else if ((c30 === 34)) {
      {
        const c47 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c47] = 2;
        buf[c47 + 1] = i;
        if (s.charCodeAt(i) !== 34) return fail("\"\\\"\"");
        i++;
        for (let c48 = s.charCodeAt(i); ((c48 < 128 && T2[c48] === 1) || (c48 >= 128 && c48 <= 65535)); c48 = s.charCodeAt(i)) {
          {
            const c49 = s.charCodeAt(i);
            if ((c49 === 92)) {
              if (s.charCodeAt(i) !== 92) return fail("\"\\\\\"");
              i++;
              { const c50 = s.charCodeAt(i); if (!(c50 >= 0)) return fail("any character"); i++; }
            }
            else if (((c49 < 128 && T1[c49] === 1) || (c49 >= 128 && c49 <= 65535))) {
              { const c51 = s.charCodeAt(i); if (!((c51 < 128 && T1[c51] === 1) || (c51 >= 128 && c51 <= 65535))) return fail("text"); i++; }
            }
            else return fail("\"\\\\\" or text");
          }
        }
        if (s.charCodeAt(i) !== 34) return fail("\"\\\"\"");
        i++;
        buf[c47 + 2] = i;
        buf[c47 + 3] = top;
      }
      { let c52 = s.charCodeAt(i); while ((c52 === 9 || c52 === 32)) { i++; c52 = s.charCodeAt(i); } }
    }
    else if (((c30 < 128 && T3[c30] === 1) || (c30 >= 128 && c30 <= 65535))) {
      {
        const c54 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c54] = 4;
        buf[c54 + 1] = i;
        {
          const c55 = top;
          if (top + 4 > buf.length) grow();
          top += 4;
          buf[c55] = 3;
          buf[c55 + 1] = i;
          { const c56 = s.charCodeAt(i); if (!((c56 < 128 && T3[c56] === 1) || (c56 >= 128 && c56 <= 65535))) return fail("a value"); i++; }
          { let c57 = s.charCodeAt(i); while (((c57 < 128 && T4[c57] === 1) || (c57 >= 128 && c57 <= 65535))) { i++; c57 = s.charCodeAt(i); } }
          buf[c55 + 2] = i;
          buf[c55 + 3] = top;
        }
        { const c59 = s.charCodeAt(i); if ((c59 === 61)) {
          if (s.charCodeAt(i) !== 61) return fail("\"=\"");
          i++;
          { let c60 = s.charCodeAt(i); while ((c60 === 9 || c60 === 32)) { i++; c60 = s.charCodeAt(i); } }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_value()) return false;
          depth--;
        } }
        buf[c54 + 2] = i;
        buf[c54 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

const RULES: Record<string, () => boolean> = { "span": r_span, "value": r_value, "item": r_item };

/**
 * Parse `input` against rule `rule` (default "span"). Never throws on input. The tree
 * is a flat buffer that the NEXT call overwrites (flat.ts) — read it first.
 */
export function parse(input: string, rule = "span"): { ok: true; tree: GenTree } | { ok: false; error: GenError } {
  const start = Object.hasOwn(RULES, rule) ? RULES[rule] : undefined;
  if (!start) throw new Error('segno: no rule "' + rule + '"');
  s = input;
  n = s.length;
  i = 0;
  depth = 0;
  err = null;
  top = 0;
  const ok = start();
  if (ok && i < n) fail('end of input');
  const e = err as GenError | null;
  if (!ok || e) return { ok: false, error: e ?? { at: i, expected: 'a valid input', found: null } };
  return { ok: true, tree: { buf, top, kinds: KINDS } };
}
