// Generated by tools/build-segno-grammar.js from notation-grammar.ts with Segno's code generator
// (codegen.ts). DO NOT EDIT — change the grammar and run `npm run segno-lib:build`.

const T0 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1]);
const T1 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1]);
const T2 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);
const T3 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1]);
const T4 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T5 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T6 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);
// biome-ignore lint/suspicious/noControlCharactersInRegex: a generated character class; control characters are input like any other
const R0 = /[\u0000-\u0008\u000a-\u001f\u0021-\u009f\u00a1-\uffff]/g;
const R1 = /[\u0022\u002c\u003d\u005b\u005d\u007b-\u007d]/g;

export interface GenError { at: number; expected: string; found: string | null; code?: 'stack' }
export interface GenTree { buf: Int32Array; top: number; kinds: readonly string[] }

const KINDS: readonly string[] = ["tagged","word","bare","record","list","quoted"];
let s = '';
let n = 0;
let i = 0;
let depth = 0;
let err: GenError | null = null;
let buf = new Int32Array(256);
let top = 0;

function grow(): void {
  const next = new Int32Array(buf.length * 2);
  next.set(buf);
  buf = next;
}

function fail(expected: string): false {
  if (!err) err = { at: i, expected, found: i < n ? s[i] : null };
  return false;
}

function r_span(): boolean {
  {
    let c8 = i; const c9 = n; const c10 = s; const c11 = c8 + 16 < c9 ? c8 + 16 : c9;
    while (c8 < c11) { const c6 = c10.charCodeAt(c8); if (!(c6 === 9 || c6 === 32 || c6 === 160)) break; c8++; }
    if (c8 === c11 && c8 < c9) { if (c9 !== c10.length) { while (c8 < c9) { const c6 = c10.charCodeAt(c8); if (!(c6 === 9 || c6 === 32 || c6 === 160)) break; c8++; } } else { R0.lastIndex = c8; c8 = R0.test(c10) ? R0.lastIndex - 1 : c9; } }
    i = c8;
  }
  {
    const c12 = (i < n ? s.charCodeAt(i) : -1);
    if ((c12 === 94 || c12 === 126)) {
      {
        const c13 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c13] = 0;
        buf[c13 + 1] = i;
        i++;
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_record()) return false;
        depth--;
        {
          let c16 = i; const c17 = n; const c18 = s; const c19 = c16 + 16 < c17 ? c16 + 16 : c17;
          while (c16 < c19) { const c14 = c18.charCodeAt(c16); if (!(c14 === 9 || c14 === 32 || c14 === 160)) break; c16++; }
          if (c16 === c19 && c16 < c17) { if (c17 !== c18.length) { while (c16 < c17) { const c14 = c18.charCodeAt(c16); if (!(c14 === 9 || c14 === 32 || c14 === 160)) break; c16++; } } else { R0.lastIndex = c16; c16 = R0.test(c18) ? R0.lastIndex - 1 : c17; } }
          i = c16;
        }
        buf[c13 + 2] = i;
        buf[c13 + 3] = top;
      }
    }
    else if (((c12 >= 0 && c12 < 128 && T0[c12] === 1) || (c12 >= 128 && c12 <= 159) || (c12 >= 161 && c12 <= 65535))) {
      if (!r_top()) return false;
    }
    else return fail("a tag, \"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_top(): boolean {
  {
    const c20 = (i < n ? s.charCodeAt(i) : -1);
    if ((c20 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      {
        let c23 = i; const c24 = n; const c25 = s; const c26 = c23 + 16 < c24 ? c23 + 16 : c24;
        while (c23 < c26) { const c21 = c25.charCodeAt(c23); if (!(c21 === 9 || c21 === 32 || c21 === 160)) break; c23++; }
        if (c23 === c26 && c23 < c24) { if (c24 !== c25.length) { while (c23 < c24) { const c21 = c25.charCodeAt(c23); if (!(c21 === 9 || c21 === 32 || c21 === 160)) break; c23++; } } else { R0.lastIndex = c23; c23 = R0.test(c25) ? R0.lastIndex - 1 : c24; } }
        i = c23;
      }
    }
    else if ((c20 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      {
        let c29 = i; const c30 = n; const c31 = s; const c32 = c29 + 16 < c30 ? c29 + 16 : c30;
        while (c29 < c32) { const c27 = c31.charCodeAt(c29); if (!(c27 === 9 || c27 === 32 || c27 === 160)) break; c29++; }
        if (c29 === c32 && c29 < c30) { if (c30 !== c31.length) { while (c29 < c30) { const c27 = c31.charCodeAt(c29); if (!(c27 === 9 || c27 === 32 || c27 === 160)) break; c29++; } } else { R0.lastIndex = c29; c29 = R0.test(c31) ? R0.lastIndex - 1 : c30; } }
        i = c29;
      }
    }
    else if ((c20 === 34)) {
      if (!r_quoted()) return false;
      {
        let c35 = i; const c36 = n; const c37 = s; const c38 = c35 + 16 < c36 ? c35 + 16 : c36;
        while (c35 < c38) { const c33 = c37.charCodeAt(c35); if (!(c33 === 9 || c33 === 32 || c33 === 160)) break; c35++; }
        if (c35 === c38 && c35 < c36) { if (c36 !== c37.length) { while (c35 < c36) { const c33 = c37.charCodeAt(c35); if (!(c33 === 9 || c33 === 32 || c33 === 160)) break; c35++; } } else { R0.lastIndex = c35; c35 = R0.test(c37) ? R0.lastIndex - 1 : c36; } }
        i = c35;
      }
    }
    else if (((c20 >= 0 && c20 < 128 && T1[c20] === 1) || (c20 >= 128 && c20 <= 159) || (c20 >= 161 && c20 <= 65535))) {
      {
        const c39 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c39] = 1;
        buf[c39 + 1] = i;
        {
          const c40 = top;
          if (top + 4 > buf.length) grow();
          top += 4;
          buf[c40] = 2;
          buf[c40 + 1] = i;
          i++;
          {
            let c43 = i; const c44 = n; const c45 = s; const c46 = c43 + 16 < c44 ? c43 + 16 : c44;
            while (c43 < c46) { const c41 = c45.charCodeAt(c43); if (!((c41 >= 0 && c41 < 128 && T2[c41] === 1) || (c41 >= 128 && c41 <= 65535))) break; c43++; }
            if (c43 === c46 && c43 < c44) { if (c44 !== c45.length) { while (c43 < c44) { const c41 = c45.charCodeAt(c43); if (!((c41 >= 0 && c41 < 128 && T2[c41] === 1) || (c41 >= 128 && c41 <= 65535))) break; c43++; } } else { R1.lastIndex = c43; c43 = R1.test(c45) ? R1.lastIndex - 1 : c44; } }
            i = c43;
          }
          buf[c40 + 2] = i;
          buf[c40 + 3] = top;
        }
        { const c47 = (i < n ? s.charCodeAt(i) : -1); if ((c47 === 61)) {
          i++;
          {
            let c50 = i; const c51 = n; const c52 = s; const c53 = c50 + 16 < c51 ? c50 + 16 : c51;
            while (c50 < c53) { const c48 = c52.charCodeAt(c50); if (!(c48 === 9 || c48 === 32 || c48 === 160)) break; c50++; }
            if (c50 === c53 && c50 < c51) { if (c51 !== c52.length) { while (c50 < c51) { const c48 = c52.charCodeAt(c50); if (!(c48 === 9 || c48 === 32 || c48 === 160)) break; c50++; } } else { R0.lastIndex = c50; c50 = R0.test(c52) ? R0.lastIndex - 1 : c51; } }
            i = c50;
          }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_value()) return false;
          depth--;
        } }
        buf[c39 + 2] = i;
        buf[c39 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_record(): boolean {
  {
    const c54 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c54] = 3;
    buf[c54 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 123) return fail("\"{\"");
    i++;
    if (depth >= 64) return fail("at most 64 levels of nesting");
    depth++;
    if (!r_item()) return false;
    depth--;
    for (let c55 = (i < n ? s.charCodeAt(i) : -1); (c55 === 44); c55 = (i < n ? s.charCodeAt(i) : -1)) {
      i++;
      {
        let c58 = i; const c59 = n; const c60 = s; const c61 = c58 + 16 < c59 ? c58 + 16 : c59;
        while (c58 < c61) { const c56 = c60.charCodeAt(c58); if (!(c56 === 9 || c56 === 32 || c56 === 160)) break; c58++; }
        if (c58 === c61 && c58 < c59) { if (c59 !== c60.length) { while (c58 < c59) { const c56 = c60.charCodeAt(c58); if (!(c56 === 9 || c56 === 32 || c56 === 160)) break; c58++; } } else { R0.lastIndex = c58; c58 = R0.test(c60) ? R0.lastIndex - 1 : c59; } }
        i = c58;
      }
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_item()) return false;
      depth--;
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 125) return fail("\"}\"");
    i++;
    buf[c54 + 2] = i;
    buf[c54 + 3] = top;
  }
  return true;
}

function r_list(): boolean {
  {
    const c62 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c62] = 4;
    buf[c62 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 91) return fail("\"[\"");
    i++;
    {
      let c65 = i; const c66 = n; const c67 = s; const c68 = c65 + 16 < c66 ? c65 + 16 : c66;
      while (c65 < c68) { const c63 = c67.charCodeAt(c65); if (!(c63 === 9 || c63 === 32 || c63 === 160)) break; c65++; }
      if (c65 === c68 && c65 < c66) { if (c66 !== c67.length) { while (c65 < c66) { const c63 = c67.charCodeAt(c65); if (!(c63 === 9 || c63 === 32 || c63 === 160)) break; c65++; } } else { R0.lastIndex = c65; c65 = R0.test(c67) ? R0.lastIndex - 1 : c66; } }
      i = c65;
    }
    { const c69 = (i < n ? s.charCodeAt(i) : -1); if (((c69 >= 0 && c69 < 128 && T3[c69] === 1) || (c69 >= 128 && c69 <= 159) || (c69 >= 161 && c69 <= 65535))) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_item()) return false;
      depth--;
    } }
    for (let c70 = (i < n ? s.charCodeAt(i) : -1); (c70 === 44); c70 = (i < n ? s.charCodeAt(i) : -1)) {
      i++;
      {
        let c73 = i; const c74 = n; const c75 = s; const c76 = c73 + 16 < c74 ? c73 + 16 : c74;
        while (c73 < c76) { const c71 = c75.charCodeAt(c73); if (!(c71 === 9 || c71 === 32 || c71 === 160)) break; c73++; }
        if (c73 === c76 && c73 < c74) { if (c74 !== c75.length) { while (c73 < c74) { const c71 = c75.charCodeAt(c73); if (!(c71 === 9 || c71 === 32 || c71 === 160)) break; c73++; } } else { R0.lastIndex = c73; c73 = R0.test(c75) ? R0.lastIndex - 1 : c74; } }
        i = c73;
      }
      { const c77 = (i < n ? s.charCodeAt(i) : -1); if (((c77 >= 0 && c77 < 128 && T3[c77] === 1) || (c77 >= 128 && c77 <= 159) || (c77 >= 161 && c77 <= 65535))) {
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_item()) return false;
        depth--;
      } }
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 93) return fail("\"]\"");
    i++;
    buf[c62 + 2] = i;
    buf[c62 + 3] = top;
  }
  return true;
}

function r_quoted(): boolean {
  {
    const c78 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c78] = 5;
    buf[c78 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 34) return fail("\"\\\"\"");
    i++;
    for (let c79 = (i < n ? s.charCodeAt(i) : -1); ((c79 >= 0 && c79 < 128 && T5[c79] === 1) || (c79 >= 128 && c79 <= 65535)); c79 = (i < n ? s.charCodeAt(i) : -1)) {
      {
        const c80 = c79;
        if ((c80 === 92)) {
          i++;
          { const c81 = (i < n ? s.charCodeAt(i) : -1); if (!(c81 >= 0)) return fail("any character"); i++; }
        }
        else if (((c80 >= 0 && c80 < 128 && T4[c80] === 1) || (c80 >= 128 && c80 <= 65535))) {
          i++;
        }
        else return fail("\"\\\\\" or text");
      }
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 34) return fail("\"\\\"\"");
    i++;
    buf[c78 + 2] = i;
    buf[c78 + 3] = top;
  }
  return true;
}

function r_value(): boolean {
  {
    const c82 = (i < n ? s.charCodeAt(i) : -1);
    if ((c82 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      {
        let c85 = i; const c86 = n; const c87 = s; const c88 = c85 + 16 < c86 ? c85 + 16 : c86;
        while (c85 < c88) { const c83 = c87.charCodeAt(c85); if (!(c83 === 9 || c83 === 32 || c83 === 160)) break; c85++; }
        if (c85 === c88 && c85 < c86) { if (c86 !== c87.length) { while (c85 < c86) { const c83 = c87.charCodeAt(c85); if (!(c83 === 9 || c83 === 32 || c83 === 160)) break; c85++; } } else { R0.lastIndex = c85; c85 = R0.test(c87) ? R0.lastIndex - 1 : c86; } }
        i = c85;
      }
    }
    else if ((c82 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      {
        let c91 = i; const c92 = n; const c93 = s; const c94 = c91 + 16 < c92 ? c91 + 16 : c92;
        while (c91 < c94) { const c89 = c93.charCodeAt(c91); if (!(c89 === 9 || c89 === 32 || c89 === 160)) break; c91++; }
        if (c91 === c94 && c91 < c92) { if (c92 !== c93.length) { while (c91 < c92) { const c89 = c93.charCodeAt(c91); if (!(c89 === 9 || c89 === 32 || c89 === 160)) break; c91++; } } else { R0.lastIndex = c91; c91 = R0.test(c93) ? R0.lastIndex - 1 : c92; } }
        i = c91;
      }
    }
    else if ((c82 === 34)) {
      if (!r_quoted()) return false;
      {
        let c97 = i; const c98 = n; const c99 = s; const c100 = c97 + 16 < c98 ? c97 + 16 : c98;
        while (c97 < c100) { const c95 = c99.charCodeAt(c97); if (!(c95 === 9 || c95 === 32 || c95 === 160)) break; c97++; }
        if (c97 === c100 && c97 < c98) { if (c98 !== c99.length) { while (c97 < c98) { const c95 = c99.charCodeAt(c97); if (!(c95 === 9 || c95 === 32 || c95 === 160)) break; c97++; } } else { R0.lastIndex = c97; c97 = R0.test(c99) ? R0.lastIndex - 1 : c98; } }
        i = c97;
      }
    }
    else if (((c82 >= 0 && c82 < 128 && T6[c82] === 1) || (c82 >= 128 && c82 <= 159) || (c82 >= 161 && c82 <= 65535))) {
      if (!e_0()) return false;
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_item(): boolean {
  {
    const c109 = (i < n ? s.charCodeAt(i) : -1);
    if ((c109 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      {
        let c112 = i; const c113 = n; const c114 = s; const c115 = c112 + 16 < c113 ? c112 + 16 : c113;
        while (c112 < c115) { const c110 = c114.charCodeAt(c112); if (!(c110 === 9 || c110 === 32 || c110 === 160)) break; c112++; }
        if (c112 === c115 && c112 < c113) { if (c113 !== c114.length) { while (c112 < c113) { const c110 = c114.charCodeAt(c112); if (!(c110 === 9 || c110 === 32 || c110 === 160)) break; c112++; } } else { R0.lastIndex = c112; c112 = R0.test(c114) ? R0.lastIndex - 1 : c113; } }
        i = c112;
      }
    }
    else if ((c109 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      {
        let c118 = i; const c119 = n; const c120 = s; const c121 = c118 + 16 < c119 ? c118 + 16 : c119;
        while (c118 < c121) { const c116 = c120.charCodeAt(c118); if (!(c116 === 9 || c116 === 32 || c116 === 160)) break; c118++; }
        if (c118 === c121 && c118 < c119) { if (c119 !== c120.length) { while (c118 < c119) { const c116 = c120.charCodeAt(c118); if (!(c116 === 9 || c116 === 32 || c116 === 160)) break; c118++; } } else { R0.lastIndex = c118; c118 = R0.test(c120) ? R0.lastIndex - 1 : c119; } }
        i = c118;
      }
    }
    else if ((c109 === 34)) {
      if (!r_quoted()) return false;
      {
        let c124 = i; const c125 = n; const c126 = s; const c127 = c124 + 16 < c125 ? c124 + 16 : c125;
        while (c124 < c127) { const c122 = c126.charCodeAt(c124); if (!(c122 === 9 || c122 === 32 || c122 === 160)) break; c124++; }
        if (c124 === c127 && c124 < c125) { if (c125 !== c126.length) { while (c124 < c125) { const c122 = c126.charCodeAt(c124); if (!(c122 === 9 || c122 === 32 || c122 === 160)) break; c124++; } } else { R0.lastIndex = c124; c124 = R0.test(c126) ? R0.lastIndex - 1 : c125; } }
        i = c124;
      }
    }
    else if (((c109 >= 0 && c109 < 128 && T6[c109] === 1) || (c109 >= 128 && c109 <= 159) || (c109 >= 161 && c109 <= 65535))) {
      {
        const c128 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c128] = 1;
        buf[c128 + 1] = i;
        if (!e_0()) return false;
        { const c129 = (i < n ? s.charCodeAt(i) : -1); if ((c129 === 61)) {
          i++;
          {
            let c132 = i; const c133 = n; const c134 = s; const c135 = c132 + 16 < c133 ? c132 + 16 : c133;
            while (c132 < c135) { const c130 = c134.charCodeAt(c132); if (!(c130 === 9 || c130 === 32 || c130 === 160)) break; c132++; }
            if (c132 === c135 && c132 < c133) { if (c133 !== c134.length) { while (c132 < c133) { const c130 = c134.charCodeAt(c132); if (!(c130 === 9 || c130 === 32 || c130 === 160)) break; c132++; } } else { R0.lastIndex = c132; c132 = R0.test(c134) ? R0.lastIndex - 1 : c133; } }
            i = c132;
          }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_value()) return false;
          depth--;
        } }
        buf[c128 + 2] = i;
        buf[c128 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function e_0(): boolean {
  {
    const c101 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c101] = 2;
    buf[c101 + 1] = i;
    { const c102 = (i < n ? s.charCodeAt(i) : -1); if (!((c102 >= 0 && c102 < 128 && T6[c102] === 1) || (c102 >= 128 && c102 <= 159) || (c102 >= 161 && c102 <= 65535))) return fail("a value"); i++; }
    {
      let c105 = i; const c106 = n; const c107 = s; const c108 = c105 + 16 < c106 ? c105 + 16 : c106;
      while (c105 < c108) { const c103 = c107.charCodeAt(c105); if (!((c103 >= 0 && c103 < 128 && T2[c103] === 1) || (c103 >= 128 && c103 <= 65535))) break; c105++; }
      if (c105 === c108 && c105 < c106) { if (c106 !== c107.length) { while (c105 < c106) { const c103 = c107.charCodeAt(c105); if (!((c103 >= 0 && c103 < 128 && T2[c103] === 1) || (c103 >= 128 && c103 <= 65535))) break; c105++; } } else { R1.lastIndex = c105; c105 = R1.test(c107) ? R1.lastIndex - 1 : c106; } }
      i = c105;
    }
    buf[c101 + 2] = i;
    buf[c101 + 3] = top;
  }
  return true;
}

const RULES: Record<string, () => boolean> = { "span": r_span, "top": r_top, "record": r_record, "list": r_list, "quoted": r_quoted, "value": r_value, "item": r_item };

/**
 * Parse `input` against rule `rule` (default "span"). Never throws on input. The tree
 * is a flat buffer that the NEXT call overwrites (flat.ts) — read it first.
 */
export function parse(input: string, rule = "span"): { ok: true; tree: GenTree } | { ok: false; error: GenError } {
  const start = Object.hasOwn(RULES, rule) ? RULES[rule] : undefined;
  if (!start) throw new Error('segno: no rule "' + rule + '"');
  s = input;
  n = s.length;
  i = 0;
  depth = 0;
  err = null;
  top = 0;
  // A tree that outgrew the first buffer is let go here rather than kept for the page's life: one
  // hostile 3M-character flowchart row held 67 MB through every later parse (phase 3b's red team).
  if (buf.length > 65536) buf = new Int32Array(256);
  const ok = start();
  if (ok && i < n) fail('end of input');
  const e = err as GenError | null;
  if (!ok || e) return { ok: false, error: e ?? { at: i, expected: 'a valid input', found: null } };
  return { ok: true, tree: { buf, top, kinds: KINDS } };
}
