// Generated by tools/build-segno-grammar.js from notation-grammar.ts with Segno's code generator
// (codegen.ts). DO NOT EDIT — change the grammar and run `npm run segno-lib:build`.

const T0 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1]);
const T1 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1]);
const T2 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);
const T3 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1]);
const T4 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T5 = new Uint8Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]);
const T6 = new Uint8Array([1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1]);

export interface GenError { at: number; expected: string; found: string | null }
export interface GenTree { buf: Int32Array; top: number; kinds: readonly string[] }

const KINDS: readonly string[] = ["tagged","word","bare","record","list","quoted"];
let s = '';
let n = 0;
let i = 0;
let depth = 0;
let err: GenError | null = null;
let buf = new Int32Array(256);
let top = 0;

function grow(): void {
  const next = new Int32Array(buf.length * 2);
  next.set(buf);
  buf = next;
}

function fail(expected: string): false {
  if (!err) err = { at: i, expected, found: i < n ? s[i] : null };
  return false;
}

function r_span(): boolean {
  { let c0 = (i < n ? s.charCodeAt(i) : -1); while ((c0 === 9 || c0 === 32 || c0 === 160)) { i++; c0 = (i < n ? s.charCodeAt(i) : -1); } }
  {
    const c2 = (i < n ? s.charCodeAt(i) : -1);
    if ((c2 === 94 || c2 === 126)) {
      {
        const c3 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c3] = 0;
        buf[c3 + 1] = i;
        { const c4 = (i < n ? s.charCodeAt(i) : -1); if (!(c4 === 94 || c4 === 126)) return fail("a tag"); i++; }
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_record()) return false;
        depth--;
        { let c5 = (i < n ? s.charCodeAt(i) : -1); while ((c5 === 9 || c5 === 32 || c5 === 160)) { i++; c5 = (i < n ? s.charCodeAt(i) : -1); } }
        buf[c3 + 2] = i;
        buf[c3 + 3] = top;
      }
    }
    else if (((c2 >= 0 && c2 < 128 && T0[c2] === 1) || (c2 >= 128 && c2 <= 159) || (c2 >= 161 && c2 <= 65535))) {
      if (!r_top()) return false;
    }
    else return fail("a tag, \"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_top(): boolean {
  {
    const c7 = (i < n ? s.charCodeAt(i) : -1);
    if ((c7 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      { let c8 = (i < n ? s.charCodeAt(i) : -1); while ((c8 === 9 || c8 === 32 || c8 === 160)) { i++; c8 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c7 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      { let c10 = (i < n ? s.charCodeAt(i) : -1); while ((c10 === 9 || c10 === 32 || c10 === 160)) { i++; c10 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c7 === 34)) {
      if (!r_quoted()) return false;
      { let c12 = (i < n ? s.charCodeAt(i) : -1); while ((c12 === 9 || c12 === 32 || c12 === 160)) { i++; c12 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if (((c7 >= 0 && c7 < 128 && T1[c7] === 1) || (c7 >= 128 && c7 <= 159) || (c7 >= 161 && c7 <= 65535))) {
      {
        const c14 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c14] = 1;
        buf[c14 + 1] = i;
        {
          const c15 = top;
          if (top + 4 > buf.length) grow();
          top += 4;
          buf[c15] = 2;
          buf[c15 + 1] = i;
          { const c16 = (i < n ? s.charCodeAt(i) : -1); if (!((c16 >= 0 && c16 < 128 && T1[c16] === 1) || (c16 >= 128 && c16 <= 159) || (c16 >= 161 && c16 <= 65535))) return fail("a value"); i++; }
          { let c17 = (i < n ? s.charCodeAt(i) : -1); while (((c17 >= 0 && c17 < 128 && T2[c17] === 1) || (c17 >= 128 && c17 <= 65535))) { i++; c17 = (i < n ? s.charCodeAt(i) : -1); } }
          buf[c15 + 2] = i;
          buf[c15 + 3] = top;
        }
        { const c19 = (i < n ? s.charCodeAt(i) : -1); if ((c19 === 61)) {
          if ((i < n ? s.charCodeAt(i) : -1) !== 61) return fail("\"=\"");
          i++;
          { let c20 = (i < n ? s.charCodeAt(i) : -1); while ((c20 === 9 || c20 === 32 || c20 === 160)) { i++; c20 = (i < n ? s.charCodeAt(i) : -1); } }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_value()) return false;
          depth--;
        } }
        buf[c14 + 2] = i;
        buf[c14 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_record(): boolean {
  {
    const c22 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c22] = 3;
    buf[c22 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 123) return fail("\"{\"");
    i++;
    if (depth >= 64) return fail("at most 64 levels of nesting");
    depth++;
    if (!r_item()) return false;
    depth--;
    for (let c23 = (i < n ? s.charCodeAt(i) : -1); (c23 === 44); c23 = (i < n ? s.charCodeAt(i) : -1)) {
      if ((i < n ? s.charCodeAt(i) : -1) !== 44) return fail("\",\"");
      i++;
      { let c24 = (i < n ? s.charCodeAt(i) : -1); while ((c24 === 9 || c24 === 32 || c24 === 160)) { i++; c24 = (i < n ? s.charCodeAt(i) : -1); } }
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_item()) return false;
      depth--;
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 125) return fail("\"}\"");
    i++;
    buf[c22 + 2] = i;
    buf[c22 + 3] = top;
  }
  return true;
}

function r_list(): boolean {
  {
    const c26 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c26] = 4;
    buf[c26 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 91) return fail("\"[\"");
    i++;
    { let c27 = (i < n ? s.charCodeAt(i) : -1); while ((c27 === 9 || c27 === 32 || c27 === 160)) { i++; c27 = (i < n ? s.charCodeAt(i) : -1); } }
    { const c29 = (i < n ? s.charCodeAt(i) : -1); if (((c29 >= 0 && c29 < 128 && T3[c29] === 1) || (c29 >= 128 && c29 <= 159) || (c29 >= 161 && c29 <= 65535))) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_item()) return false;
      depth--;
    } }
    for (let c30 = (i < n ? s.charCodeAt(i) : -1); (c30 === 44); c30 = (i < n ? s.charCodeAt(i) : -1)) {
      if ((i < n ? s.charCodeAt(i) : -1) !== 44) return fail("\",\"");
      i++;
      { let c31 = (i < n ? s.charCodeAt(i) : -1); while ((c31 === 9 || c31 === 32 || c31 === 160)) { i++; c31 = (i < n ? s.charCodeAt(i) : -1); } }
      { const c33 = (i < n ? s.charCodeAt(i) : -1); if (((c33 >= 0 && c33 < 128 && T3[c33] === 1) || (c33 >= 128 && c33 <= 159) || (c33 >= 161 && c33 <= 65535))) {
        if (depth >= 64) return fail("at most 64 levels of nesting");
        depth++;
        if (!r_item()) return false;
        depth--;
      } }
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 93) return fail("\"]\"");
    i++;
    buf[c26 + 2] = i;
    buf[c26 + 3] = top;
  }
  return true;
}

function r_quoted(): boolean {
  {
    const c34 = top;
    if (top + 4 > buf.length) grow();
    top += 4;
    buf[c34] = 5;
    buf[c34 + 1] = i;
    if ((i < n ? s.charCodeAt(i) : -1) !== 34) return fail("\"\\\"\"");
    i++;
    for (let c35 = (i < n ? s.charCodeAt(i) : -1); ((c35 >= 0 && c35 < 128 && T5[c35] === 1) || (c35 >= 128 && c35 <= 65535)); c35 = (i < n ? s.charCodeAt(i) : -1)) {
      {
        const c36 = (i < n ? s.charCodeAt(i) : -1);
        if ((c36 === 92)) {
          if ((i < n ? s.charCodeAt(i) : -1) !== 92) return fail("\"\\\\\"");
          i++;
          { const c37 = (i < n ? s.charCodeAt(i) : -1); if (!(c37 >= 0)) return fail("any character"); i++; }
        }
        else if (((c36 >= 0 && c36 < 128 && T4[c36] === 1) || (c36 >= 128 && c36 <= 65535))) {
          { const c38 = (i < n ? s.charCodeAt(i) : -1); if (!((c38 >= 0 && c38 < 128 && T4[c38] === 1) || (c38 >= 128 && c38 <= 65535))) return fail("text"); i++; }
        }
        else return fail("\"\\\\\" or text");
      }
    }
    if ((i < n ? s.charCodeAt(i) : -1) !== 34) return fail("\"\\\"\"");
    i++;
    buf[c34 + 2] = i;
    buf[c34 + 3] = top;
  }
  return true;
}

function r_value(): boolean {
  {
    const c39 = (i < n ? s.charCodeAt(i) : -1);
    if ((c39 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      { let c40 = (i < n ? s.charCodeAt(i) : -1); while ((c40 === 9 || c40 === 32 || c40 === 160)) { i++; c40 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c39 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      { let c42 = (i < n ? s.charCodeAt(i) : -1); while ((c42 === 9 || c42 === 32 || c42 === 160)) { i++; c42 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c39 === 34)) {
      if (!r_quoted()) return false;
      { let c44 = (i < n ? s.charCodeAt(i) : -1); while ((c44 === 9 || c44 === 32 || c44 === 160)) { i++; c44 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if (((c39 >= 0 && c39 < 128 && T6[c39] === 1) || (c39 >= 128 && c39 <= 159) || (c39 >= 161 && c39 <= 65535))) {
      {
        const c46 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c46] = 2;
        buf[c46 + 1] = i;
        { const c47 = (i < n ? s.charCodeAt(i) : -1); if (!((c47 >= 0 && c47 < 128 && T6[c47] === 1) || (c47 >= 128 && c47 <= 159) || (c47 >= 161 && c47 <= 65535))) return fail("a value"); i++; }
        { let c48 = (i < n ? s.charCodeAt(i) : -1); while (((c48 >= 0 && c48 < 128 && T2[c48] === 1) || (c48 >= 128 && c48 <= 65535))) { i++; c48 = (i < n ? s.charCodeAt(i) : -1); } }
        buf[c46 + 2] = i;
        buf[c46 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

function r_item(): boolean {
  {
    const c50 = (i < n ? s.charCodeAt(i) : -1);
    if ((c50 === 123)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_record()) return false;
      depth--;
      { let c51 = (i < n ? s.charCodeAt(i) : -1); while ((c51 === 9 || c51 === 32 || c51 === 160)) { i++; c51 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c50 === 91)) {
      if (depth >= 64) return fail("at most 64 levels of nesting");
      depth++;
      if (!r_list()) return false;
      depth--;
      { let c53 = (i < n ? s.charCodeAt(i) : -1); while ((c53 === 9 || c53 === 32 || c53 === 160)) { i++; c53 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if ((c50 === 34)) {
      if (!r_quoted()) return false;
      { let c55 = (i < n ? s.charCodeAt(i) : -1); while ((c55 === 9 || c55 === 32 || c55 === 160)) { i++; c55 = (i < n ? s.charCodeAt(i) : -1); } }
    }
    else if (((c50 >= 0 && c50 < 128 && T6[c50] === 1) || (c50 >= 128 && c50 <= 159) || (c50 >= 161 && c50 <= 65535))) {
      {
        const c57 = top;
        if (top + 4 > buf.length) grow();
        top += 4;
        buf[c57] = 1;
        buf[c57 + 1] = i;
        {
          const c58 = top;
          if (top + 4 > buf.length) grow();
          top += 4;
          buf[c58] = 2;
          buf[c58 + 1] = i;
          { const c59 = (i < n ? s.charCodeAt(i) : -1); if (!((c59 >= 0 && c59 < 128 && T6[c59] === 1) || (c59 >= 128 && c59 <= 159) || (c59 >= 161 && c59 <= 65535))) return fail("a value"); i++; }
          { let c60 = (i < n ? s.charCodeAt(i) : -1); while (((c60 >= 0 && c60 < 128 && T2[c60] === 1) || (c60 >= 128 && c60 <= 65535))) { i++; c60 = (i < n ? s.charCodeAt(i) : -1); } }
          buf[c58 + 2] = i;
          buf[c58 + 3] = top;
        }
        { const c62 = (i < n ? s.charCodeAt(i) : -1); if ((c62 === 61)) {
          if ((i < n ? s.charCodeAt(i) : -1) !== 61) return fail("\"=\"");
          i++;
          { let c63 = (i < n ? s.charCodeAt(i) : -1); while ((c63 === 9 || c63 === 32 || c63 === 160)) { i++; c63 = (i < n ? s.charCodeAt(i) : -1); } }
          if (depth >= 64) return fail("at most 64 levels of nesting");
          depth++;
          if (!r_value()) return false;
          depth--;
        } }
        buf[c57 + 2] = i;
        buf[c57 + 3] = top;
      }
    }
    else return fail("\"{\", \"[\", \"\\\"\" or a value");
  }
  return true;
}

const RULES: Record<string, () => boolean> = { "span": r_span, "top": r_top, "record": r_record, "list": r_list, "quoted": r_quoted, "value": r_value, "item": r_item };

/**
 * Parse `input` against rule `rule` (default "span"). Never throws on input. The tree
 * is a flat buffer that the NEXT call overwrites (flat.ts) — read it first.
 */
export function parse(input: string, rule = "span"): { ok: true; tree: GenTree } | { ok: false; error: GenError } {
  const start = Object.hasOwn(RULES, rule) ? RULES[rule] : undefined;
  if (!start) throw new Error('segno: no rule "' + rule + '"');
  s = input;
  n = s.length;
  i = 0;
  depth = 0;
  err = null;
  top = 0;
  // A tree that outgrew the first buffer is let go here rather than kept for the page's life: one
  // hostile 3M-character flowchart row held 67 MB through every later parse (phase 3b's red team).
  if (buf.length > 65536) buf = new Int32Array(256);
  const ok = start();
  if (ok && i < n) fail('end of input');
  const e = err as GenError | null;
  if (!ok || e) return { ok: false, error: e ?? { at: i, expected: 'a valid input', found: null } };
  return { ok: true, tree: { buf, top, kinds: KINDS } };
}
