// Auto-generated by tools/lib/timing-engine-hash.js (npm run engine-hash:build) — DO NOT EDIT.
// The timing engine's content hash, written into every LTT as `inputs.engine`. It changes
// whenever a file `buildTrack` is computed from does; test/unit/tools/timing-engine-hash.test.js
// fails when this file is stale.

export const ENGINE_HASH = 'sha256:09c7dc7f5a819a9d10472d38caf4214dda4ce805036e43f507137cd3609a8f1b';
