// Auto-generated by tools/lib/timing-engine-hash.js (npm run engine-hash:build) — DO NOT EDIT.
// The timing engine's content hash, written into every LTT as `inputs.engine`. It changes
// whenever a file `buildTrack` is computed from does; test/unit/tools/timing-engine-hash.test.js
// fails when this file is stale.

export const ENGINE_HASH = 'sha256:4db1f89997767d56f256fa6104ebe1f8e25e7cdb251d5f7b1cb80b6e0f2accbf';
