// Auto-generated by tools/lib/timing-engine-hash.js (npm run engine-hash:build) — DO NOT EDIT.
// The timing engine's content hash, written into every LTT as `inputs.engine`. It changes
// whenever a file `buildTrack` is computed from does; test/unit/tools/timing-engine-hash.test.js
// fails when this file is stale.

export const ENGINE_HASH = 'sha256:6a3d62e1cc2ce48679e6617d7cef83f68aeb503dc0aea693f271c479b47a21d2';
