/**
 * runs-note.mjs — the `_note` banner written into every pick-surface runs artifact.
 *
 * WHY IT IS ITS OWN MODULE. The banner tells a reader which token figure to quote, and it
 * got that wrong once: it said "quote `model_tokens`" on the reasoning that `context_tokens`
 * re-counts the cached prefix per turn. Both do. The harness's docblock and
 * `engineering/capabilities.md` were corrected; the two committed JSONs were not, because
 * rewriting them meant re-running a bake-off that costs about $10. So the artifact a reader
 * opens went on giving withdrawn advice — follow it and you reproduce 14.2x against the
 * 18.4x `2026-08-17-component-pick-surface.md` reports, and conclude the note is wrong.
 *
 * A string that lives only inside a script nobody can import is a string nothing can check.
 * It lives here so the generator and the committed artifacts read from ONE source, and
 * `test/unit/tools/parse-stream.test.js` asserts they still agree — which is what makes the
 * banner correctable without paying for the measurements again.
 */

export const RUNS_NOTE =
  'GENERATED by tools/intent-bakeoff/pick-surface-agent-eval.mjs — do not hand-edit. Each run ' +
  "records the agent RAW return verbatim plus the harness's own tool-call and usage accounting. " +
  'For "how much context did this surface cost", quote model_usage[opus].cacheCreationInputTokens ' +
  '— the newly-cached prefix, billed once, and insensitive to how many reads it took. ' +
  '`model_tokens` and `context_tokens` BOTH accumulate the cached prefix per turn, so both scale ' +
  'with turn count rather than with the surface. None of the three compares to the ' +
  '`subagent_tokens` of the pre-#1897 hand transcription (see git history for that file), which ' +
  'came from the Agent tool inside an interactive session.';
