#!/usr/bin/env node
/**
 * Generate the curated `--cat-1-ink … --cat-12-ink` block for every palette.
 *
 * WHY THIS IS A GENERATOR AND NOT A CSS DERIVATION. The first cut of this tier
 * derived the ink at render time — `color-mix(in oklab, var(--cat-N-mark) 65%,
 * var(--text-heading))`. That is contrast-correct and measurably OFF BRAND: the
 * mix pole has to track the canvas (a fixed black/white pole fails `carbone`, a
 * mode-invariant dark palette, at 1.57:1), and `--text-heading` is itself
 * chromatic on several palettes — indaco navy, mustard brown, burgundy plum. So
 * the mark's hue got dragged toward the heading ink by up to 14.9 degrees, unevenly
 * across slots (indaco light spread 25 degrees, a shear rather than a tint), while
 * 28% of the chroma was mixed away on average. The cycle it derives from is
 * hand-curated per theme; its ink was not, and it showed.
 *
 * THE RECIPE. Keep the mark's HUE and CHROMA exactly; move only LIGHTNESS, by
 * binary search, until the result clears AA against BOTH slide surfaces (`--bg`
 * and `--bg-alt`) with a small margin. Direction is decided per mode from the
 * canvas itself, not assumed: darken on a light canvas, lighten on a dark one —
 * which is what makes `carbone` (dark canvas in BOTH modes) come out right where
 * a fixed pole could not. Chroma gives way only where the solved lightness puts
 * the color outside sRGB, which is `oklchToHex`'s standard gamut clip.
 *
 * The output is CONCRETE per-theme values, committed into each palette next to
 * the fill/mark cycle they belong with — the same shape, and the same method, the
 * shipped `--cat-N-fill`/`--cat-N-mark` values already use (a deterministic recipe
 * run per theme over that theme's own curated hues; see
 * engineering/decisions/2026-07-15-categorical-token-contract.md "Shipped"). That
 * keeps them inspectable, hand-tunable, and reachable by `section.print`'s remap —
 * none of which a `:root`-scoped color-mix was.
 *
 * Re-run this after re-hueing a mark tier. `checkCatContrast` gates the result
 * (AA on three canvases, plus an anti-collapse arm on the hue palettes).
 *
 * NOTE ON HAND-TUNING: `npm run build` runs this in WRITE mode (tools/build.js), so
 * a hand-edited value is not merely flagged — it is regenerated over. Change the
 * mark, or change the recipe; editing the output does not stick.
 *
 * Usage:
 *   node tools/derive-cat-ink.js            # rewrite the ink block in every palette
 *   node tools/derive-cat-ink.js --check    # verify committed values match (CI)
 *   node tools/derive-cat-ink.js --report   # print fidelity stats, write nothing
 */

const fs = require('node:fs');
const path = require('node:path');
const { resolveTokenExpr } = require('../lib/core/resolve-token-expr');
const { hexToOklch, withLightness, contrastRatio, oklabDistance } = require('../lib/theme/color.js');

const ROOT = path.join(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const SLOTS = 12;
const AA = 4.5;
const MARGIN = 0.15; // solve to 4.65:1 so a later rounding/regeneration cannot land under the floor
// The separation an ink pair is held to, in OKLab ΔE — but only ever as much as
// the MARK pair already had (see `separationTarget`). This is a ceiling on what
// the guard will try to restore, not a standard imposed on the palette.
//
// WHY IT IS RELATIVE TO THE MARKS, and not an absolute floor. Measured across the
// shipped palettes, the minimum ink separation runs continuously from 0.0013
// (`concrete` dark) through 0.0065 (`cuoio` dark) and 0.0105 (`indaco`/`carta`
// dark) up to 0.055 (`carbone`). There is no gap to put a floor in: any threshold
// that catches concrete's near-identical dark arm also rewrites cuoio's and
// indaco's CURATED cycles — and those values are the designer's, inherited
// unchanged from marks that are themselves that close. A generator that "improves"
// a hand-curated spacing is committing the same off-brand sin as the color-mix
// this tier replaced.
//
// So the guard's question is not "are these far enough apart?" but "did the SOLVE
// lose separation the palette had?". concrete dark inherits its 0.0013 from its own
// marks and is left exactly alone; the a11y grayscale ramp, whose distinguishable
// marks all solve onto ONE lightness, is restored to the marks' own spacing.
const MIN_DIST = 0.035;

/**
 * How far apart this pair of inks must sit: the marks' own separation, capped at
 * MIN_DIST. Never asks for more distinction than the palette itself carries.
 */
function separationTarget(markA, markB) {
  return Math.min(MIN_DIST, oklabDistance(markA, markB));
}

const BEGIN = '/* ── CATEGORICAL ON-CANVAS INK — generated by tools/derive-cat-ink.js ──';
const END = '  /* ── end categorical on-canvas ink ── */';

/** Every palette file, `@import` chain flattened, base first (cascade order). */
function paletteSource(name, seen = new Set()) {
  if (seen.has(name)) return '';
  seen.add(name);
  if (name === 'lattice') return fs.readFileSync(path.join(ROOT, 'lib', 'base', 'base.tokens.css'), 'utf8');
  const file = path.join(THEMES_DIR, `${name}.css`);
  if (!fs.existsSync(file)) return '';
  const css = fs.readFileSync(file, 'utf8');
  let out = '';
  for (const m of stripComments(css).matchAll(/@import\s+['"]([^'"]+)['"]/g)) out += `${paletteSource(m[1], seen)}\n`;
  return `${out}${css}`;
}
function stripComments(s) { return s.replace(/\/\*[\s\S]*?\*\//g, ''); }
function declaredVars(css) {
  const vars = {};
  for (const m of stripComments(css).matchAll(/--([a-zA-Z0-9-]+)\s*:\s*([^;}]+)[;}]/g)) vars[m[1]] = m[2].trim();
  return vars;
}
const isHex = (v) => typeof v === 'string' && /^#[0-9a-fA-F]{6}$/.test(String(v).trim());

/**
 * The mark, moved in lightness only, until it clears `AA + MARGIN` on both
 * surfaces. Returns the mark unchanged when it already clears — an ink that does
 * not need repair should not be repainted.
 */
function solveInk(mark, bg, bgAlt) {
  const clears = (hex) => Math.min(contrastRatio(hex, bg), contrastRatio(hex, bgAlt)) >= AA + MARGIN;
  if (clears(mark)) return mark;
  const { L } = hexToOklch(mark);
  // Which way is safety? Whichever pole the canvases are further from. Decided
  // from the resolved surfaces, never assumed from the mode name — that is what
  // makes a dark-canvas "light mode" palette (carbone) solve correctly.
  // TRY BOTH POLES. Guessing the direction from the surfaces' average lightness is
  // wrong whenever the mark sits between --bg and --bg-alt, or above a mid-tone
  // canvas: `concrete`'s light surfaces average L=0.827, so any mark lighter than
  // that was sent toward WHITE and returned a 1.47:1 value the generator then wrote
  // into tracked source (the black pole would have given 10.56:1). Solve toward each
  // pole, keep whichever clears with the smaller move.
  const solveToward = (target) => {
    if (!clears(withLightness(mark, target))) return null;
    let near = L;      // known NOT to clear
    let far = target;  // known to clear
    for (let i = 0; i < 40 && Math.abs(far - near) > 1e-4; i += 1) {
      const mid = (near + far) / 2;
      if (clears(withLightness(mark, mid))) far = mid;
      else near = mid;
    }
    return { L: far, hex: withLightness(mark, far) };
  };
  const candidates = [solveToward(0), solveToward(1)].filter(Boolean);
  if (!candidates.length) return null; // neither pole works — the caller must say so
  candidates.sort((a, b) => Math.abs(a.L - L) - Math.abs(b.L - L));
  return candidates[0].hex;
}

/**
 * The lightness interval, for one mark, over which the ink clears AA on BOTH
 * surfaces — as `{ dir, bound }`.
 *
 * Contrast against a fixed surface is monotone in L (falling against a light
 * surface, rising against a dark one), so the feasible set for a hue is always
 * ONE-SIDED: either `[0, bound]` (safety lies toward black, `dir: -1`) or
 * `[bound, 1]` (toward white, `dir: +1`). Never both — clearing 4.5:1 against a
 * light AND a dark surface simultaneously has no solution for any real canvas
 * pair. `null` when neither pole clears, which is the same condition that makes
 * `solveInk` return null.
 */
function feasibleRange(mark, bg, bgAlt) {
  const clears = (L) => {
    const hex = withLightness(mark, L);
    return Math.min(contrastRatio(hex, bg), contrastRatio(hex, bgAlt)) >= AA + MARGIN;
  };
  const dir = clears(0) ? -1 : clears(1) ? 1 : null;
  if (dir === null) return null;
  // Bisect for the far edge of the feasible interval.
  let inside = dir === -1 ? 0 : 1;      // known to clear
  let outside = dir === -1 ? 1 : 0;     // known not to
  for (let i = 0; i < 40 && Math.abs(outside - inside) > 1e-4; i += 1) {
    const mid = (inside + outside) / 2;
    if (clears(mid)) inside = mid; else outside = mid;
  }
  return { dir, bound: inside, clears };
}

/**
 * True when the SOLVE cost this arm separation its marks had — i.e. some pair of
 * inks now reads as one category where the corresponding marks read as two.
 * Perceptual (OKLab), not hex identity: `new Set(hexes).size === 12` calls
 * concrete's dark arm, twelve values spanning two units out of 255, a distinct
 * cycle — true only to a string comparator.
 */
function armCollapsed(arms, marks, key) {
  for (let i = 1; i <= SLOTS; i += 1) {
    for (let j = i + 1; j <= SLOTS; j += 1) {
      const a = arms[i]?.[key], b = arms[j]?.[key];
      if (!a || !b) continue;
      if (oklabDistance(a, b) < separationTarget(marks[i], marks[j]) - 1e-9) return true;
    }
  }
  return false;
}

/**
 * Push apart only the slots of `arms[*][key]` that are not already separated.
 *
 * Works in "safety" coordinates: `u = dir * L`, so larger u is always further
 * from the canvas and therefore always still legal. Slots are visited in
 * increasing u — i.e. from the least-safe end — and each is either left exactly
 * where `solveInk` put it (when it already sits MIN_SEP beyond its predecessor)
 * or pushed the minimum distance to reach that gap. Pushing along +u can never
 * break AA, because the feasible interval is one-sided and unbounded in that
 * direction up to the pole; the only way to fail is to run out of axis, which
 * throws rather than silently clamping.
 *
 * Slots whose feasible direction differs (possible on a mixed palette where some
 * marks are lighter and some darker than the canvas) are separated independently
 * within their own direction group — two inks on opposite sides of the canvas are
 * already far apart in lightness and cannot be the pair that collided.
 *
 * WHAT THIS DOES NOT FIX, stated rather than hidden. The only lever here is
 * lightness, so two marks of DIFFERENT hue that the solve pushed to the same
 * lightness cannot be pulled fully back apart: moving either one further only
 * trades their separation for a bigger move off the curated value. Measured over
 * the shipped palettes, the guard takes solve-induced separation loss from 272
 * pairs to 18 (of 4224). Every one of the 18 keeps 71-97% of its marks'
 * separation, and the tightest lands at 0.0119 — wider than the 0.0105 that
 * `indaco`'s own CURATED dark cycle ships, so they sit inside the range the
 * design already accepts. They are different hues (#3A6E00 vs #00720C), not
 * repeats. `checkCatContrast`'s collapse arm holds the floor that matters.
 */
function separateArm({ arms, marks, key, bg, bgAlt, theme }) {
  const groups = new Map(); // dir → [{ n, u, bound }]
  for (let n = 1; n <= SLOTS; n += 1) {
    const range = feasibleRange(marks[n], bg, bgAlt);
    if (!range) {
      throw new Error(
        `${theme}: --cat-${n}-mark has no legible lightness on the ${key} canvas — ` +
        `no shade of its hue clears ${AA}:1 against both --bg and --bg-alt. ` +
        `Re-running the generator cannot fix this: widen the gap between the two ` +
        `canvas surfaces, or re-hue the mark.`,
      );
    }
    const { dir, bound } = range;
    if (!groups.has(dir)) groups.set(dir, []);
    groups.get(dir).push({ n, u: dir * hexToOklch(arms[n][key]).L, uBound: dir * bound });
  }
  for (const [dir, slots] of groups) {
    slots.sort((a, b) => a.u - b.u);
    // uMax is the far pole in safety coordinates: 0 for dir -1, 1 for dir +1.
    const uMax = dir === -1 ? 0 : 1;
    let prevHex = null;
    let prevN = null;
    let prevU = -Infinity;
    for (const slot of slots) {
      // MONOTONE IN u. Comparing each slot only against its immediate predecessor
      // is not enough: a slot left at its solved position can clear the pushed slot
      // before it while still coinciding with the one two back, so the walk
      // alternates push / don't-push and half the arm stays collapsed (measured on
      // a11y dark: six slots left on one value). Never stepping backwards makes the
      // placed sequence strictly increasing, which gives all-pairs separation from
      // the adjacent test alone.
      let u = Math.max(slot.u, prevU);
      const need = prevN === null ? 0 : separationTarget(marks[slot.n], marks[prevN]);
      if (prevHex !== null) {
        // Walk +u (always further from the canvas, so always still legible) until
        // this slot reads as its own color. A pair that differs in hue satisfies
        // the test at its solved position and never moves.
        while (u <= uMax && oklabDistance(withLightness(marks[slot.n], dir * u), prevHex) < need) {
          u += Math.max(need, 1e-3) / 8;
        }
        if (u > uMax + 1e-9) {
          throw new Error(
            `${theme}: the ${key} ink arm cannot hold ${SLOTS} distinguishable slots — ` +
            `after clearing ${AA}:1 there is not ${need.toFixed(4)} of perceptual room left ` +
            `between every pair (ran out at --cat-${slot.n}-ink). This is a property ` +
            `of the palette, not of the generator: re-running it will reproduce it. ` +
            `Widen the categorical marks' lightness range, or raise the contrast ` +
            `between --bg and --bg-alt.`,
          );
        }
      }
      if (u !== slot.u) arms[slot.n][key] = withLightness(marks[slot.n], dir * u);
      prevU = u;
      prevN = slot.n;
      prevHex = arms[slot.n][key];
    }
  }
}

/** The 12 `light-dark(...)` ink values for one palette, plus fidelity stats. */
function inkFor(theme) {
  // Base tokens from SOURCE, not dist/ — this generator runs inside `npm run build`,
  // so depending on a built artifact would make it order-sensitive against the very
  // bundle it helps produce.
  const raw = declaredVars(paletteSource(theme));
  const arms = {};
  const marks = {};
  const stats = { shift: 0, chroma: [], repaired: 0, total: 0, collapsed: [], chromaLost: [] };
  for (const dark of [false, true]) {
    const R = (t) => resolveTokenExpr(raw[t], raw, dark);
    const bg = R('bg');
    const bgAlt = R('bg-alt');
    if (!isHex(bg) || !isHex(bgAlt)) throw new Error(`${theme}: --bg/--bg-alt did not resolve`);
    for (let n = 1; n <= SLOTS; n += 1) {
      const mark = R(`cat-${n}-mark`);
      if (!isHex(mark)) throw new Error(`${theme}: --cat-${n}-mark did not resolve`);
      const ink = solveInk(mark, bg, bgAlt);
      // solveInk returns null when NEITHER pole clears — the canvas pair is too
      // close together for any shade of any hue to reach AA against both (e.g.
      // --bg and --bg-alt both mid-gray). Say that here, naming the theme, the
      // slot and the two surfaces. Letting the null travel produces `not a hex
      // color: null` from deep inside lib/theme/color.js, which names nothing.
      if (!isHex(ink)) {
        throw new Error(
          `${theme}: no legible --cat-${n}-ink exists on the ${dark ? 'dark' : 'light'} canvas. ` +
          `--bg ${bg} and --bg-alt ${bgAlt} are close enough in lightness that no shade of ` +
          `--cat-${n}-mark (${mark}) clears ${AA}:1 against both. Widen the gap between the two ` +
          `surfaces — this is a palette fact the generator cannot solve around.`,
        );
      }
      (arms[n] ??= {})[dark ? 'dark' : 'light'] = ink;
      marks[n] = mark;
    }
    // ANTI-COLLAPSE, BY SEPARATING ONLY WHAT COLLIDES.
    //
    // Solving each slot for the least move that clears AA is right while the slots
    // stay tellable apart. On a ramp that differs only in lightness — the a11y
    // grayscale cycle — every slot fails in the same direction and converges on the
    // same solved lightness: 12 slots, 1 color.
    //
    // TWO EARLIER CUTS OF THIS GUARD WERE WRONG, in opposite directions, and both
    // shipped green. The first set every slot to the lightness pole: that kept the
    // collapse AND destroyed the hue of all twelve, because the gamut clip at the
    // pole turns a teal into #000001. The second moved the whole arm by the largest
    // single delta: that preserved a LIGHTNESS ramp's spacing (a11y) but, on the
    // fourteen HUE cycles, rewrote all twelve curated inks — including slots that
    // already cleared untouched — off their marks whenever any two collided, losing
    // most of their chroma. `concrete` dark ships two inks one channel step apart,
    // so that was one rounding change away from firing. It could also clamp six
    // slots onto #000000, or no-op entirely when the largest delta was 0 — leaving
    // the very collapse it exists to prevent, while `checkCatContrast` told the
    // maintainer to re-run a DETERMINISTIC generator that would reproduce it.
    //
    // What is actually wanted is the least intervention that makes the arm
    // readable: keep every slot that is already separated, and push only a
    // colliding one — along its own hue, inside its own feasible interval, in the
    // ramp's existing order. On a hue cycle that touches two slots and leaves ten
    // alone; on the a11y ramp every slot collides, so it spreads all twelve, which
    // is the case the uniform shift was built for. If the feasible room genuinely
    // cannot hold twelve separated slots, that is a palette fact, not something a
    // re-run can fix — so it throws and says so.
    const key = dark ? 'dark' : 'light';
    if (armCollapsed(arms, marks, key)) {
      separateArm({ arms, marks, key, bg, bgAlt, theme });
      stats.collapsed.push(key);
    }

    // Fidelity is measured AFTER any anti-collapse pass, over the values actually
    // written. Measuring inside the per-slot loop described colors the guard had
    // already replaced — the report claimed "chroma kept 100%" for an arm written as
    // pure black. A statistic that cannot see the failure mode is worse than none.
    for (let n = 1; n <= SLOTS; n += 1) {
      const M = hexToOklch(marks[n]);
      const I = hexToOklch(arms[n][key]);
      stats.total += 1;
      if (arms[n][key].toLowerCase() !== marks[n].toLowerCase()) stats.repaired += 1;
      if (M.C > 0.02) {
        // Include the clipped case: if the write killed the chroma, that IS the
        // finding, so fall back to comparing against the mark's own hue.
        let d = Math.abs(M.h - I.h) % 360;
        if (d > 180) d = 360 - d;
        if (I.C > 0.02) stats.shift = Math.max(stats.shift, d);
        else stats.chromaLost.push(`cat-${n}-${key}`);
      }
      if (M.C > 0.001) stats.chroma.push(I.C / M.C);
    }
  }
  return { arms, stats };
}

function renderBlock(arms) {
  const lines = [
    '  /* ── CATEGORICAL ON-CANVAS INK — generated by tools/derive-cat-ink.js ──',
    '   * The categorical hue as TEXT on --bg / --bg-alt, one per slot. Same hue and',
    '   * chroma as --cat-N-mark; lightness solved until it clears AA on both slide',
    '   * surfaces. Do not hand-edit: re-run the generator after re-hueing a mark.',
    '   * Gated by checkCatContrast (layer 4) on light, dark and the print band. */',
  ];
  for (let n = 1; n <= SLOTS; n += 1) {
    const pad = n < 10 ? ' ' : '';
    lines.push(`  --cat-${n}-ink:${pad}  light-dark(${arms[n].light.toUpperCase()}, ${arms[n].dark.toUpperCase()});`);
  }
  lines.push(END);
  return `${lines.join('\n')}\n`;
}

/** Splice the generated block into a palette, replacing any previous one. */
function writeBlock(file, block) {
  let css = fs.readFileSync(file, 'utf8');
  const at = css.indexOf(BEGIN.trim());
  if (at !== -1) {
    const endAt = css.indexOf(END, at);
    const lineStart = css.lastIndexOf('\n', at) + 1;
    css = css.slice(0, lineStart) + block + css.slice(endAt + END.length + 1);
  } else {
    // Land it directly after the mark cycle, where a reader looks for it.
    // Anchored on the LAST line mentioning --cat-12-mark, not on a line that
    // starts with it: carbone pairs fill and mark on one line.
    const m = [...css.matchAll(/^[^\n]*--cat-12-mark\s*:[^\n]*\n/gm)].pop();
    if (!m) throw new Error(`${file}: no --cat-12-mark to anchor the ink block to`);
    const insertAt = m.index + m[0].length;
    css = `${css.slice(0, insertAt)}\n${block}${css.slice(insertAt)}`;
  }
  fs.writeFileSync(file, css);
}

function main() {
  const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--report') ? 'report' : 'write';
  const themes = fs.readdirSync(THEMES_DIR)
    .filter((f) => f.endsWith('.css') && !f.includes('audit'))
    .map((f) => f.replace(/\.css$/, ''))
    .filter((t) => !/-dark$/.test(t)) // a `-dark` wrapper is a color-scheme flip over its base
    // Only palettes that OWN a mark cycle get a block. The four a11y-* variants
    // declare just their status trio and inherit the ramp from a11y-base, so a
    // block there would be twelve redundant copies drifting out of one source.
    .filter((t) => /--cat-1-mark\s*:/.test(stripComments(fs.readFileSync(path.join(THEMES_DIR, `${t}.css`), 'utf8'))))
    .sort();

  const stale = [];
  let worstShift = 0;
  let chroma = [];
  for (const theme of themes) {
    const { arms, stats } = inkFor(theme);
    worstShift = Math.max(worstShift, stats.shift);
    chroma = chroma.concat(stats.chroma);
    const block = renderBlock(arms);
    const file = path.join(THEMES_DIR, `${theme}.css`);
    const current = fs.readFileSync(file, 'utf8');
    const at = current.indexOf(BEGIN.trim());
    const has = at !== -1 && current.slice(current.lastIndexOf('\n', at) + 1).startsWith(block);
    if (mode === 'write') writeBlock(file, block);
    else if (mode === 'check' && !has) stale.push(theme);
    if (mode === 'report') {
      const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 1);
      console.log(`${theme.padEnd(20)} repaired ${String(stats.repaired).padStart(2)}/${stats.total}  max hue shift ${stats.shift.toFixed(2)}deg  chroma kept ${(100 * mean(stats.chroma)).toFixed(0)}%${stats.collapsed.length ? `  [anti-collapse: ${stats.collapsed.join(',')}]` : ''}`);
    }
  }
  const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 1);
  if (mode === 'check') {
    if (stale.length) {
      console.error(`derive-cat-ink: ${stale.length} palette(s) have a stale --cat-N-ink block: ${stale.join(', ')}.\nRun \`node tools/derive-cat-ink.js\` and commit.`);
      process.exit(1);
    }
    console.log(`derive-cat-ink: ${themes.length} palettes up to date.`);
  } else if (mode === 'write') {
    console.log(`derive-cat-ink: wrote ${themes.length} palettes · max hue shift ${worstShift.toFixed(2)}deg · chroma kept ${(100 * mean(chroma)).toFixed(0)}%`);
  } else {
    console.log(`\nALL: max hue shift ${worstShift.toFixed(2)}deg · chroma kept ${(100 * mean(chroma)).toFixed(0)}%`);
  }
}

if (require.main === module) main();
module.exports = { inkFor, solveInk, renderBlock, BEGIN, END };
