#!/usr/bin/env node
/**
 * Generate the curated `--cat-1-ink … --cat-12-ink` block for every palette.
 *
 * WHY THIS IS A GENERATOR AND NOT A CSS DERIVATION. The first cut of this tier
 * derived the ink at render time — `color-mix(in oklab, var(--cat-N-mark) 65%,
 * var(--text-heading))`. That is contrast-correct and measurably OFF BRAND: the
 * mix pole has to track the canvas (a fixed black/white pole fails `carbone`, a
 * mode-invariant dark palette, at 1.57:1), and `--text-heading` is itself
 * chromatic on several palettes — indaco navy, mustard brown, burgundy plum. So
 * the mark's hue got dragged toward the heading ink by up to 14.9 degrees, unevenly
 * across slots (indaco light spread 25 degrees, a shear rather than a tint), while
 * 28% of the chroma was mixed away on average. The cycle it derives from is
 * hand-curated per theme; its ink was not, and it showed.
 *
 * THE RECIPE. Keep the mark's HUE and CHROMA exactly; move only LIGHTNESS, by
 * binary search, until the result clears AA against BOTH slide surfaces (`--bg`
 * and `--bg-alt`) with a small margin. Direction is decided per mode from the
 * canvas itself, not assumed: darken on a light canvas, lighten on a dark one —
 * which is what makes `carbone` (dark canvas in BOTH modes) come out right where
 * a fixed pole could not. Chroma gives way only where the solved lightness puts
 * the color outside sRGB, which is `oklchToHex`'s standard gamut clip.
 *
 * THE SOLVE ITSELF LIVES IN `lib/theme/cat-ink.js` and is shared with the
 * Studio's browser-bundled generator (`lib/theme/derive.js`), which grew the same
 * tier in #1457. This file owns the FILE half — which palettes get a block, how it
 * is spliced in, the fidelity report — and calls the shared solver in STRICT mode,
 * where an unsolvable palette throws instead of degrading: this one writes tracked
 * source, so a human has to fix it.
 *
 * The output is CONCRETE per-theme values, committed into each palette next to
 * the fill/mark cycle they belong with — the same shape, and the same method, the
 * shipped `--cat-N-fill`/`--cat-N-mark` values already use (a deterministic recipe
 * run per theme over that theme's own curated hues; see
 * engineering/decisions/2026-07-15-categorical-token-contract.md "Shipped"). That
 * keeps them inspectable, hand-tunable, and reachable by `section.print`'s remap —
 * none of which a `:root`-scoped color-mix was.
 *
 * Re-run this after re-hueing a mark tier. `checkCatContrast` gates the result
 * (AA on three canvases, plus an anti-collapse arm on the hue palettes).
 *
 * NOTE ON HAND-TUNING: `npm run build` runs this in WRITE mode (tools/build.js), so
 * a hand-edited value is not merely flagged — it is regenerated over. Change the
 * mark, or change the recipe; editing the output does not stick.
 *
 * Usage:
 *   node tools/derive-cat-ink.js            # rewrite the ink block in every palette
 *   node tools/derive-cat-ink.js --check    # verify committed values match (CI)
 *   node tools/derive-cat-ink.js --report   # print fidelity stats, write nothing
 */

const fs = require('node:fs');
const path = require('node:path');
const { resolveTokenExpr } = require('../lib/core/resolve-token-expr');
const { hexToOklch } = require('../lib/theme/color.js');
const { solveInk, solveInkArm } = require('../lib/theme/cat-ink.js');

const ROOT = path.join(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const SLOTS = 12;

const BEGIN = '/* ── CATEGORICAL ON-CANVAS INK — generated by tools/derive-cat-ink.js ──';
const END = '  /* ── end categorical on-canvas ink ── */';

/** Every palette file, `@import` chain flattened, base first (cascade order). */
function paletteSource(name, seen = new Set()) {
  if (seen.has(name)) return '';
  seen.add(name);
  if (name === 'lattice') return fs.readFileSync(path.join(ROOT, 'lib', 'base', 'base.tokens.css'), 'utf8');
  const file = path.join(THEMES_DIR, `${name}.css`);
  if (!fs.existsSync(file)) return '';
  const css = fs.readFileSync(file, 'utf8');
  let out = '';
  for (const m of stripComments(css).matchAll(/@import\s+['"]([^'"]+)['"]/g)) out += `${paletteSource(m[1], seen)}\n`;
  return `${out}${css}`;
}
function stripComments(s) { return s.replace(/\/\*[\s\S]*?\*\//g, ''); }
function declaredVars(css) {
  const vars = {};
  for (const m of stripComments(css).matchAll(/--([a-zA-Z0-9-]+)\s*:\s*([^;}]+)[;}]/g)) vars[m[1]] = m[2].trim();
  return vars;
}
const isHex = (v) => typeof v === 'string' && /^#[0-9a-fA-F]{6}$/.test(String(v).trim());

/** The 12 `light-dark(...)` ink values for one palette, plus fidelity stats. */
function inkFor(theme) {
  // Base tokens from SOURCE, not dist/ — this generator runs inside `npm run build`,
  // so depending on a built artifact would make it order-sensitive against the very
  // bundle it helps produce.
  const raw = declaredVars(paletteSource(theme));
  const arms = {};
  const marks = {};
  const stats = { shift: 0, chroma: [], repaired: 0, total: 0, collapsed: [], chromaLost: [] };
  for (const dark of [false, true]) {
    const key = dark ? 'dark' : 'light';
    const R = (t) => resolveTokenExpr(raw[t], raw, dark);
    const bg = R('bg');
    const bgAlt = R('bg-alt');
    if (!isHex(bg) || !isHex(bgAlt)) throw new Error(`${theme}: --bg/--bg-alt did not resolve`);
    const armMarks = [];
    for (let n = 1; n <= SLOTS; n += 1) {
      const mark = R(`cat-${n}-mark`);
      if (!isHex(mark)) throw new Error(`${theme}: --cat-${n}-mark did not resolve`);
      armMarks.push(mark);
      marks[n] = mark;
    }
    // STRICT. An unsolvable palette here is a fact about tracked source — the two
    // canvas surfaces are too close for any shade of some hue to clear AA on both,
    // or the arm has no room left to hold twelve distinguishable slots. Both are
    // properties of the palette that a re-run reproduces, so this caller wants the
    // throw that names the theme and the slot, not a best-effort value written
    // silently into a committed file. (The Studio's caller takes the other half of
    // the policy — see lib/theme/cat-ink.js.)
    const { inks, collapsed } = solveInkArm({ marks: armMarks, bg, bgAlt, strict: true, label: theme, arm: key });
    for (let n = 1; n <= SLOTS; n += 1) (arms[n] ??= {})[key] = inks[n - 1];
    if (collapsed) stats.collapsed.push(key);

    // Fidelity is measured AFTER any anti-collapse pass, over the values actually
    // written. Measuring inside the per-slot loop described colors the guard had
    // already replaced — the report claimed "chroma kept 100%" for an arm written as
    // pure black. A statistic that cannot see the failure mode is worse than none.
    for (let n = 1; n <= SLOTS; n += 1) {
      const M = hexToOklch(marks[n]);
      const I = hexToOklch(arms[n][key]);
      stats.total += 1;
      if (arms[n][key].toLowerCase() !== marks[n].toLowerCase()) stats.repaired += 1;
      if (M.C > 0.02) {
        // Include the clipped case: if the write killed the chroma, that IS the
        // finding, so fall back to comparing against the mark's own hue.
        let d = Math.abs(M.h - I.h) % 360;
        if (d > 180) d = 360 - d;
        if (I.C > 0.02) stats.shift = Math.max(stats.shift, d);
        else stats.chromaLost.push(`cat-${n}-${key}`);
      }
      if (M.C > 0.001) stats.chroma.push(I.C / M.C);
    }
  }
  return { arms, stats };
}

function renderBlock(arms) {
  const lines = [
    '  /* ── CATEGORICAL ON-CANVAS INK — generated by tools/derive-cat-ink.js ──',
    '   * The categorical hue as TEXT on --bg / --bg-alt, one per slot. Same hue and',
    '   * chroma as --cat-N-mark; lightness solved until it clears AA on both slide',
    '   * surfaces. Do not hand-edit: re-run the generator after re-hueing a mark.',
    '   * Gated by checkCatContrast (layer 4) on light, dark and the print band. */',
  ];
  for (let n = 1; n <= SLOTS; n += 1) {
    const pad = n < 10 ? ' ' : '';
    lines.push(`  --cat-${n}-ink:${pad}  light-dark(${arms[n].light.toUpperCase()}, ${arms[n].dark.toUpperCase()});`);
  }
  lines.push(END);
  return `${lines.join('\n')}\n`;
}

/** Splice the generated block into a palette, replacing any previous one. */
function writeBlock(file, block) {
  let css = fs.readFileSync(file, 'utf8');
  const at = css.indexOf(BEGIN.trim());
  if (at !== -1) {
    const endAt = css.indexOf(END, at);
    const lineStart = css.lastIndexOf('\n', at) + 1;
    css = css.slice(0, lineStart) + block + css.slice(endAt + END.length + 1);
  } else {
    // Land it directly after the mark cycle, where a reader looks for it.
    // Anchored on the LAST line mentioning --cat-12-mark, not on a line that
    // starts with it: carbone pairs fill and mark on one line.
    const m = [...css.matchAll(/^[^\n]*--cat-12-mark\s*:[^\n]*\n/gm)].pop();
    if (!m) throw new Error(`${file}: no --cat-12-mark to anchor the ink block to`);
    const insertAt = m.index + m[0].length;
    css = `${css.slice(0, insertAt)}\n${block}${css.slice(insertAt)}`;
  }
  fs.writeFileSync(file, css);
}

function main() {
  const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--report') ? 'report' : 'write';
  // SCOPE COMES FROM THE MANIFESTS. This used to read the directory and exclude
  // `-dark` by FILENAME, which made the convention load-bearing; the role is now
  // declared in themes/<name>.manifest.json and proved against the file by
  // `checkThemeRoles`. See engineering/decisions/2026-08-09-theme-token-contract.md.
  const themes = fs.readdirSync(THEMES_DIR)
    .filter((f) => f.endsWith('.manifest.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(THEMES_DIR, f), 'utf8')))
    .filter((m) => m.role !== 'variant-dark') // a variant-dark is a color-scheme flip over its base
    .map((m) => m.name)
    // Only palettes that OWN a mark cycle get a block. The four a11y-* variants
    // declare just their status trio and inherit the ramp from a11y-base, so a
    // block there would be twelve redundant copies drifting out of one source.
    .filter((t) => /--cat-1-mark\s*:/.test(stripComments(fs.readFileSync(path.join(THEMES_DIR, `${t}.css`), 'utf8'))))
    .sort();

  const stale = [];
  let worstShift = 0;
  let chroma = [];
  for (const theme of themes) {
    const { arms, stats } = inkFor(theme);
    worstShift = Math.max(worstShift, stats.shift);
    chroma = chroma.concat(stats.chroma);
    const block = renderBlock(arms);
    const file = path.join(THEMES_DIR, `${theme}.css`);
    const current = fs.readFileSync(file, 'utf8');
    const at = current.indexOf(BEGIN.trim());
    const has = at !== -1 && current.slice(current.lastIndexOf('\n', at) + 1).startsWith(block);
    if (mode === 'write') writeBlock(file, block);
    else if (mode === 'check' && !has) stale.push(theme);
    if (mode === 'report') {
      const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 1);
      console.log(`${theme.padEnd(20)} repaired ${String(stats.repaired).padStart(2)}/${stats.total}  max hue shift ${stats.shift.toFixed(2)}deg  chroma kept ${(100 * mean(stats.chroma)).toFixed(0)}%${stats.collapsed.length ? `  [anti-collapse: ${stats.collapsed.join(',')}]` : ''}`);
    }
  }
  const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 1);
  if (mode === 'check') {
    if (stale.length) {
      console.error(`derive-cat-ink: ${stale.length} palette(s) have a stale --cat-N-ink block: ${stale.join(', ')}.\nRun \`node tools/derive-cat-ink.js\` and commit.`);
      process.exit(1);
    }
    console.log(`derive-cat-ink: ${themes.length} palettes up to date.`);
  } else if (mode === 'write') {
    console.log(`derive-cat-ink: wrote ${themes.length} palettes · max hue shift ${worstShift.toFixed(2)}deg · chroma kept ${(100 * mean(chroma)).toFixed(0)}%`);
  } else {
    console.log(`\nALL: max hue shift ${worstShift.toFixed(2)}deg · chroma kept ${(100 * mean(chroma)).toFixed(0)}%`);
  }
}

if (require.main === module) main();
// `solveInk` is re-exported (not redefined): the recipe lives in lib/theme/cat-ink.js
// now that the Studio shares it, and this path keeps working for its callers/tests.
module.exports = { inkFor, solveInk, renderBlock, BEGIN, END };
