/**
 * Unit: a status trio's CVD separation may improve, never erode.
 *
 * `test/unit/palette/cvd-palette.test.js` gates the four a11y CVD palettes, which
 * are curated for separation. Nothing gated the FOURTEEN brand palettes, and
 * `tools/cvd-audit.js` is a report that exits 0 — so a re-tune driven by some other
 * constraint could collapse a pair with every gate green.
 *
 * It did. #1704 moved `--pass` on ardesia / brina / laguna to clear AA on redline's
 * own-hue band, and rotated magnolia's `--fail` -14 deg to clear the same band on a
 * dark canvas. Measured afterwards against `origin/main`: pass^fail under
 * PROTANOPIA went 0.158 -> 0.094 on ardesia and 0.152 -> 0.087 on laguna, and
 * magnolia's warn^fail under TRITANOPIA went 0.1209 -> 0.0473. laguna's shipped
 * value was not an accident — CHANGELOG.md records it as "chosen so it still holds
 * the >=0.15 protanopia pass<->fail CVD floor". That is the #1181 shape: a re-tune
 * satisfying its own surface and breaking a distant one through a shared channel
 * (HARD RULE #18).
 *
 * WHAT IS FROZEN IS THE DISTANCE, NOT THE SET. The first cut of this gate froze the
 * SET of pairs above the floor, and that is why it reported "0 newly collapsed"
 * while 21 pairs eroded and 4 later crossed: a pair already under the floor could
 * decay without limit, and one at 0.1584 could sit at 0.1483 as long as it was not
 * re-counted. It is the same hole this repo's contrast baseline was keyed to close
 * — "a count says nothing about an existing failure getting worse" — and the CVD
 * arm shipped with it anyway. Values, keyed, with an explicit rule:
 *
 *   · frozen AT OR ABOVE the 0.15 collapse floor -> must still clear 0.15.
 *     Separation above the floor is spendable; the floor itself is not.
 *   · frozen BELOW the floor -> must not drop further. The pair is already
 *     unreadable under that deficiency and taking it lower is a loss with no
 *     offsetting gain. (The brand palettes are not CVD-curated, so many pairs sit
 *     here and always have; lifting them all is a different change.)
 *
 * If this fails: a token move eroded a pair. Solve the trio TOGETHER — move the
 * companion token (magnolia needed `--warn` lifted with `--fail`), and remember
 * that LIGHTNESS is the only channel every deficiency preserves, so two hues that
 * must stay apart under simulation need a luminance gap. Do not delete the key,
 * and do not re-bless a number downward without saying why.
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { simulate, SIMULATED_TYPES, ACHROMATOPSIA } = require('../../../lib/theme/cvd.js');
const { oklabDistance } = require('../../../lib/theme/color.js');
const { resolveTokenExpr } = require('../../../lib/core/resolve-token-expr.js');
const { mergedVars, listAllThemes } = require('../../../tools/composed-contrast.js');

/**
 * THE COLLAPSE FLOOR IS PER-CONDITION, and it is the same split `tools/cvd-audit.js`
 * applies to this group: 0.15 where a dichromacy leaves lightness plus one chromatic
 * axis, 0.11 where a monochromacy leaves lightness alone.
 *
 * 0.11 is not a discount. It is what the palette BUILT for the condition reaches:
 * `a11y-achromatopsia`'s trio is a hand-curated value ramp, and 0.11 is the ratchet
 * just under its own minimum pairwise reading. Three tokens mutually >= 0.11 need
 * 0.22 of lightness range, which is why the crowded groups (twelve categorical fills,
 * eight chart hues) take the audit's lower 0.065 and this group does not — see
 * `2026-08-23-measurement-primitives-reach-the-reader.md` 3.1.
 */
const COLLAPSE_BY_TYPE = Object.freeze({ [ACHROMATOPSIA]: 0.11 });
const COLLAPSE_DEFAULT = 0.15;
const collapseFloor = (type) => COLLAPSE_BY_TYPE[type] ?? COLLAPSE_DEFAULT;
// Absorbs last-digit movement in the frozen table, nothing more. A real erosion
// in this repo's measurements is 0.01 upward; the ones #1704 caused were 0.07+.
const EROSION_TOLERANCE = 0.002;
const TRIO = ['pass', 'warn', 'fail'];
/**
 * All FOUR conditions, from `lib/theme/cvd.js` rather than re-listed, so this table
 * cannot silently stop covering one. The monochromacy arm was added when the trio was
 * respaced to clear its floor on all 32 palettes; before that, 162 of its 192 pairs
 * sat under 0.11 and nothing measured them.
 */
const TYPES = SIMULATED_TYPES;

/**
 * theme|mode|a^b|deficiency -> the HIGH-WATER OKLab distance under that deficiency.
 *
 * Not "today's measurement": `npm run palette:bless` is ratchet-only, so where a
 * change erodes a pair within tolerance the entry keeps the OLDER, larger value
 * and the tree scores below it. That is the strict direction — the floor never
 * relaxes — but it means an entry is an upper bound on the shipped separation,
 * not a reading of it. 73 entries are above the tree as of #1698.
 */
const CVD_FROZEN = new Map([
  ['a11y-achromatopsia|dark|pass^fail|achromatopsia', 0.1207],
  ['a11y-achromatopsia|dark|pass^fail|deuteranopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^fail|protanopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^fail|tritanopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^warn|achromatopsia', 0.1222],
  ['a11y-achromatopsia|dark|pass^warn|deuteranopia', 0.1222],
  ['a11y-achromatopsia|dark|pass^warn|protanopia', 0.1222],
  ['a11y-achromatopsia|dark|pass^warn|tritanopia', 0.1222],
  ['a11y-achromatopsia|dark|warn^fail|achromatopsia', 0.2429],
  ['a11y-achromatopsia|dark|warn^fail|deuteranopia', 0.2429],
  ['a11y-achromatopsia|dark|warn^fail|protanopia', 0.2429],
  ['a11y-achromatopsia|dark|warn^fail|tritanopia', 0.2429],
  ['a11y-achromatopsia|light|pass^fail|achromatopsia', 0.1230],
  ['a11y-achromatopsia|light|pass^fail|deuteranopia', 0.1230],
  ['a11y-achromatopsia|light|pass^fail|protanopia', 0.1230],
  ['a11y-achromatopsia|light|pass^fail|tritanopia', 0.1230],
  ['a11y-achromatopsia|light|pass^warn|achromatopsia', 0.1179],
  ['a11y-achromatopsia|light|pass^warn|deuteranopia', 0.1179],
  ['a11y-achromatopsia|light|pass^warn|protanopia', 0.1179],
  ['a11y-achromatopsia|light|pass^warn|tritanopia', 0.1179],
  ['a11y-achromatopsia|light|warn^fail|achromatopsia', 0.2410],
  ['a11y-achromatopsia|light|warn^fail|deuteranopia', 0.2410],
  ['a11y-achromatopsia|light|warn^fail|protanopia', 0.2410],
  ['a11y-achromatopsia|light|warn^fail|tritanopia', 0.2410],
  ['a11y-base|dark|pass^fail|achromatopsia', 0.2399],
  ['a11y-base|dark|pass^fail|deuteranopia', 0.2037],
  ['a11y-base|dark|pass^fail|protanopia', 0.3030],
  ['a11y-base|dark|pass^fail|tritanopia', 0.3249],
  ['a11y-base|dark|pass^warn|achromatopsia', 0.1208],
  ['a11y-base|dark|pass^warn|deuteranopia', 0.1132],
  ['a11y-base|dark|pass^warn|protanopia', 0.1664],
  ['a11y-base|dark|pass^warn|tritanopia', 0.2130],
  ['a11y-base|dark|warn^fail|achromatopsia', 0.1190],
  ['a11y-base|dark|warn^fail|deuteranopia', 0.1278],
  ['a11y-base|dark|warn^fail|protanopia', 0.1669],
  ['a11y-base|dark|warn^fail|tritanopia', 0.1235],
  ['a11y-base|light|pass^fail|achromatopsia', 0.1195],
  ['a11y-base|light|pass^fail|deuteranopia', 0.0889],
  ['a11y-base|light|pass^fail|protanopia', 0.1755],
  ['a11y-base|light|pass^fail|tritanopia', 0.2445],
  ['a11y-base|light|pass^warn|achromatopsia', 0.1175],
  ['a11y-base|light|pass^warn|deuteranopia', 0.1538],
  ['a11y-base|light|pass^warn|protanopia', 0.0983],
  ['a11y-base|light|pass^warn|tritanopia', 0.1999],
  ['a11y-base|light|warn^fail|achromatopsia', 0.2370],
  ['a11y-base|light|warn^fail|deuteranopia', 0.2334],
  ['a11y-base|light|warn^fail|protanopia', 0.2701],
  ['a11y-base|light|warn^fail|tritanopia', 0.2152],
  ['a11y-deuteranopia|dark|pass^fail|achromatopsia', 0.1190],
  ['a11y-deuteranopia|dark|pass^fail|deuteranopia', 0.2006],
  ['a11y-deuteranopia|dark|pass^fail|protanopia', 0.2367],
  ['a11y-deuteranopia|dark|pass^fail|tritanopia', 0.3204],
  ['a11y-deuteranopia|dark|pass^warn|achromatopsia', 0.1208],
  ['a11y-deuteranopia|dark|pass^warn|deuteranopia', 0.2436],
  ['a11y-deuteranopia|dark|pass^warn|protanopia', 0.1905],
  ['a11y-deuteranopia|dark|pass^warn|tritanopia', 0.2149],
  ['a11y-deuteranopia|dark|warn^fail|achromatopsia', 0.2399],
  ['a11y-deuteranopia|dark|warn^fail|deuteranopia', 0.2193],
  ['a11y-deuteranopia|dark|warn^fail|protanopia', 0.2763],
  ['a11y-deuteranopia|dark|warn^fail|tritanopia', 0.2540],
  ['a11y-deuteranopia|light|pass^fail|achromatopsia', 0.1200],
  ['a11y-deuteranopia|light|pass^fail|deuteranopia', 0.1953],
  ['a11y-deuteranopia|light|pass^fail|protanopia', 0.2400],
  ['a11y-deuteranopia|light|pass^fail|tritanopia', 0.2370],
  ['a11y-deuteranopia|light|pass^warn|achromatopsia', 0.1221],
  ['a11y-deuteranopia|light|pass^warn|deuteranopia', 0.2759],
  ['a11y-deuteranopia|light|pass^warn|protanopia', 0.2200],
  ['a11y-deuteranopia|light|pass^warn|tritanopia', 0.2130],
  ['a11y-deuteranopia|light|warn^fail|achromatopsia', 0.2422],
  ['a11y-deuteranopia|light|warn^fail|deuteranopia', 0.2350],
  ['a11y-deuteranopia|light|warn^fail|protanopia', 0.2761],
  ['a11y-deuteranopia|light|warn^fail|tritanopia', 0.2138],
  ['a11y-protanopia|dark|pass^fail|achromatopsia', 0.1190],
  ['a11y-protanopia|dark|pass^fail|deuteranopia', 0.2006],
  ['a11y-protanopia|dark|pass^fail|protanopia', 0.2367],
  ['a11y-protanopia|dark|pass^fail|tritanopia', 0.3204],
  ['a11y-protanopia|dark|pass^warn|achromatopsia', 0.1208],
  ['a11y-protanopia|dark|pass^warn|deuteranopia', 0.2436],
  ['a11y-protanopia|dark|pass^warn|protanopia', 0.1905],
  ['a11y-protanopia|dark|pass^warn|tritanopia', 0.2149],
  ['a11y-protanopia|dark|warn^fail|achromatopsia', 0.2399],
  ['a11y-protanopia|dark|warn^fail|deuteranopia', 0.2193],
  ['a11y-protanopia|dark|warn^fail|protanopia', 0.2763],
  ['a11y-protanopia|dark|warn^fail|tritanopia', 0.2540],
  ['a11y-protanopia|light|pass^fail|achromatopsia', 0.1200],
  ['a11y-protanopia|light|pass^fail|deuteranopia', 0.1953],
  ['a11y-protanopia|light|pass^fail|protanopia', 0.2400],
  ['a11y-protanopia|light|pass^fail|tritanopia', 0.2370],
  ['a11y-protanopia|light|pass^warn|achromatopsia', 0.1221],
  ['a11y-protanopia|light|pass^warn|deuteranopia', 0.2759],
  ['a11y-protanopia|light|pass^warn|protanopia', 0.2200],
  ['a11y-protanopia|light|pass^warn|tritanopia', 0.2130],
  ['a11y-protanopia|light|warn^fail|achromatopsia', 0.2422],
  ['a11y-protanopia|light|warn^fail|deuteranopia', 0.2350],
  ['a11y-protanopia|light|warn^fail|protanopia', 0.2761],
  ['a11y-protanopia|light|warn^fail|tritanopia', 0.2138],
  ['a11y-tritanopia|dark|pass^fail|achromatopsia', 0.1291],
  ['a11y-tritanopia|dark|pass^fail|deuteranopia', 0.1838],
  ['a11y-tritanopia|dark|pass^fail|protanopia', 0.2296],
  ['a11y-tritanopia|dark|pass^fail|tritanopia', 0.2371],
  ['a11y-tritanopia|dark|pass^warn|achromatopsia', 0.2702],
  ['a11y-tritanopia|dark|pass^warn|deuteranopia', 0.2328],
  ['a11y-tritanopia|dark|pass^warn|protanopia', 0.3271],
  ['a11y-tritanopia|dark|pass^warn|tritanopia', 0.3532],
  ['a11y-tritanopia|dark|warn^fail|achromatopsia', 0.1410],
  ['a11y-tritanopia|dark|warn^fail|deuteranopia', 0.2226],
  ['a11y-tritanopia|dark|warn^fail|protanopia', 0.2513],
  ['a11y-tritanopia|dark|warn^fail|tritanopia', 0.1902],
  ['a11y-tritanopia|light|pass^fail|achromatopsia', 0.1405],
  ['a11y-tritanopia|light|pass^fail|deuteranopia', 0.1606],
  ['a11y-tritanopia|light|pass^fail|protanopia', 0.2477],
  ['a11y-tritanopia|light|pass^fail|tritanopia', 0.2253],
  ['a11y-tritanopia|light|pass^warn|achromatopsia', 0.1221],
  ['a11y-tritanopia|light|pass^warn|deuteranopia', 0.1612],
  ['a11y-tritanopia|light|pass^warn|protanopia', 0.0637],
  ['a11y-tritanopia|light|pass^warn|tritanopia', 0.2793],
  ['a11y-tritanopia|light|warn^fail|achromatopsia', 0.2626],
  ['a11y-tritanopia|light|warn^fail|deuteranopia', 0.3010],
  ['a11y-tritanopia|light|warn^fail|protanopia', 0.2755],
  ['a11y-tritanopia|light|warn^fail|tritanopia', 0.2736],
  ['ardesia-dark|dark|pass^fail|achromatopsia', 0.2401],
  ['ardesia-dark|dark|pass^fail|deuteranopia', 0.2019],
  ['ardesia-dark|dark|pass^fail|protanopia', 0.3032],
  ['ardesia-dark|dark|pass^fail|tritanopia', 0.3317],
  ['ardesia-dark|dark|pass^warn|achromatopsia', 0.1194],
  ['ardesia-dark|dark|pass^warn|deuteranopia', 0.1336],
  ['ardesia-dark|dark|pass^warn|protanopia', 0.1778],
  ['ardesia-dark|dark|pass^warn|tritanopia', 0.2364],
  ['ardesia-dark|dark|warn^fail|achromatopsia', 0.1206],
  ['ardesia-dark|dark|warn^fail|deuteranopia', 0.1394],
  ['ardesia-dark|dark|warn^fail|protanopia', 0.1843],
  ['ardesia-dark|dark|warn^fail|tritanopia', 0.1309],
  ['ardesia-dark|light|pass^fail|achromatopsia', 0.1207],
  ['ardesia-dark|light|pass^fail|deuteranopia', 0.0923],
  ['ardesia-dark|light|pass^fail|protanopia', 0.1769],
  ['ardesia-dark|light|pass^fail|tritanopia', 0.2538],
  ['ardesia-dark|light|pass^warn|achromatopsia', 0.1183],
  ['ardesia-dark|light|pass^warn|deuteranopia', 0.1588],
  ['ardesia-dark|light|pass^warn|protanopia', 0.1021],
  ['ardesia-dark|light|pass^warn|tritanopia', 0.2001],
  ['ardesia-dark|light|warn^fail|achromatopsia', 0.2390],
  ['ardesia-dark|light|warn^fail|deuteranopia', 0.2386],
  ['ardesia-dark|light|warn^fail|protanopia', 0.2725],
  ['ardesia-dark|light|warn^fail|tritanopia', 0.2165],
  ['ardesia|dark|pass^fail|achromatopsia', 0.2401],
  ['ardesia|dark|pass^fail|deuteranopia', 0.2019],
  ['ardesia|dark|pass^fail|protanopia', 0.3032],
  ['ardesia|dark|pass^fail|tritanopia', 0.3317],
  ['ardesia|dark|pass^warn|achromatopsia', 0.1194],
  ['ardesia|dark|pass^warn|deuteranopia', 0.1336],
  ['ardesia|dark|pass^warn|protanopia', 0.1778],
  ['ardesia|dark|pass^warn|tritanopia', 0.2364],
  ['ardesia|dark|warn^fail|achromatopsia', 0.1206],
  ['ardesia|dark|warn^fail|deuteranopia', 0.1394],
  ['ardesia|dark|warn^fail|protanopia', 0.1843],
  ['ardesia|dark|warn^fail|tritanopia', 0.1309],
  ['ardesia|light|pass^fail|achromatopsia', 0.1207],
  ['ardesia|light|pass^fail|deuteranopia', 0.0923],
  ['ardesia|light|pass^fail|protanopia', 0.1769],
  ['ardesia|light|pass^fail|tritanopia', 0.2538],
  ['ardesia|light|pass^warn|achromatopsia', 0.1183],
  ['ardesia|light|pass^warn|deuteranopia', 0.1588],
  ['ardesia|light|pass^warn|protanopia', 0.1021],
  ['ardesia|light|pass^warn|tritanopia', 0.2001],
  ['ardesia|light|warn^fail|achromatopsia', 0.2390],
  ['ardesia|light|warn^fail|deuteranopia', 0.2386],
  ['ardesia|light|warn^fail|protanopia', 0.2725],
  ['ardesia|light|warn^fail|tritanopia', 0.2165],
  ['atelier-dark|dark|pass^fail|achromatopsia', 0.1200],
  ['atelier-dark|dark|pass^fail|deuteranopia', 0.1142],
  ['atelier-dark|dark|pass^fail|protanopia', 0.1984],
  ['atelier-dark|dark|pass^fail|tritanopia', 0.2650],
  ['atelier-dark|dark|pass^warn|achromatopsia', 0.2415],
  ['atelier-dark|dark|pass^warn|deuteranopia', 0.2104],
  ['atelier-dark|dark|pass^warn|protanopia', 0.2835],
  ['atelier-dark|dark|pass^warn|tritanopia', 0.3094],
  ['atelier-dark|dark|warn^fail|achromatopsia', 0.1214],
  ['atelier-dark|dark|warn^fail|deuteranopia', 0.1511],
  ['atelier-dark|dark|warn^fail|protanopia', 0.1667],
  ['atelier-dark|dark|warn^fail|tritanopia', 0.1089],
  ['atelier-dark|light|pass^fail|achromatopsia', 0.1195],
  ['atelier-dark|light|pass^fail|deuteranopia', 0.0897],
  ['atelier-dark|light|pass^fail|protanopia', 0.1818],
  ['atelier-dark|light|pass^fail|tritanopia', 0.2607],
  ['atelier-dark|light|pass^warn|achromatopsia', 0.1175],
  ['atelier-dark|light|pass^warn|deuteranopia', 0.1554],
  ['atelier-dark|light|pass^warn|protanopia', 0.0844],
  ['atelier-dark|light|pass^warn|tritanopia', 0.2244],
  ['atelier-dark|light|warn^fail|achromatopsia', 0.2370],
  ['atelier-dark|light|warn^fail|deuteranopia', 0.2344],
  ['atelier-dark|light|warn^fail|protanopia', 0.2618],
  ['atelier-dark|light|warn^fail|tritanopia', 0.2163],
  ['atelier|dark|pass^fail|achromatopsia', 0.1200],
  ['atelier|dark|pass^fail|deuteranopia', 0.1142],
  ['atelier|dark|pass^fail|protanopia', 0.1984],
  ['atelier|dark|pass^fail|tritanopia', 0.2650],
  ['atelier|dark|pass^warn|achromatopsia', 0.2415],
  ['atelier|dark|pass^warn|deuteranopia', 0.2104],
  ['atelier|dark|pass^warn|protanopia', 0.2835],
  ['atelier|dark|pass^warn|tritanopia', 0.3094],
  ['atelier|dark|warn^fail|achromatopsia', 0.1214],
  ['atelier|dark|warn^fail|deuteranopia', 0.1511],
  ['atelier|dark|warn^fail|protanopia', 0.1667],
  ['atelier|dark|warn^fail|tritanopia', 0.1089],
  ['atelier|light|pass^fail|achromatopsia', 0.1195],
  ['atelier|light|pass^fail|deuteranopia', 0.0897],
  ['atelier|light|pass^fail|protanopia', 0.1818],
  ['atelier|light|pass^fail|tritanopia', 0.2607],
  ['atelier|light|pass^warn|achromatopsia', 0.1175],
  ['atelier|light|pass^warn|deuteranopia', 0.1554],
  ['atelier|light|pass^warn|protanopia', 0.0844],
  ['atelier|light|pass^warn|tritanopia', 0.2244],
  ['atelier|light|warn^fail|achromatopsia', 0.2370],
  ['atelier|light|warn^fail|deuteranopia', 0.2344],
  ['atelier|light|warn^fail|protanopia', 0.2618],
  ['atelier|light|warn^fail|tritanopia', 0.2163],
  ['brina-dark|dark|pass^fail|achromatopsia', 0.2401],
  ['brina-dark|dark|pass^fail|deuteranopia', 0.2019],
  ['brina-dark|dark|pass^fail|protanopia', 0.3032],
  ['brina-dark|dark|pass^fail|tritanopia', 0.3317],
  ['brina-dark|dark|pass^warn|achromatopsia', 0.1194],
  ['brina-dark|dark|pass^warn|deuteranopia', 0.1336],
  ['brina-dark|dark|pass^warn|protanopia', 0.1778],
  ['brina-dark|dark|pass^warn|tritanopia', 0.2364],
  ['brina-dark|dark|warn^fail|achromatopsia', 0.1206],
  ['brina-dark|dark|warn^fail|deuteranopia', 0.1394],
  ['brina-dark|dark|warn^fail|protanopia', 0.1843],
  ['brina-dark|dark|warn^fail|tritanopia', 0.1309],
  ['brina-dark|light|pass^fail|achromatopsia', 0.1177],
  ['brina-dark|light|pass^fail|deuteranopia', 0.0935],
  ['brina-dark|light|pass^fail|protanopia', 0.1703],
  ['brina-dark|light|pass^fail|tritanopia', 0.2547],
  ['brina-dark|light|pass^warn|achromatopsia', 0.1227],
  ['brina-dark|light|pass^warn|deuteranopia', 0.1677],
  ['brina-dark|light|pass^warn|protanopia', 0.1128],
  ['brina-dark|light|pass^warn|tritanopia', 0.2005],
  ['brina-dark|light|warn^fail|achromatopsia', 0.2404],
  ['brina-dark|light|warn^fail|deuteranopia', 0.2398],
  ['brina-dark|light|warn^fail|protanopia', 0.2696],
  ['brina-dark|light|warn^fail|tritanopia', 0.2193],
  ['brina|dark|pass^fail|achromatopsia', 0.2401],
  ['brina|dark|pass^fail|deuteranopia', 0.2019],
  ['brina|dark|pass^fail|protanopia', 0.3032],
  ['brina|dark|pass^fail|tritanopia', 0.3317],
  ['brina|dark|pass^warn|achromatopsia', 0.1194],
  ['brina|dark|pass^warn|deuteranopia', 0.1336],
  ['brina|dark|pass^warn|protanopia', 0.1778],
  ['brina|dark|pass^warn|tritanopia', 0.2364],
  ['brina|dark|warn^fail|achromatopsia', 0.1206],
  ['brina|dark|warn^fail|deuteranopia', 0.1394],
  ['brina|dark|warn^fail|protanopia', 0.1843],
  ['brina|dark|warn^fail|tritanopia', 0.1309],
  ['brina|light|pass^fail|achromatopsia', 0.1177],
  ['brina|light|pass^fail|deuteranopia', 0.0935],
  ['brina|light|pass^fail|protanopia', 0.1703],
  ['brina|light|pass^fail|tritanopia', 0.2547],
  ['brina|light|pass^warn|achromatopsia', 0.1227],
  ['brina|light|pass^warn|deuteranopia', 0.1677],
  ['brina|light|pass^warn|protanopia', 0.1128],
  ['brina|light|pass^warn|tritanopia', 0.2005],
  ['brina|light|warn^fail|achromatopsia', 0.2404],
  ['brina|light|warn^fail|deuteranopia', 0.2398],
  ['brina|light|warn^fail|protanopia', 0.2696],
  ['brina|light|warn^fail|tritanopia', 0.2193],
  ['burgundy-dark|dark|pass^fail|achromatopsia', 0.2391],
  ['burgundy-dark|dark|pass^fail|deuteranopia', 0.2054],
  ['burgundy-dark|dark|pass^fail|protanopia', 0.3170],
  ['burgundy-dark|dark|pass^fail|tritanopia', 0.3387],
  ['burgundy-dark|dark|pass^warn|achromatopsia', 0.1173],
  ['burgundy-dark|dark|pass^warn|deuteranopia', 0.0915],
  ['burgundy-dark|dark|pass^warn|protanopia', 0.1649],
  ['burgundy-dark|dark|pass^warn|tritanopia', 0.2331],
  ['burgundy-dark|dark|warn^fail|achromatopsia', 0.1218],
  ['burgundy-dark|dark|warn^fail|deuteranopia', 0.1316],
  ['burgundy-dark|dark|warn^fail|protanopia', 0.1662],
  ['burgundy-dark|dark|warn^fail|tritanopia', 0.1142],
  ['burgundy-dark|light|pass^fail|achromatopsia', 0.1218],
  ['burgundy-dark|light|pass^fail|deuteranopia', 0.0920],
  ['burgundy-dark|light|pass^fail|protanopia', 0.1835],
  ['burgundy-dark|light|pass^fail|tritanopia', 0.2607],
  ['burgundy-dark|light|pass^warn|achromatopsia', 0.1198],
  ['burgundy-dark|light|pass^warn|deuteranopia', 0.1581],
  ['burgundy-dark|light|pass^warn|protanopia', 0.0882],
  ['burgundy-dark|light|pass^warn|tritanopia', 0.2275],
  ['burgundy-dark|light|warn^fail|achromatopsia', 0.2416],
  ['burgundy-dark|light|warn^fail|deuteranopia', 0.2379],
  ['burgundy-dark|light|warn^fail|protanopia', 0.2664],
  ['burgundy-dark|light|warn^fail|tritanopia', 0.2153],
  ['burgundy|dark|pass^fail|achromatopsia', 0.2391],
  ['burgundy|dark|pass^fail|deuteranopia', 0.2054],
  ['burgundy|dark|pass^fail|protanopia', 0.3170],
  ['burgundy|dark|pass^fail|tritanopia', 0.3387],
  ['burgundy|dark|pass^warn|achromatopsia', 0.1173],
  ['burgundy|dark|pass^warn|deuteranopia', 0.0915],
  ['burgundy|dark|pass^warn|protanopia', 0.1649],
  ['burgundy|dark|pass^warn|tritanopia', 0.2331],
  ['burgundy|dark|warn^fail|achromatopsia', 0.1218],
  ['burgundy|dark|warn^fail|deuteranopia', 0.1316],
  ['burgundy|dark|warn^fail|protanopia', 0.1662],
  ['burgundy|dark|warn^fail|tritanopia', 0.1142],
  ['burgundy|light|pass^fail|achromatopsia', 0.1218],
  ['burgundy|light|pass^fail|deuteranopia', 0.0920],
  ['burgundy|light|pass^fail|protanopia', 0.1835],
  ['burgundy|light|pass^fail|tritanopia', 0.2607],
  ['burgundy|light|pass^warn|achromatopsia', 0.1198],
  ['burgundy|light|pass^warn|deuteranopia', 0.1581],
  ['burgundy|light|pass^warn|protanopia', 0.0882],
  ['burgundy|light|pass^warn|tritanopia', 0.2275],
  ['burgundy|light|warn^fail|achromatopsia', 0.2416],
  ['burgundy|light|warn^fail|deuteranopia', 0.2379],
  ['burgundy|light|warn^fail|protanopia', 0.2664],
  ['burgundy|light|warn^fail|tritanopia', 0.2153],
  ['carbone|dark|pass^fail|achromatopsia', 0.1200],
  ['carbone|dark|pass^fail|deuteranopia', 0.0898],
  ['carbone|dark|pass^fail|protanopia', 0.1825],
  ['carbone|dark|pass^fail|tritanopia', 0.2982],
  ['carbone|dark|pass^warn|achromatopsia', 0.2415],
  ['carbone|dark|pass^warn|deuteranopia', 0.2040],
  ['carbone|dark|pass^warn|protanopia', 0.3219],
  ['carbone|dark|pass^warn|tritanopia', 0.3908],
  ['carbone|dark|warn^fail|achromatopsia', 0.1214],
  ['carbone|dark|warn^fail|deuteranopia', 0.1465],
  ['carbone|dark|warn^fail|protanopia', 0.1867],
  ['carbone|dark|warn^fail|tritanopia', 0.1546],
  ['carbone|light|pass^fail|achromatopsia', 0.1197],
  ['carbone|light|pass^fail|deuteranopia', 0.0876],
  ['carbone|light|pass^fail|protanopia', 0.1975],
  ['carbone|light|pass^fail|tritanopia', 0.2807],
  ['carbone|light|pass^warn|achromatopsia', 0.1202],
  ['carbone|light|pass^warn|deuteranopia', 0.1765],
  ['carbone|light|pass^warn|protanopia', 0.0716],
  ['carbone|light|pass^warn|tritanopia', 0.3016],
  ['carbone|light|warn^fail|achromatopsia', 0.2399],
  ['carbone|light|warn^fail|deuteranopia', 0.2385],
  ['carbone|light|warn^fail|protanopia', 0.2582],
  ['carbone|light|warn^fail|tritanopia', 0.2223],
  ['carta-dark|dark|pass^fail|achromatopsia', 0.2415],
  ['carta-dark|dark|pass^fail|deuteranopia', 0.1972],
  ['carta-dark|dark|pass^fail|protanopia', 0.3252],
  ['carta-dark|dark|pass^fail|tritanopia', 0.3667],
  ['carta-dark|dark|pass^warn|achromatopsia', 0.1200],
  ['carta-dark|dark|pass^warn|deuteranopia', 0.1020],
  ['carta-dark|dark|pass^warn|protanopia', 0.1575],
  ['carta-dark|dark|pass^warn|tritanopia', 0.2060],
  ['carta-dark|dark|warn^fail|achromatopsia', 0.1214],
  ['carta-dark|dark|warn^fail|deuteranopia', 0.1174],
  ['carta-dark|dark|warn^fail|protanopia', 0.1865],
  ['carta-dark|dark|warn^fail|tritanopia', 0.1663],
  ['carta-dark|light|pass^fail|achromatopsia', 0.1207],
  ['carta-dark|light|pass^fail|deuteranopia', 0.0940],
  ['carta-dark|light|pass^fail|protanopia', 0.1922],
  ['carta-dark|light|pass^fail|tritanopia', 0.2272],
  ['carta-dark|light|pass^warn|achromatopsia', 0.1183],
  ['carta-dark|light|pass^warn|deuteranopia', 0.1422],
  ['carta-dark|light|pass^warn|protanopia', 0.0906],
  ['carta-dark|light|pass^warn|tritanopia', 0.1950],
  ['carta-dark|light|warn^fail|achromatopsia', 0.2390],
  ['carta-dark|light|warn^fail|deuteranopia', 0.2363],
  ['carta-dark|light|warn^fail|protanopia', 0.2703],
  ['carta-dark|light|warn^fail|tritanopia', 0.2174],
  ['carta|dark|pass^fail|achromatopsia', 0.2415],
  ['carta|dark|pass^fail|deuteranopia', 0.1972],
  ['carta|dark|pass^fail|protanopia', 0.3252],
  ['carta|dark|pass^fail|tritanopia', 0.3667],
  ['carta|dark|pass^warn|achromatopsia', 0.1200],
  ['carta|dark|pass^warn|deuteranopia', 0.1020],
  ['carta|dark|pass^warn|protanopia', 0.1575],
  ['carta|dark|pass^warn|tritanopia', 0.2060],
  ['carta|dark|warn^fail|achromatopsia', 0.1214],
  ['carta|dark|warn^fail|deuteranopia', 0.1174],
  ['carta|dark|warn^fail|protanopia', 0.1865],
  ['carta|dark|warn^fail|tritanopia', 0.1663],
  ['carta|light|pass^fail|achromatopsia', 0.1207],
  ['carta|light|pass^fail|deuteranopia', 0.0940],
  ['carta|light|pass^fail|protanopia', 0.1922],
  ['carta|light|pass^fail|tritanopia', 0.2272],
  ['carta|light|pass^warn|achromatopsia', 0.1183],
  ['carta|light|pass^warn|deuteranopia', 0.1422],
  ['carta|light|pass^warn|protanopia', 0.0906],
  ['carta|light|pass^warn|tritanopia', 0.1950],
  ['carta|light|warn^fail|achromatopsia', 0.2390],
  ['carta|light|warn^fail|deuteranopia', 0.2363],
  ['carta|light|warn^fail|protanopia', 0.2703],
  ['carta|light|warn^fail|tritanopia', 0.2174],
  ['concrete-dark|dark|pass^fail|achromatopsia', 0.2424],
  ['concrete-dark|dark|pass^fail|deuteranopia', 0.2087],
  ['concrete-dark|dark|pass^fail|protanopia', 0.2900],
  ['concrete-dark|dark|pass^fail|tritanopia', 0.3048],
  ['concrete-dark|dark|pass^warn|achromatopsia', 0.1221],
  ['concrete-dark|dark|pass^warn|deuteranopia', 0.1305],
  ['concrete-dark|dark|pass^warn|protanopia', 0.1694],
  ['concrete-dark|dark|pass^warn|tritanopia', 0.1889],
  ['concrete-dark|dark|warn^fail|achromatopsia', 0.1203],
  ['concrete-dark|dark|warn^fail|deuteranopia', 0.1287],
  ['concrete-dark|dark|warn^fail|protanopia', 0.1647],
  ['concrete-dark|dark|warn^fail|tritanopia', 0.1242],
  ['concrete-dark|light|pass^fail|achromatopsia', 0.2408],
  ['concrete-dark|light|pass^fail|deuteranopia', 0.2794],
  ['concrete-dark|light|pass^fail|protanopia', 0.1680],
  ['concrete-dark|light|pass^fail|tritanopia', 0.3524],
  ['concrete-dark|light|pass^warn|achromatopsia', 0.1190],
  ['concrete-dark|light|pass^warn|deuteranopia', 0.1350],
  ['concrete-dark|light|pass^warn|protanopia', 0.1009],
  ['concrete-dark|light|pass^warn|tritanopia', 0.1568],
  ['concrete-dark|light|warn^fail|achromatopsia', 0.1218],
  ['concrete-dark|light|warn^fail|deuteranopia', 0.1445],
  ['concrete-dark|light|warn^fail|protanopia', 0.0678],
  ['concrete-dark|light|warn^fail|tritanopia', 0.1965],
  ['concrete|dark|pass^fail|achromatopsia', 0.2424],
  ['concrete|dark|pass^fail|deuteranopia', 0.2087],
  ['concrete|dark|pass^fail|protanopia', 0.2900],
  ['concrete|dark|pass^fail|tritanopia', 0.3048],
  ['concrete|dark|pass^warn|achromatopsia', 0.1221],
  ['concrete|dark|pass^warn|deuteranopia', 0.1305],
  ['concrete|dark|pass^warn|protanopia', 0.1694],
  ['concrete|dark|pass^warn|tritanopia', 0.1889],
  ['concrete|dark|warn^fail|achromatopsia', 0.1203],
  ['concrete|dark|warn^fail|deuteranopia', 0.1287],
  ['concrete|dark|warn^fail|protanopia', 0.1647],
  ['concrete|dark|warn^fail|tritanopia', 0.1242],
  ['concrete|light|pass^fail|achromatopsia', 0.2408],
  ['concrete|light|pass^fail|deuteranopia', 0.2794],
  ['concrete|light|pass^fail|protanopia', 0.1680],
  ['concrete|light|pass^fail|tritanopia', 0.3524],
  ['concrete|light|pass^warn|achromatopsia', 0.1190],
  ['concrete|light|pass^warn|deuteranopia', 0.1350],
  ['concrete|light|pass^warn|protanopia', 0.1009],
  ['concrete|light|pass^warn|tritanopia', 0.1568],
  ['concrete|light|warn^fail|achromatopsia', 0.1218],
  ['concrete|light|warn^fail|deuteranopia', 0.1445],
  ['concrete|light|warn^fail|protanopia', 0.0678],
  ['concrete|light|warn^fail|tritanopia', 0.1965],
  ['crepuscolo-dark|dark|pass^fail|achromatopsia', 0.1173],
  ['crepuscolo-dark|dark|pass^fail|deuteranopia', 0.1109],
  ['crepuscolo-dark|dark|pass^fail|protanopia', 0.2008],
  ['crepuscolo-dark|dark|pass^fail|tritanopia', 0.2650],
  ['crepuscolo-dark|dark|pass^warn|achromatopsia', 0.2391],
  ['crepuscolo-dark|dark|pass^warn|deuteranopia', 0.2080],
  ['crepuscolo-dark|dark|pass^warn|protanopia', 0.2817],
  ['crepuscolo-dark|dark|pass^warn|tritanopia', 0.3034],
  ['crepuscolo-dark|dark|warn^fail|achromatopsia', 0.1218],
  ['crepuscolo-dark|dark|warn^fail|deuteranopia', 0.1497],
  ['crepuscolo-dark|dark|warn^fail|protanopia', 0.1627],
  ['crepuscolo-dark|dark|warn^fail|tritanopia', 0.1052],
  ['crepuscolo-dark|light|pass^fail|achromatopsia', 0.1218],
  ['crepuscolo-dark|light|pass^fail|deuteranopia', 0.0920],
  ['crepuscolo-dark|light|pass^fail|protanopia', 0.1835],
  ['crepuscolo-dark|light|pass^fail|tritanopia', 0.2607],
  ['crepuscolo-dark|light|pass^warn|achromatopsia', 0.1198],
  ['crepuscolo-dark|light|pass^warn|deuteranopia', 0.1581],
  ['crepuscolo-dark|light|pass^warn|protanopia', 0.0882],
  ['crepuscolo-dark|light|pass^warn|tritanopia', 0.2275],
  ['crepuscolo-dark|light|warn^fail|achromatopsia', 0.2416],
  ['crepuscolo-dark|light|warn^fail|deuteranopia', 0.2379],
  ['crepuscolo-dark|light|warn^fail|protanopia', 0.2664],
  ['crepuscolo-dark|light|warn^fail|tritanopia', 0.2153],
  ['crepuscolo|dark|pass^fail|achromatopsia', 0.1173],
  ['crepuscolo|dark|pass^fail|deuteranopia', 0.1109],
  ['crepuscolo|dark|pass^fail|protanopia', 0.2008],
  ['crepuscolo|dark|pass^fail|tritanopia', 0.2650],
  ['crepuscolo|dark|pass^warn|achromatopsia', 0.2391],
  ['crepuscolo|dark|pass^warn|deuteranopia', 0.2080],
  ['crepuscolo|dark|pass^warn|protanopia', 0.2817],
  ['crepuscolo|dark|pass^warn|tritanopia', 0.3034],
  ['crepuscolo|dark|warn^fail|achromatopsia', 0.1218],
  ['crepuscolo|dark|warn^fail|deuteranopia', 0.1497],
  ['crepuscolo|dark|warn^fail|protanopia', 0.1627],
  ['crepuscolo|dark|warn^fail|tritanopia', 0.1052],
  ['crepuscolo|light|pass^fail|achromatopsia', 0.1218],
  ['crepuscolo|light|pass^fail|deuteranopia', 0.0920],
  ['crepuscolo|light|pass^fail|protanopia', 0.1835],
  ['crepuscolo|light|pass^fail|tritanopia', 0.2607],
  ['crepuscolo|light|pass^warn|achromatopsia', 0.1198],
  ['crepuscolo|light|pass^warn|deuteranopia', 0.1581],
  ['crepuscolo|light|pass^warn|protanopia', 0.0882],
  ['crepuscolo|light|pass^warn|tritanopia', 0.2275],
  ['crepuscolo|light|warn^fail|achromatopsia', 0.2416],
  ['crepuscolo|light|warn^fail|deuteranopia', 0.2379],
  ['crepuscolo|light|warn^fail|protanopia', 0.2664],
  ['crepuscolo|light|warn^fail|tritanopia', 0.2153],
  ['cuoio-dark|dark|pass^fail|achromatopsia', 0.2406],
  ['cuoio-dark|dark|pass^fail|deuteranopia', 0.1982],
  ['cuoio-dark|dark|pass^fail|protanopia', 0.3280],
  ['cuoio-dark|dark|pass^fail|tritanopia', 0.3625],
  ['cuoio-dark|dark|pass^warn|achromatopsia', 0.1211],
  ['cuoio-dark|dark|pass^warn|deuteranopia', 0.0888],
  ['cuoio-dark|dark|pass^warn|protanopia', 0.1722],
  ['cuoio-dark|dark|pass^warn|tritanopia', 0.2457],
  ['cuoio-dark|dark|warn^fail|achromatopsia', 0.1194],
  ['cuoio-dark|dark|warn^fail|deuteranopia', 0.1210],
  ['cuoio-dark|dark|warn^fail|protanopia', 0.1639],
  ['cuoio-dark|dark|warn^fail|tritanopia', 0.1243],
  ['cuoio-dark|light|pass^fail|achromatopsia', 0.2106],
  ['cuoio-dark|light|pass^fail|deuteranopia', 0.2596],
  ['cuoio-dark|light|pass^fail|protanopia', 0.1388],
  ['cuoio-dark|light|pass^fail|tritanopia', 0.3313],
  ['cuoio-dark|light|pass^warn|achromatopsia', 0.3312],
  ['cuoio-dark|light|pass^warn|deuteranopia', 0.3614],
  ['cuoio-dark|light|pass^warn|protanopia', 0.3100],
  ['cuoio-dark|light|pass^warn|tritanopia', 0.3652],
  ['cuoio-dark|light|warn^fail|achromatopsia', 0.1206],
  ['cuoio-dark|light|warn^fail|deuteranopia', 0.1019],
  ['cuoio-dark|light|warn^fail|protanopia', 0.1711],
  ['cuoio-dark|light|warn^fail|tritanopia', 0.1097],
  ['cuoio|dark|pass^fail|achromatopsia', 0.2406],
  ['cuoio|dark|pass^fail|deuteranopia', 0.1982],
  ['cuoio|dark|pass^fail|protanopia', 0.3280],
  ['cuoio|dark|pass^fail|tritanopia', 0.3625],
  ['cuoio|dark|pass^warn|achromatopsia', 0.1211],
  ['cuoio|dark|pass^warn|deuteranopia', 0.0888],
  ['cuoio|dark|pass^warn|protanopia', 0.1722],
  ['cuoio|dark|pass^warn|tritanopia', 0.2457],
  ['cuoio|dark|warn^fail|achromatopsia', 0.1194],
  ['cuoio|dark|warn^fail|deuteranopia', 0.1210],
  ['cuoio|dark|warn^fail|protanopia', 0.1639],
  ['cuoio|dark|warn^fail|tritanopia', 0.1243],
  ['cuoio|light|pass^fail|achromatopsia', 0.2106],
  ['cuoio|light|pass^fail|deuteranopia', 0.2596],
  ['cuoio|light|pass^fail|protanopia', 0.1388],
  ['cuoio|light|pass^fail|tritanopia', 0.3313],
  ['cuoio|light|pass^warn|achromatopsia', 0.3312],
  ['cuoio|light|pass^warn|deuteranopia', 0.3614],
  ['cuoio|light|pass^warn|protanopia', 0.3100],
  ['cuoio|light|pass^warn|tritanopia', 0.3652],
  ['cuoio|light|warn^fail|achromatopsia', 0.1206],
  ['cuoio|light|warn^fail|deuteranopia', 0.1019],
  ['cuoio|light|warn^fail|protanopia', 0.1711],
  ['cuoio|light|warn^fail|tritanopia', 0.1097],
  ['indaco-dark|dark|pass^fail|achromatopsia', 0.2415],
  ['indaco-dark|dark|pass^fail|deuteranopia', 0.2158],
  ['indaco-dark|dark|pass^fail|protanopia', 0.3228],
  ['indaco-dark|dark|pass^fail|tritanopia', 0.3335],
  ['indaco-dark|dark|pass^warn|achromatopsia', 0.1200],
  ['indaco-dark|dark|pass^warn|deuteranopia', 0.0952],
  ['indaco-dark|dark|pass^warn|protanopia', 0.1555],
  ['indaco-dark|dark|pass^warn|tritanopia', 0.2150],
  ['indaco-dark|dark|warn^fail|achromatopsia', 0.1214],
  ['indaco-dark|dark|warn^fail|deuteranopia', 0.1383],
  ['indaco-dark|dark|warn^fail|protanopia', 0.1827],
  ['indaco-dark|dark|warn^fail|tritanopia', 0.1284],
  ['indaco-dark|light|pass^fail|achromatopsia', 0.1218],
  ['indaco-dark|light|pass^fail|deuteranopia', 0.0939],
  ['indaco-dark|light|pass^fail|protanopia', 0.1917],
  ['indaco-dark|light|pass^fail|tritanopia', 0.2633],
  ['indaco-dark|light|pass^warn|achromatopsia', 0.1198],
  ['indaco-dark|light|pass^warn|deuteranopia', 0.1409],
  ['indaco-dark|light|pass^warn|protanopia', 0.0854],
  ['indaco-dark|light|pass^warn|tritanopia', 0.2019],
  ['indaco-dark|light|warn^fail|achromatopsia', 0.2416],
  ['indaco-dark|light|warn^fail|deuteranopia', 0.2347],
  ['indaco-dark|light|warn^fail|protanopia', 0.2763],
  ['indaco-dark|light|warn^fail|tritanopia', 0.2162],
  ['indaco|dark|pass^fail|achromatopsia', 0.2415],
  ['indaco|dark|pass^fail|deuteranopia', 0.2158],
  ['indaco|dark|pass^fail|protanopia', 0.3228],
  ['indaco|dark|pass^fail|tritanopia', 0.3335],
  ['indaco|dark|pass^warn|achromatopsia', 0.1200],
  ['indaco|dark|pass^warn|deuteranopia', 0.0952],
  ['indaco|dark|pass^warn|protanopia', 0.1555],
  ['indaco|dark|pass^warn|tritanopia', 0.2150],
  ['indaco|dark|warn^fail|achromatopsia', 0.1214],
  ['indaco|dark|warn^fail|deuteranopia', 0.1383],
  ['indaco|dark|warn^fail|protanopia', 0.1827],
  ['indaco|dark|warn^fail|tritanopia', 0.1284],
  ['indaco|light|pass^fail|achromatopsia', 0.1218],
  ['indaco|light|pass^fail|deuteranopia', 0.0939],
  ['indaco|light|pass^fail|protanopia', 0.1917],
  ['indaco|light|pass^fail|tritanopia', 0.2633],
  ['indaco|light|pass^warn|achromatopsia', 0.1198],
  ['indaco|light|pass^warn|deuteranopia', 0.1409],
  ['indaco|light|pass^warn|protanopia', 0.0854],
  ['indaco|light|pass^warn|tritanopia', 0.2019],
  ['indaco|light|warn^fail|achromatopsia', 0.2416],
  ['indaco|light|warn^fail|deuteranopia', 0.2347],
  ['indaco|light|warn^fail|protanopia', 0.2763],
  ['indaco|light|warn^fail|tritanopia', 0.2162],
  ['laguna-dark|dark|pass^fail|achromatopsia', 0.2401],
  ['laguna-dark|dark|pass^fail|deuteranopia', 0.2019],
  ['laguna-dark|dark|pass^fail|protanopia', 0.3032],
  ['laguna-dark|dark|pass^fail|tritanopia', 0.3317],
  ['laguna-dark|dark|pass^warn|achromatopsia', 0.1194],
  ['laguna-dark|dark|pass^warn|deuteranopia', 0.1336],
  ['laguna-dark|dark|pass^warn|protanopia', 0.1778],
  ['laguna-dark|dark|pass^warn|tritanopia', 0.2364],
  ['laguna-dark|dark|warn^fail|achromatopsia', 0.1206],
  ['laguna-dark|dark|warn^fail|deuteranopia', 0.1394],
  ['laguna-dark|dark|warn^fail|protanopia', 0.1843],
  ['laguna-dark|dark|warn^fail|tritanopia', 0.1309],
  ['laguna-dark|light|pass^fail|achromatopsia', 0.1177],
  ['laguna-dark|light|pass^fail|deuteranopia', 0.0922],
  ['laguna-dark|light|pass^fail|protanopia', 0.1698],
  ['laguna-dark|light|pass^fail|tritanopia', 0.2588],
  ['laguna-dark|light|pass^warn|achromatopsia', 0.1227],
  ['laguna-dark|light|pass^warn|deuteranopia', 0.1650],
  ['laguna-dark|light|pass^warn|protanopia', 0.1105],
  ['laguna-dark|light|pass^warn|tritanopia', 0.2008],
  ['laguna-dark|light|warn^fail|achromatopsia', 0.2404],
  ['laguna-dark|light|warn^fail|deuteranopia', 0.2398],
  ['laguna-dark|light|warn^fail|protanopia', 0.2696],
  ['laguna-dark|light|warn^fail|tritanopia', 0.2193],
  ['laguna|dark|pass^fail|achromatopsia', 0.2401],
  ['laguna|dark|pass^fail|deuteranopia', 0.2019],
  ['laguna|dark|pass^fail|protanopia', 0.3032],
  ['laguna|dark|pass^fail|tritanopia', 0.3317],
  ['laguna|dark|pass^warn|achromatopsia', 0.1194],
  ['laguna|dark|pass^warn|deuteranopia', 0.1336],
  ['laguna|dark|pass^warn|protanopia', 0.1778],
  ['laguna|dark|pass^warn|tritanopia', 0.2364],
  ['laguna|dark|warn^fail|achromatopsia', 0.1206],
  ['laguna|dark|warn^fail|deuteranopia', 0.1394],
  ['laguna|dark|warn^fail|protanopia', 0.1843],
  ['laguna|dark|warn^fail|tritanopia', 0.1309],
  ['laguna|light|pass^fail|achromatopsia', 0.1177],
  ['laguna|light|pass^fail|deuteranopia', 0.0922],
  ['laguna|light|pass^fail|protanopia', 0.1698],
  ['laguna|light|pass^fail|tritanopia', 0.2588],
  ['laguna|light|pass^warn|achromatopsia', 0.1227],
  ['laguna|light|pass^warn|deuteranopia', 0.1650],
  ['laguna|light|pass^warn|protanopia', 0.1105],
  ['laguna|light|pass^warn|tritanopia', 0.2008],
  ['laguna|light|warn^fail|achromatopsia', 0.2404],
  ['laguna|light|warn^fail|deuteranopia', 0.2398],
  ['laguna|light|warn^fail|protanopia', 0.2696],
  ['laguna|light|warn^fail|tritanopia', 0.2193],
  ['magnolia-dark|dark|pass^fail|achromatopsia', 0.1197],
  ['magnolia-dark|dark|pass^fail|deuteranopia', 0.1461],
  ['magnolia-dark|dark|pass^fail|protanopia', 0.2194],
  ['magnolia-dark|dark|pass^fail|tritanopia', 0.2327],
  ['magnolia-dark|dark|pass^warn|achromatopsia', 0.2505],
  ['magnolia-dark|dark|pass^warn|deuteranopia', 0.2246],
  ['magnolia-dark|dark|pass^warn|protanopia', 0.2805],
  ['magnolia-dark|dark|pass^warn|tritanopia', 0.2865],
  ['magnolia-dark|dark|warn^fail|achromatopsia', 0.1308],
  ['magnolia-dark|dark|warn^fail|deuteranopia', 0.1815],
  ['magnolia-dark|dark|warn^fail|protanopia', 0.2089],
  ['magnolia-dark|dark|warn^fail|tritanopia', 0.1285],
  ['magnolia-dark|light|pass^fail|achromatopsia', 0.1187],
  ['magnolia-dark|light|pass^fail|deuteranopia', 0.0870],
  ['magnolia-dark|light|pass^fail|protanopia', 0.1837],
  ['magnolia-dark|light|pass^fail|tritanopia', 0.2145],
  ['magnolia-dark|light|pass^warn|achromatopsia', 0.1206],
  ['magnolia-dark|light|pass^warn|deuteranopia', 0.1611],
  ['magnolia-dark|light|pass^warn|protanopia', 0.0890],
  ['magnolia-dark|light|pass^warn|tritanopia', 0.2266],
  ['magnolia-dark|light|warn^fail|achromatopsia', 0.2393],
  ['magnolia-dark|light|warn^fail|deuteranopia', 0.2424],
  ['magnolia-dark|light|warn^fail|protanopia', 0.2709],
  ['magnolia-dark|light|warn^fail|tritanopia', 0.2198],
  ['magnolia|dark|pass^fail|achromatopsia', 0.1197],
  ['magnolia|dark|pass^fail|deuteranopia', 0.1461],
  ['magnolia|dark|pass^fail|protanopia', 0.2194],
  ['magnolia|dark|pass^fail|tritanopia', 0.2327],
  ['magnolia|dark|pass^warn|achromatopsia', 0.2505],
  ['magnolia|dark|pass^warn|deuteranopia', 0.2246],
  ['magnolia|dark|pass^warn|protanopia', 0.2805],
  ['magnolia|dark|pass^warn|tritanopia', 0.2865],
  ['magnolia|dark|warn^fail|achromatopsia', 0.1308],
  ['magnolia|dark|warn^fail|deuteranopia', 0.1815],
  ['magnolia|dark|warn^fail|protanopia', 0.2089],
  ['magnolia|dark|warn^fail|tritanopia', 0.1285],
  ['magnolia|light|pass^fail|achromatopsia', 0.1187],
  ['magnolia|light|pass^fail|deuteranopia', 0.0870],
  ['magnolia|light|pass^fail|protanopia', 0.1837],
  ['magnolia|light|pass^fail|tritanopia', 0.2145],
  ['magnolia|light|pass^warn|achromatopsia', 0.1206],
  ['magnolia|light|pass^warn|deuteranopia', 0.1611],
  ['magnolia|light|pass^warn|protanopia', 0.0890],
  ['magnolia|light|pass^warn|tritanopia', 0.2266],
  ['magnolia|light|warn^fail|achromatopsia', 0.2393],
  ['magnolia|light|warn^fail|deuteranopia', 0.2424],
  ['magnolia|light|warn^fail|protanopia', 0.2709],
  ['magnolia|light|warn^fail|tritanopia', 0.2198],
  ['mustard-dark|dark|pass^fail|achromatopsia', 0.2408],
  ['mustard-dark|dark|pass^fail|deuteranopia', 0.2042],
  ['mustard-dark|dark|pass^fail|protanopia', 0.3064],
  ['mustard-dark|dark|pass^fail|tritanopia', 0.3297],
  ['mustard-dark|dark|pass^warn|achromatopsia', 0.1197],
  ['mustard-dark|dark|pass^warn|deuteranopia', 0.0964],
  ['mustard-dark|dark|pass^warn|protanopia', 0.1583],
  ['mustard-dark|dark|pass^warn|tritanopia', 0.2176],
  ['mustard-dark|dark|warn^fail|achromatopsia', 0.1210],
  ['mustard-dark|dark|warn^fail|deuteranopia', 0.1338],
  ['mustard-dark|dark|warn^fail|protanopia', 0.1678],
  ['mustard-dark|dark|warn^fail|tritanopia', 0.1167],
  ['mustard-dark|light|pass^fail|achromatopsia', 0.1187],
  ['mustard-dark|light|pass^fail|deuteranopia', 0.0895],
  ['mustard-dark|light|pass^fail|protanopia', 0.1806],
  ['mustard-dark|light|pass^fail|tritanopia', 0.2607],
  ['mustard-dark|light|pass^warn|achromatopsia', 0.1206],
  ['mustard-dark|light|pass^warn|deuteranopia', 0.1611],
  ['mustard-dark|light|pass^warn|protanopia', 0.0890],
  ['mustard-dark|light|pass^warn|tritanopia', 0.2266],
  ['mustard-dark|light|warn^fail|achromatopsia', 0.2393],
  ['mustard-dark|light|warn^fail|deuteranopia', 0.2393],
  ['mustard-dark|light|warn^fail|protanopia', 0.2649],
  ['mustard-dark|light|warn^fail|tritanopia', 0.2186],
  ['mustard|dark|pass^fail|achromatopsia', 0.2408],
  ['mustard|dark|pass^fail|deuteranopia', 0.2042],
  ['mustard|dark|pass^fail|protanopia', 0.3064],
  ['mustard|dark|pass^fail|tritanopia', 0.3297],
  ['mustard|dark|pass^warn|achromatopsia', 0.1197],
  ['mustard|dark|pass^warn|deuteranopia', 0.0964],
  ['mustard|dark|pass^warn|protanopia', 0.1583],
  ['mustard|dark|pass^warn|tritanopia', 0.2176],
  ['mustard|dark|warn^fail|achromatopsia', 0.1210],
  ['mustard|dark|warn^fail|deuteranopia', 0.1338],
  ['mustard|dark|warn^fail|protanopia', 0.1678],
  ['mustard|dark|warn^fail|tritanopia', 0.1167],
  ['mustard|light|pass^fail|achromatopsia', 0.1187],
  ['mustard|light|pass^fail|deuteranopia', 0.0895],
  ['mustard|light|pass^fail|protanopia', 0.1806],
  ['mustard|light|pass^fail|tritanopia', 0.2607],
  ['mustard|light|pass^warn|achromatopsia', 0.1206],
  ['mustard|light|pass^warn|deuteranopia', 0.1611],
  ['mustard|light|pass^warn|protanopia', 0.0890],
  ['mustard|light|pass^warn|tritanopia', 0.2266],
  ['mustard|light|warn^fail|achromatopsia', 0.2393],
  ['mustard|light|warn^fail|deuteranopia', 0.2393],
  ['mustard|light|warn^fail|protanopia', 0.2649],
  ['mustard|light|warn^fail|tritanopia', 0.2186],
  ['onyx-dark|dark|pass^fail|achromatopsia', 0.2399],
  ['onyx-dark|dark|pass^fail|deuteranopia', 0.2037],
  ['onyx-dark|dark|pass^fail|protanopia', 0.3030],
  ['onyx-dark|dark|pass^fail|tritanopia', 0.3249],
  ['onyx-dark|dark|pass^warn|achromatopsia', 0.1208],
  ['onyx-dark|dark|pass^warn|deuteranopia', 0.1132],
  ['onyx-dark|dark|pass^warn|protanopia', 0.1664],
  ['onyx-dark|dark|pass^warn|tritanopia', 0.2130],
  ['onyx-dark|dark|warn^fail|achromatopsia', 0.1190],
  ['onyx-dark|dark|warn^fail|deuteranopia', 0.1278],
  ['onyx-dark|dark|warn^fail|protanopia', 0.1669],
  ['onyx-dark|dark|warn^fail|tritanopia', 0.1235],
  ['onyx-dark|light|pass^fail|achromatopsia', 0.1195],
  ['onyx-dark|light|pass^fail|deuteranopia', 0.0889],
  ['onyx-dark|light|pass^fail|protanopia', 0.1755],
  ['onyx-dark|light|pass^fail|tritanopia', 0.2445],
  ['onyx-dark|light|pass^warn|achromatopsia', 0.1175],
  ['onyx-dark|light|pass^warn|deuteranopia', 0.1538],
  ['onyx-dark|light|pass^warn|protanopia', 0.0983],
  ['onyx-dark|light|pass^warn|tritanopia', 0.1999],
  ['onyx-dark|light|warn^fail|achromatopsia', 0.2370],
  ['onyx-dark|light|warn^fail|deuteranopia', 0.2334],
  ['onyx-dark|light|warn^fail|protanopia', 0.2701],
  ['onyx-dark|light|warn^fail|tritanopia', 0.2152],
  ['onyx|dark|pass^fail|achromatopsia', 0.2399],
  ['onyx|dark|pass^fail|deuteranopia', 0.2037],
  ['onyx|dark|pass^fail|protanopia', 0.3030],
  ['onyx|dark|pass^fail|tritanopia', 0.3249],
  ['onyx|dark|pass^warn|achromatopsia', 0.1208],
  ['onyx|dark|pass^warn|deuteranopia', 0.1132],
  ['onyx|dark|pass^warn|protanopia', 0.1664],
  ['onyx|dark|pass^warn|tritanopia', 0.2130],
  ['onyx|dark|warn^fail|achromatopsia', 0.1190],
  ['onyx|dark|warn^fail|deuteranopia', 0.1278],
  ['onyx|dark|warn^fail|protanopia', 0.1669],
  ['onyx|dark|warn^fail|tritanopia', 0.1235],
  ['onyx|light|pass^fail|achromatopsia', 0.1195],
  ['onyx|light|pass^fail|deuteranopia', 0.0889],
  ['onyx|light|pass^fail|protanopia', 0.1755],
  ['onyx|light|pass^fail|tritanopia', 0.2445],
  ['onyx|light|pass^warn|achromatopsia', 0.1175],
  ['onyx|light|pass^warn|deuteranopia', 0.1538],
  ['onyx|light|pass^warn|protanopia', 0.0983],
  ['onyx|light|pass^warn|tritanopia', 0.1999],
  ['onyx|light|warn^fail|achromatopsia', 0.2370],
  ['onyx|light|warn^fail|deuteranopia', 0.2334],
  ['onyx|light|warn^fail|protanopia', 0.2701],
  ['onyx|light|warn^fail|tritanopia', 0.2152],
]);

/** Every trio pair on every palette, both modes, three deficiencies. */
function measure() {
  const out = new Map();
  for (const theme of listAllThemes()) {
    const vars = mergedVars(theme);
    for (const [mode, isDark] of [['light', false], ['dark', true]]) {
      const hex = (t) => {
        const v = resolveTokenExpr(vars[t], vars, isDark);
        return /^#[0-9a-f]{6}$/i.test(String(v).trim()) ? String(v).trim() : null;
      };
      for (let i = 0; i < TRIO.length; i++) {
        for (let j = i + 1; j < TRIO.length; j++) {
          const a = hex(TRIO[i]); const b = hex(TRIO[j]);
          if (!a || !b) continue;
          for (const type of TYPES) {
            out.set(`${theme}|${mode}|${TRIO[i]}^${TRIO[j]}|${type}`,
                    oklabDistance(simulate(a, type), simulate(b, type)));
          }
        }
      }
    }
  }
  return out;
}

const now = measure();

describe('CVD status-trio separation (frozen distances)', () => {
  test('every frozen pair still resolves', () => {
    const missing = [...CVD_FROZEN.keys()].filter((k) => !now.has(k));
    assert.deepEqual(missing, [],
      `frozen CVD pairs no longer produced — a palette or token was renamed:\n  ${missing.join('\n  ')}`);
  });

  test('a pair at or above the collapse floor still clears it', () => {
    const collapsed = [];
    for (const [k, frozen] of CVD_FROZEN) {
      const floor = collapseFloor(k.split('|')[3]);
      if (frozen < floor) continue;
      const v = now.get(k);
      if (v != null && v < floor) collapsed.push(`${k}  ${frozen.toFixed(4)} -> ${v.toFixed(4)} (floor ${floor})`);
    }
    assert.deepEqual(collapsed, [],
      `${collapsed.length} status pair(s) fell through the CVD collapse floor:\n  ${collapsed.join('\n  ')}`);
  });

  test('a pair already below the floor does not erode further', () => {
    const eroded = [];
    for (const [k, frozen] of CVD_FROZEN) {
      if (frozen >= collapseFloor(k.split('|')[3])) continue;
      const v = now.get(k);
      if (v != null && v < frozen - EROSION_TOLERANCE) eroded.push(`${k}  ${frozen.toFixed(4)} -> ${v.toFixed(4)}`);
    }
    assert.deepEqual(eroded, [],
      `${eroded.length} already-collapsed pair(s) eroded further:\n  ${eroded.join('\n  ')}`);
  });

  test('the frozen table is not stale', () => {
    const extra = [...now.keys()].filter((k) => !CVD_FROZEN.has(k));
    assert.deepEqual(extra, [],
      `pairs measured but not frozen — add them:\n  ${extra.join('\n  ')}`);
    assert.equal(CVD_FROZEN.size, now.size);
  });

  test('coverage: every palette is scanned', () => {
    assert.ok(listAllThemes().length >= 30);
    assert.equal(now.size, listAllThemes().length * 2 * 3 * TYPES.length);
    assert.equal(TYPES.length, 4, 'the monochromacy arm must stay in the frozen table');
  });
});
