/**
 * Unit: a status trio's CVD separation may improve, never erode.
 *
 * `test/unit/palette/cvd-palette.test.js` gates the four a11y CVD palettes, which
 * are curated for separation. Nothing gated the FOURTEEN brand palettes, and
 * `tools/cvd-audit.js` is a report that exits 0 — so a re-tune driven by some other
 * constraint could collapse a pair with every gate green.
 *
 * It did. #1704 moved `--pass` on ardesia / brina / laguna to clear AA on redline's
 * own-hue band, and rotated magnolia's `--fail` -14 deg to clear the same band on a
 * dark canvas. Measured afterwards against `origin/main`: pass^fail under
 * PROTANOPIA went 0.158 -> 0.094 on ardesia and 0.152 -> 0.087 on laguna, and
 * magnolia's warn^fail under TRITANOPIA went 0.1209 -> 0.0473. laguna's shipped
 * value was not an accident — CHANGELOG.md records it as "chosen so it still holds
 * the >=0.15 protanopia pass<->fail CVD floor". That is the #1181 shape: a re-tune
 * satisfying its own surface and breaking a distant one through a shared channel
 * (HARD RULE #18).
 *
 * WHAT IS FROZEN IS THE DISTANCE, NOT THE SET. The first cut of this gate froze the
 * SET of pairs above the floor, and that is why it reported "0 newly collapsed"
 * while 21 pairs eroded and 4 later crossed: a pair already under the floor could
 * decay without limit, and one at 0.1584 could sit at 0.1483 as long as it was not
 * re-counted. It is the same hole this repo's contrast baseline was keyed to close
 * — "a count says nothing about an existing failure getting worse" — and the CVD
 * arm shipped with it anyway. Values, keyed, with an explicit rule:
 *
 *   · frozen AT OR ABOVE the 0.15 collapse floor -> must still clear 0.15.
 *     Separation above the floor is spendable; the floor itself is not.
 *   · frozen BELOW the floor -> must not drop further. The pair is already
 *     unreadable under that deficiency and taking it lower is a loss with no
 *     offsetting gain. (The brand palettes are not CVD-curated, so many pairs sit
 *     here and always have; lifting them all is a different change.)
 *
 * If this fails: a token move eroded a pair. Solve the trio TOGETHER — move the
 * companion token (magnolia needed `--warn` lifted with `--fail`), and remember
 * that LIGHTNESS is the only channel every deficiency preserves, so two hues that
 * must stay apart under simulation need a luminance gap. Do not delete the key,
 * and do not re-bless a number downward without saying why.
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { simulate } = require('../../../lib/theme/cvd.js');
const { oklabDistance } = require('../../../lib/theme/color.js');
const { resolveTokenExpr } = require('../../../lib/core/resolve-token-expr.js');
const { mergedVars, listAllThemes } = require('../../../tools/composed-contrast.js');

// The same floor tools/cvd-audit.js uses for an induced collapse.
const COLLAPSE = 0.15;
// Absorbs last-digit movement in the frozen table, nothing more. A real erosion
// in this repo's measurements is 0.01 upward; the ones #1704 caused were 0.07+.
const EROSION_TOLERANCE = 0.002;
const TRIO = ['pass', 'warn', 'fail'];
const TYPES = ['protanopia', 'deuteranopia', 'tritanopia'];

/**
 * theme|mode|a^b|deficiency -> the HIGH-WATER OKLab distance under that deficiency.
 *
 * Not "today's measurement": `npm run palette:bless` is ratchet-only, so where a
 * change erodes a pair within tolerance the entry keeps the OLDER, larger value
 * and the tree scores below it. That is the strict direction — the floor never
 * relaxes — but it means an entry is an upper bound on the shipped separation,
 * not a reading of it. 73 entries are above the tree as of #1698.
 */
const CVD_FROZEN = new Map([
  ['a11y-achromatopsia|dark|pass^fail|deuteranopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^fail|protanopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^fail|tritanopia', 0.1217],
  ['a11y-achromatopsia|dark|pass^warn|deuteranopia', 0.1102],
  ['a11y-achromatopsia|dark|pass^warn|protanopia', 0.1102],
  ['a11y-achromatopsia|dark|pass^warn|tritanopia', 0.1102],
  ['a11y-achromatopsia|dark|warn^fail|deuteranopia', 0.2320],
  ['a11y-achromatopsia|dark|warn^fail|protanopia', 0.2320],
  ['a11y-achromatopsia|dark|warn^fail|tritanopia', 0.2320],
  ['a11y-achromatopsia|light|pass^fail|deuteranopia', 0.1190],
  ['a11y-achromatopsia|light|pass^fail|protanopia', 0.1190],
  ['a11y-achromatopsia|light|pass^fail|tritanopia', 0.1190],
  ['a11y-achromatopsia|light|pass^warn|deuteranopia', 0.1179],
  ['a11y-achromatopsia|light|pass^warn|protanopia', 0.1179],
  ['a11y-achromatopsia|light|pass^warn|tritanopia', 0.1179],
  ['a11y-achromatopsia|light|warn^fail|deuteranopia', 0.2370],
  ['a11y-achromatopsia|light|warn^fail|protanopia', 0.2370],
  ['a11y-achromatopsia|light|warn^fail|tritanopia', 0.2370],
  ['a11y-base|dark|pass^fail|deuteranopia', 0.0249],
  ['a11y-base|dark|pass^fail|protanopia', 0.1297],
  ['a11y-base|dark|pass^fail|tritanopia', 0.2540],
  ['a11y-base|dark|pass^warn|deuteranopia', 0.0623],
  ['a11y-base|dark|pass^warn|protanopia', 0.0611],
  ['a11y-base|dark|pass^warn|tritanopia', 0.1889],
  ['a11y-base|dark|warn^fail|deuteranopia', 0.0813],
  ['a11y-base|dark|warn^fail|protanopia', 0.1189],
  ['a11y-base|dark|warn^fail|tritanopia', 0.0757],
  ['a11y-base|light|pass^fail|deuteranopia', 0.0423],
  ['a11y-base|light|pass^fail|protanopia', 0.1273],
  ['a11y-base|light|pass^fail|tritanopia', 0.2445],
  ['a11y-base|light|pass^warn|deuteranopia', 0.0936],
  ['a11y-base|light|pass^warn|protanopia', 0.0466],
  ['a11y-base|light|pass^warn|tritanopia', 0.1621],
  ['a11y-base|light|warn^fail|deuteranopia', 0.0838],
  ['a11y-base|light|warn^fail|protanopia', 0.1533],
  ['a11y-base|light|warn^fail|tritanopia', 0.1082],
  ['a11y-deuteranopia|dark|pass^fail|deuteranopia', 0.1888],
  ['a11y-deuteranopia|dark|pass^fail|protanopia', 0.1914],
  ['a11y-deuteranopia|dark|pass^fail|tritanopia', 0.2971],
  ['a11y-deuteranopia|dark|pass^warn|deuteranopia', 0.2436],
  ['a11y-deuteranopia|dark|pass^warn|protanopia', 0.1905],
  ['a11y-deuteranopia|dark|pass^warn|tritanopia', 0.2149],
  ['a11y-deuteranopia|dark|warn^fail|deuteranopia', 0.1623],
  ['a11y-deuteranopia|dark|warn^fail|protanopia', 0.2196],
  ['a11y-deuteranopia|dark|warn^fail|tritanopia', 0.2170],
  ['a11y-deuteranopia|light|pass^fail|deuteranopia', 0.1876],
  ['a11y-deuteranopia|light|pass^fail|protanopia', 0.1890],
  ['a11y-deuteranopia|light|pass^fail|tritanopia', 0.2370],
  ['a11y-deuteranopia|light|pass^warn|deuteranopia', 0.2759],
  ['a11y-deuteranopia|light|pass^warn|protanopia', 0.2200],
  ['a11y-deuteranopia|light|pass^warn|tritanopia', 0.2130],
  ['a11y-deuteranopia|light|warn^fail|deuteranopia', 0.1608],
  ['a11y-deuteranopia|light|warn^fail|protanopia', 0.2185],
  ['a11y-deuteranopia|light|warn^fail|tritanopia', 0.1528],
  ['a11y-protanopia|dark|pass^fail|deuteranopia', 0.1888],
  ['a11y-protanopia|dark|pass^fail|protanopia', 0.1914],
  ['a11y-protanopia|dark|pass^fail|tritanopia', 0.2971],
  ['a11y-protanopia|dark|pass^warn|deuteranopia', 0.2436],
  ['a11y-protanopia|dark|pass^warn|protanopia', 0.1905],
  ['a11y-protanopia|dark|pass^warn|tritanopia', 0.2149],
  ['a11y-protanopia|dark|warn^fail|deuteranopia', 0.1623],
  ['a11y-protanopia|dark|warn^fail|protanopia', 0.2196],
  ['a11y-protanopia|dark|warn^fail|tritanopia', 0.2170],
  ['a11y-protanopia|light|pass^fail|deuteranopia', 0.1876],
  ['a11y-protanopia|light|pass^fail|protanopia', 0.1890],
  ['a11y-protanopia|light|pass^fail|tritanopia', 0.2370],
  ['a11y-protanopia|light|pass^warn|deuteranopia', 0.2759],
  ['a11y-protanopia|light|pass^warn|protanopia', 0.2200],
  ['a11y-protanopia|light|pass^warn|tritanopia', 0.2130],
  ['a11y-protanopia|light|warn^fail|deuteranopia', 0.1608],
  ['a11y-protanopia|light|warn^fail|protanopia', 0.2185],
  ['a11y-protanopia|light|warn^fail|tritanopia', 0.1528],
  ['a11y-tritanopia|dark|pass^fail|deuteranopia', 0.1838],
  ['a11y-tritanopia|dark|pass^fail|protanopia', 0.1836],
  ['a11y-tritanopia|dark|pass^fail|tritanopia', 0.2371],
  ['a11y-tritanopia|dark|pass^warn|deuteranopia', 0.0399],
  ['a11y-tritanopia|dark|pass^warn|protanopia', 0.1309],
  ['a11y-tritanopia|dark|pass^warn|tritanopia', 0.2668],
  ['a11y-tritanopia|dark|warn^fail|deuteranopia', 0.2226],
  ['a11y-tritanopia|dark|warn^fail|protanopia', 0.2513],
  ['a11y-tritanopia|dark|warn^fail|tritanopia', 0.1902],
  ['a11y-tritanopia|light|pass^fail|deuteranopia', 0.1606],
  ['a11y-tritanopia|light|pass^fail|protanopia', 0.2477],
  ['a11y-tritanopia|light|pass^fail|tritanopia', 0.2253],
  ['a11y-tritanopia|light|pass^warn|deuteranopia', 0.0830],
  ['a11y-tritanopia|light|pass^warn|protanopia', 0.0254],
  ['a11y-tritanopia|light|pass^warn|tritanopia', 0.2605],
  ['a11y-tritanopia|light|warn^fail|deuteranopia', 0.2344],
  ['a11y-tritanopia|light|warn^fail|protanopia', 0.2226],
  ['a11y-tritanopia|light|warn^fail|tritanopia', 0.1883],
  ['ardesia-dark|dark|pass^fail|deuteranopia', 0.0338],
  ['ardesia-dark|dark|pass^fail|protanopia', 0.1608],
  ['ardesia-dark|dark|pass^fail|tritanopia', 0.3064],
  ['ardesia-dark|dark|pass^warn|deuteranopia', 0.0840],
  ['ardesia-dark|dark|pass^warn|protanopia', 0.0668],
  ['ardesia-dark|dark|pass^warn|tritanopia', 0.2364],
  ['ardesia-dark|dark|warn^fail|deuteranopia', 0.1113],
  ['ardesia-dark|dark|warn^fail|protanopia', 0.1569],
  ['ardesia-dark|dark|warn^fail|tritanopia', 0.1009],
  ['ardesia-dark|light|pass^fail|deuteranopia', 0.0485],
  ['ardesia-dark|light|pass^fail|protanopia', 0.1560],
  ['ardesia-dark|light|pass^fail|tritanopia', 0.2538],
  ['ardesia-dark|light|pass^warn|deuteranopia', 0.1183],
  ['ardesia-dark|light|pass^warn|protanopia', 0.0623],
  ['ardesia-dark|light|pass^warn|tritanopia', 0.1946],
  ['ardesia-dark|light|warn^fail|deuteranopia', 0.1396],
  ['ardesia-dark|light|warn^fail|protanopia', 0.1989],
  ['ardesia-dark|light|warn^fail|tritanopia', 0.1308],
  ['ardesia|dark|pass^fail|deuteranopia', 0.0338],
  ['ardesia|dark|pass^fail|protanopia', 0.1608],
  ['ardesia|dark|pass^fail|tritanopia', 0.3064],
  ['ardesia|dark|pass^warn|deuteranopia', 0.0840],
  ['ardesia|dark|pass^warn|protanopia', 0.0668],
  ['ardesia|dark|pass^warn|tritanopia', 0.2364],
  ['ardesia|dark|warn^fail|deuteranopia', 0.1113],
  ['ardesia|dark|warn^fail|protanopia', 0.1569],
  ['ardesia|dark|warn^fail|tritanopia', 0.1009],
  ['ardesia|light|pass^fail|deuteranopia', 0.0485],
  ['ardesia|light|pass^fail|protanopia', 0.1560],
  ['ardesia|light|pass^fail|tritanopia', 0.2538],
  ['ardesia|light|pass^warn|deuteranopia', 0.1183],
  ['ardesia|light|pass^warn|protanopia', 0.0623],
  ['ardesia|light|pass^warn|tritanopia', 0.1946],
  ['ardesia|light|warn^fail|deuteranopia', 0.1396],
  ['ardesia|light|warn^fail|protanopia', 0.1989],
  ['ardesia|light|warn^fail|tritanopia', 0.1308],
  ['atelier-dark|dark|pass^fail|deuteranopia', 0.0572],
  ['atelier-dark|dark|pass^fail|protanopia', 0.1669],
  ['atelier-dark|dark|pass^fail|tritanopia', 0.2650],
  ['atelier-dark|dark|pass^warn|deuteranopia', 0.0351],
  ['atelier-dark|dark|pass^warn|protanopia', 0.0510],
  ['atelier-dark|dark|pass^warn|tritanopia', 0.2166],
  ['atelier-dark|dark|warn^fail|deuteranopia', 0.0881],
  ['atelier-dark|dark|warn^fail|protanopia', 0.1245],
  ['atelier-dark|dark|warn^fail|tritanopia', 0.0745],
  ['atelier-dark|light|pass^fail|deuteranopia', 0.0450],
  ['atelier-dark|light|pass^fail|protanopia', 0.1241],
  ['atelier-dark|light|pass^fail|tritanopia', 0.2607],
  ['atelier-dark|light|pass^warn|deuteranopia', 0.0736],
  ['atelier-dark|light|pass^warn|protanopia', 0.0508],
  ['atelier-dark|light|pass^warn|tritanopia', 0.1899],
  ['atelier-dark|light|warn^fail|deuteranopia', 0.0432],
  ['atelier-dark|light|warn^fail|protanopia', 0.1020],
  ['atelier-dark|light|warn^fail|tritanopia', 0.0806],
  ['atelier|dark|pass^fail|deuteranopia', 0.0572],
  ['atelier|dark|pass^fail|protanopia', 0.1669],
  ['atelier|dark|pass^fail|tritanopia', 0.2650],
  ['atelier|dark|pass^warn|deuteranopia', 0.0351],
  ['atelier|dark|pass^warn|protanopia', 0.0510],
  ['atelier|dark|pass^warn|tritanopia', 0.2166],
  ['atelier|dark|warn^fail|deuteranopia', 0.0881],
  ['atelier|dark|warn^fail|protanopia', 0.1245],
  ['atelier|dark|warn^fail|tritanopia', 0.0745],
  ['atelier|light|pass^fail|deuteranopia', 0.0450],
  ['atelier|light|pass^fail|protanopia', 0.1241],
  ['atelier|light|pass^fail|tritanopia', 0.2607],
  ['atelier|light|pass^warn|deuteranopia', 0.0736],
  ['atelier|light|pass^warn|protanopia', 0.0508],
  ['atelier|light|pass^warn|tritanopia', 0.1899],
  ['atelier|light|warn^fail|deuteranopia', 0.0432],
  ['atelier|light|warn^fail|protanopia', 0.1020],
  ['atelier|light|warn^fail|tritanopia', 0.0806],
  ['brina-dark|dark|pass^fail|deuteranopia', 0.0338],
  ['brina-dark|dark|pass^fail|protanopia', 0.1608],
  ['brina-dark|dark|pass^fail|tritanopia', 0.3064],
  ['brina-dark|dark|pass^warn|deuteranopia', 0.0840],
  ['brina-dark|dark|pass^warn|protanopia', 0.0668],
  ['brina-dark|dark|pass^warn|tritanopia', 0.2364],
  ['brina-dark|dark|warn^fail|deuteranopia', 0.1113],
  ['brina-dark|dark|warn^fail|protanopia', 0.1569],
  ['brina-dark|dark|warn^fail|tritanopia', 0.1009],
  ['brina-dark|light|pass^fail|deuteranopia', 0.0600],
  ['brina-dark|light|pass^fail|protanopia', 0.1572],
  ['brina-dark|light|pass^fail|tritanopia', 0.2547],
  ['brina-dark|light|pass^warn|deuteranopia', 0.1260],
  ['brina-dark|light|pass^warn|protanopia', 0.0735],
  ['brina-dark|light|pass^warn|tritanopia', 0.1911],
  ['brina-dark|light|warn^fail|deuteranopia', 0.1478],
  ['brina-dark|light|warn^fail|protanopia', 0.2006],
  ['brina-dark|light|warn^fail|tritanopia', 0.1347],
  ['brina|dark|pass^fail|deuteranopia', 0.0338],
  ['brina|dark|pass^fail|protanopia', 0.1608],
  ['brina|dark|pass^fail|tritanopia', 0.3064],
  ['brina|dark|pass^warn|deuteranopia', 0.0840],
  ['brina|dark|pass^warn|protanopia', 0.0668],
  ['brina|dark|pass^warn|tritanopia', 0.2364],
  ['brina|dark|warn^fail|deuteranopia', 0.1113],
  ['brina|dark|warn^fail|protanopia', 0.1569],
  ['brina|dark|warn^fail|tritanopia', 0.1009],
  ['brina|light|pass^fail|deuteranopia', 0.0600],
  ['brina|light|pass^fail|protanopia', 0.1572],
  ['brina|light|pass^fail|tritanopia', 0.2547],
  ['brina|light|pass^warn|deuteranopia', 0.1260],
  ['brina|light|pass^warn|protanopia', 0.0735],
  ['brina|light|pass^warn|tritanopia', 0.1911],
  ['brina|light|warn^fail|deuteranopia', 0.1478],
  ['brina|light|warn^fail|protanopia', 0.2006],
  ['brina|light|warn^fail|tritanopia', 0.1347],
  ['burgundy-dark|dark|pass^fail|deuteranopia', 0.0572],
  ['burgundy-dark|dark|pass^fail|protanopia', 0.1669],
  ['burgundy-dark|dark|pass^fail|tritanopia', 0.2650],
  ['burgundy-dark|dark|pass^warn|deuteranopia', 0.0351],
  ['burgundy-dark|dark|pass^warn|protanopia', 0.0510],
  ['burgundy-dark|dark|pass^warn|tritanopia', 0.2166],
  ['burgundy-dark|dark|warn^fail|deuteranopia', 0.0881],
  ['burgundy-dark|dark|warn^fail|protanopia', 0.1245],
  ['burgundy-dark|dark|warn^fail|tritanopia', 0.0745],
  ['burgundy-dark|light|pass^fail|deuteranopia', 0.0450],
  ['burgundy-dark|light|pass^fail|protanopia', 0.1241],
  ['burgundy-dark|light|pass^fail|tritanopia', 0.2607],
  ['burgundy-dark|light|pass^warn|deuteranopia', 0.0879],
  ['burgundy-dark|light|pass^warn|protanopia', 0.0459],
  ['burgundy-dark|light|pass^warn|tritanopia', 0.1958],
  ['burgundy-dark|light|warn^fail|deuteranopia', 0.0625],
  ['burgundy-dark|light|warn^fail|protanopia', 0.1168],
  ['burgundy-dark|light|warn^fail|tritanopia', 0.0880],
  ['burgundy|dark|pass^fail|deuteranopia', 0.0572],
  ['burgundy|dark|pass^fail|protanopia', 0.1669],
  ['burgundy|dark|pass^fail|tritanopia', 0.2650],
  ['burgundy|dark|pass^warn|deuteranopia', 0.0351],
  ['burgundy|dark|pass^warn|protanopia', 0.0510],
  ['burgundy|dark|pass^warn|tritanopia', 0.2166],
  ['burgundy|dark|warn^fail|deuteranopia', 0.0881],
  ['burgundy|dark|warn^fail|protanopia', 0.1245],
  ['burgundy|dark|warn^fail|tritanopia', 0.0745],
  ['burgundy|light|pass^fail|deuteranopia', 0.0450],
  ['burgundy|light|pass^fail|protanopia', 0.1241],
  ['burgundy|light|pass^fail|tritanopia', 0.2607],
  ['burgundy|light|pass^warn|deuteranopia', 0.0879],
  ['burgundy|light|pass^warn|protanopia', 0.0459],
  ['burgundy|light|pass^warn|tritanopia', 0.1958],
  ['burgundy|light|warn^fail|deuteranopia', 0.0625],
  ['burgundy|light|warn^fail|protanopia', 0.1168],
  ['burgundy|light|warn^fail|tritanopia', 0.0880],
  ['carbone|dark|pass^fail|deuteranopia', 0.0597],
  ['carbone|dark|pass^fail|protanopia', 0.1817],
  ['carbone|dark|pass^fail|tritanopia', 0.2982],
  ['carbone|dark|pass^warn|deuteranopia', 0.1242],
  ['carbone|dark|pass^warn|protanopia', 0.2327],
  ['carbone|dark|pass^warn|tritanopia', 0.3447],
  ['carbone|dark|warn^fail|deuteranopia', 0.0897],
  ['carbone|dark|warn^fail|protanopia', 0.1121],
  ['carbone|dark|warn^fail|tritanopia', 0.0580],
  ['carbone|light|pass^fail|deuteranopia', 0.0571],
  ['carbone|light|pass^fail|protanopia', 0.1610],
  ['carbone|light|pass^fail|tritanopia', 0.2711],
  ['carbone|light|pass^warn|deuteranopia', 0.1137],
  ['carbone|light|pass^warn|protanopia', 0.0537],
  ['carbone|light|pass^warn|tritanopia', 0.2751],
  ['carbone|light|warn^fail|deuteranopia', 0.1267],
  ['carbone|light|warn^fail|protanopia', 0.1471],
  ['carbone|light|warn^fail|tritanopia', 0.1095],
  ['carta-dark|dark|pass^fail|deuteranopia', 0.0469],
  ['carta-dark|dark|pass^fail|protanopia', 0.1857],
  ['carta-dark|dark|pass^fail|tritanopia', 0.2906],
  ['carta-dark|dark|pass^warn|deuteranopia', 0.0392],
  ['carta-dark|dark|pass^warn|protanopia', 0.0506],
  ['carta-dark|dark|pass^warn|tritanopia', 0.1845],
  ['carta-dark|dark|warn^fail|deuteranopia', 0.0836],
  ['carta-dark|dark|warn^fail|protanopia', 0.1526],
  ['carta-dark|dark|warn^fail|tritanopia', 0.1343],
  ['carta-dark|light|pass^fail|deuteranopia', 0.0661],
  ['carta-dark|light|pass^fail|protanopia', 0.1922],
  ['carta-dark|light|pass^fail|tritanopia', 0.2272],
  ['carta-dark|light|pass^warn|deuteranopia', 0.0636],
  ['carta-dark|light|pass^warn|protanopia', 0.0077],
  ['carta-dark|light|pass^warn|tritanopia', 0.1579],
  ['carta-dark|light|warn^fail|deuteranopia', 0.1281],
  ['carta-dark|light|warn^fail|protanopia', 0.1917],
  ['carta-dark|light|warn^fail|tritanopia', 0.1212],
  ['carta|dark|pass^fail|deuteranopia', 0.0469],
  ['carta|dark|pass^fail|protanopia', 0.1857],
  ['carta|dark|pass^fail|tritanopia', 0.2906],
  ['carta|dark|pass^warn|deuteranopia', 0.0392],
  ['carta|dark|pass^warn|protanopia', 0.0506],
  ['carta|dark|pass^warn|tritanopia', 0.1845],
  ['carta|dark|warn^fail|deuteranopia', 0.0836],
  ['carta|dark|warn^fail|protanopia', 0.1526],
  ['carta|dark|warn^fail|tritanopia', 0.1343],
  ['carta|light|pass^fail|deuteranopia', 0.0661],
  ['carta|light|pass^fail|protanopia', 0.1922],
  ['carta|light|pass^fail|tritanopia', 0.2272],
  ['carta|light|pass^warn|deuteranopia', 0.0636],
  ['carta|light|pass^warn|protanopia', 0.0077],
  ['carta|light|pass^warn|tritanopia', 0.1579],
  ['carta|light|warn^fail|deuteranopia', 0.1281],
  ['carta|light|warn^fail|protanopia', 0.1917],
  ['carta|light|warn^fail|tritanopia', 0.1212],
  ['concrete-dark|dark|pass^fail|deuteranopia', 0.0249],
  ['concrete-dark|dark|pass^fail|protanopia', 0.1297],
  ['concrete-dark|dark|pass^fail|tritanopia', 0.2540],
  ['concrete-dark|dark|pass^warn|deuteranopia', 0.0623],
  ['concrete-dark|dark|pass^warn|protanopia', 0.0611],
  ['concrete-dark|dark|pass^warn|tritanopia', 0.1889],
  ['concrete-dark|dark|warn^fail|deuteranopia', 0.0813],
  ['concrete-dark|dark|warn^fail|protanopia', 0.1189],
  ['concrete-dark|dark|warn^fail|tritanopia', 0.0757],
  ['concrete-dark|light|pass^fail|deuteranopia', 0.0567],
  ['concrete-dark|light|pass^fail|protanopia', 0.0764],
  ['concrete-dark|light|pass^fail|tritanopia', 0.2369],
  ['concrete-dark|light|pass^warn|deuteranopia', 0.0467],
  ['concrete-dark|light|pass^warn|protanopia', 0.0368],
  ['concrete-dark|light|pass^warn|tritanopia', 0.1492],
  ['concrete-dark|light|warn^fail|deuteranopia', 0.0182],
  ['concrete-dark|light|warn^fail|protanopia', 0.0523],
  ['concrete-dark|light|warn^fail|tritanopia', 0.0918],
  ['concrete|dark|pass^fail|deuteranopia', 0.0249],
  ['concrete|dark|pass^fail|protanopia', 0.1297],
  ['concrete|dark|pass^fail|tritanopia', 0.2540],
  ['concrete|dark|pass^warn|deuteranopia', 0.0623],
  ['concrete|dark|pass^warn|protanopia', 0.0611],
  ['concrete|dark|pass^warn|tritanopia', 0.1889],
  ['concrete|dark|warn^fail|deuteranopia', 0.0813],
  ['concrete|dark|warn^fail|protanopia', 0.1189],
  ['concrete|dark|warn^fail|tritanopia', 0.0757],
  ['concrete|light|pass^fail|deuteranopia', 0.0567],
  ['concrete|light|pass^fail|protanopia', 0.0764],
  ['concrete|light|pass^fail|tritanopia', 0.2369],
  ['concrete|light|pass^warn|deuteranopia', 0.0467],
  ['concrete|light|pass^warn|protanopia', 0.0368],
  ['concrete|light|pass^warn|tritanopia', 0.1492],
  ['concrete|light|warn^fail|deuteranopia', 0.0182],
  ['concrete|light|warn^fail|protanopia', 0.0523],
  ['concrete|light|warn^fail|tritanopia', 0.0918],
  ['crepuscolo-dark|dark|pass^fail|deuteranopia', 0.0572],
  ['crepuscolo-dark|dark|pass^fail|protanopia', 0.1669],
  ['crepuscolo-dark|dark|pass^fail|tritanopia', 0.2650],
  ['crepuscolo-dark|dark|pass^warn|deuteranopia', 0.0351],
  ['crepuscolo-dark|dark|pass^warn|protanopia', 0.0510],
  ['crepuscolo-dark|dark|pass^warn|tritanopia', 0.2166],
  ['crepuscolo-dark|dark|warn^fail|deuteranopia', 0.0881],
  ['crepuscolo-dark|dark|warn^fail|protanopia', 0.1245],
  ['crepuscolo-dark|dark|warn^fail|tritanopia', 0.0745],
  ['crepuscolo-dark|light|pass^fail|deuteranopia', 0.0450],
  ['crepuscolo-dark|light|pass^fail|protanopia', 0.1241],
  ['crepuscolo-dark|light|pass^fail|tritanopia', 0.2607],
  ['crepuscolo-dark|light|pass^warn|deuteranopia', 0.0915],
  ['crepuscolo-dark|light|pass^warn|protanopia', 0.0454],
  ['crepuscolo-dark|light|pass^warn|tritanopia', 0.1983],
  ['crepuscolo-dark|light|warn^fail|deuteranopia', 0.0675],
  ['crepuscolo-dark|light|warn^fail|protanopia', 0.1237],
  ['crepuscolo-dark|light|warn^fail|tritanopia', 0.0902],
  ['crepuscolo|dark|pass^fail|deuteranopia', 0.0572],
  ['crepuscolo|dark|pass^fail|protanopia', 0.1669],
  ['crepuscolo|dark|pass^fail|tritanopia', 0.2650],
  ['crepuscolo|dark|pass^warn|deuteranopia', 0.0351],
  ['crepuscolo|dark|pass^warn|protanopia', 0.0510],
  ['crepuscolo|dark|pass^warn|tritanopia', 0.2166],
  ['crepuscolo|dark|warn^fail|deuteranopia', 0.0881],
  ['crepuscolo|dark|warn^fail|protanopia', 0.1245],
  ['crepuscolo|dark|warn^fail|tritanopia', 0.0745],
  ['crepuscolo|light|pass^fail|deuteranopia', 0.0450],
  ['crepuscolo|light|pass^fail|protanopia', 0.1241],
  ['crepuscolo|light|pass^fail|tritanopia', 0.2607],
  ['crepuscolo|light|pass^warn|deuteranopia', 0.0915],
  ['crepuscolo|light|pass^warn|protanopia', 0.0454],
  ['crepuscolo|light|pass^warn|tritanopia', 0.1983],
  ['crepuscolo|light|warn^fail|deuteranopia', 0.0675],
  ['crepuscolo|light|warn^fail|protanopia', 0.1237],
  ['crepuscolo|light|warn^fail|tritanopia', 0.0902],
  ['cuoio-dark|dark|pass^fail|deuteranopia', 0.0581],
  ['cuoio-dark|dark|pass^fail|protanopia', 0.1907],
  ['cuoio-dark|dark|pass^fail|tritanopia', 0.2965],
  ['cuoio-dark|dark|pass^warn|deuteranopia', 0.0277],
  ['cuoio-dark|dark|pass^warn|protanopia', 0.0650],
  ['cuoio-dark|dark|pass^warn|tritanopia', 0.2235],
  ['cuoio-dark|dark|warn^fail|deuteranopia', 0.0857],
  ['cuoio-dark|dark|warn^fail|protanopia', 0.1299],
  ['cuoio-dark|dark|warn^fail|tritanopia', 0.1021],
  ['cuoio-dark|light|pass^fail|deuteranopia', 0.0468],
  ['cuoio-dark|light|pass^fail|protanopia', 0.1318],
  ['cuoio-dark|light|pass^fail|tritanopia', 0.2582],
  ['cuoio-dark|light|pass^warn|deuteranopia', 0.1011],
  ['cuoio-dark|light|pass^warn|protanopia', 0.0460],
  ['cuoio-dark|light|pass^warn|tritanopia', 0.1839],
  ['cuoio-dark|light|warn^fail|deuteranopia', 0.0844],
  ['cuoio-dark|light|warn^fail|protanopia', 0.1527],
  ['cuoio-dark|light|warn^fail|tritanopia', 0.1043],
  ['cuoio|dark|pass^fail|deuteranopia', 0.0581],
  ['cuoio|dark|pass^fail|protanopia', 0.1907],
  ['cuoio|dark|pass^fail|tritanopia', 0.2965],
  ['cuoio|dark|pass^warn|deuteranopia', 0.0277],
  ['cuoio|dark|pass^warn|protanopia', 0.0650],
  ['cuoio|dark|pass^warn|tritanopia', 0.2235],
  ['cuoio|dark|warn^fail|deuteranopia', 0.0857],
  ['cuoio|dark|warn^fail|protanopia', 0.1299],
  ['cuoio|dark|warn^fail|tritanopia', 0.1021],
  ['cuoio|light|pass^fail|deuteranopia', 0.0468],
  ['cuoio|light|pass^fail|protanopia', 0.1318],
  ['cuoio|light|pass^fail|tritanopia', 0.2582],
  ['cuoio|light|pass^warn|deuteranopia', 0.1011],
  ['cuoio|light|pass^warn|protanopia', 0.0460],
  ['cuoio|light|pass^warn|tritanopia', 0.1839],
  ['cuoio|light|warn^fail|deuteranopia', 0.0844],
  ['cuoio|light|warn^fail|protanopia', 0.1527],
  ['cuoio|light|warn^fail|tritanopia', 0.1043],
  ['indaco-dark|dark|pass^fail|deuteranopia', 0.0838],
  ['indaco-dark|dark|pass^fail|protanopia', 0.1881],
  ['indaco-dark|dark|pass^fail|tritanopia', 0.2639],
  ['indaco-dark|dark|pass^warn|deuteranopia', 0.0393],
  ['indaco-dark|dark|pass^warn|protanopia', 0.0328],
  ['indaco-dark|dark|pass^warn|tritanopia', 0.1953],
  ['indaco-dark|dark|warn^fail|deuteranopia', 0.1113],
  ['indaco-dark|dark|warn^fail|protanopia', 0.1569],
  ['indaco-dark|dark|warn^fail|tritanopia', 0.1009],
  ['indaco-dark|light|pass^fail|deuteranopia', 0.0269],
  ['indaco-dark|light|pass^fail|protanopia', 0.1574],
  ['indaco-dark|light|pass^fail|tritanopia', 0.2633],
  ['indaco-dark|light|pass^warn|deuteranopia', 0.0855],
  ['indaco-dark|light|pass^warn|protanopia', 0.0256],
  ['indaco-dark|light|pass^warn|tritanopia', 0.1795],
  ['indaco-dark|light|warn^fail|deuteranopia', 0.1084],
  ['indaco-dark|light|warn^fail|protanopia', 0.1821],
  ['indaco-dark|light|warn^fail|tritanopia', 0.1163],
  ['indaco|dark|pass^fail|deuteranopia', 0.0838],
  ['indaco|dark|pass^fail|protanopia', 0.1881],
  ['indaco|dark|pass^fail|tritanopia', 0.2639],
  ['indaco|dark|pass^warn|deuteranopia', 0.0393],
  ['indaco|dark|pass^warn|protanopia', 0.0328],
  ['indaco|dark|pass^warn|tritanopia', 0.1953],
  ['indaco|dark|warn^fail|deuteranopia', 0.1113],
  ['indaco|dark|warn^fail|protanopia', 0.1569],
  ['indaco|dark|warn^fail|tritanopia', 0.1009],
  ['indaco|light|pass^fail|deuteranopia', 0.0269],
  ['indaco|light|pass^fail|protanopia', 0.1574],
  ['indaco|light|pass^fail|tritanopia', 0.2633],
  ['indaco|light|pass^warn|deuteranopia', 0.0855],
  ['indaco|light|pass^warn|protanopia', 0.0256],
  ['indaco|light|pass^warn|tritanopia', 0.1795],
  ['indaco|light|warn^fail|deuteranopia', 0.1084],
  ['indaco|light|warn^fail|protanopia', 0.1821],
  ['indaco|light|warn^fail|tritanopia', 0.1163],
  ['laguna-dark|dark|pass^fail|deuteranopia', 0.0338],
  ['laguna-dark|dark|pass^fail|protanopia', 0.1608],
  ['laguna-dark|dark|pass^fail|tritanopia', 0.3064],
  ['laguna-dark|dark|pass^warn|deuteranopia', 0.0840],
  ['laguna-dark|dark|pass^warn|protanopia', 0.0668],
  ['laguna-dark|dark|pass^warn|tritanopia', 0.2364],
  ['laguna-dark|dark|warn^fail|deuteranopia', 0.1113],
  ['laguna-dark|dark|warn^fail|protanopia', 0.1569],
  ['laguna-dark|dark|warn^fail|tritanopia', 0.1009],
  ['laguna-dark|light|pass^fail|deuteranopia', 0.0524],
  ['laguna-dark|light|pass^fail|protanopia', 0.1534],
  ['laguna-dark|light|pass^fail|tritanopia', 0.2588],
  ['laguna-dark|light|pass^warn|deuteranopia', 0.1207],
  ['laguna-dark|light|pass^warn|protanopia', 0.0655],
  ['laguna-dark|light|pass^warn|tritanopia', 0.1907],
  ['laguna-dark|light|warn^fail|deuteranopia', 0.1357],
  ['laguna-dark|light|warn^fail|protanopia', 0.1930],
  ['laguna-dark|light|warn^fail|tritanopia', 0.1255],
  ['laguna|dark|pass^fail|deuteranopia', 0.0338],
  ['laguna|dark|pass^fail|protanopia', 0.1608],
  ['laguna|dark|pass^fail|tritanopia', 0.3064],
  ['laguna|dark|pass^warn|deuteranopia', 0.0840],
  ['laguna|dark|pass^warn|protanopia', 0.0668],
  ['laguna|dark|pass^warn|tritanopia', 0.2364],
  ['laguna|dark|warn^fail|deuteranopia', 0.1113],
  ['laguna|dark|warn^fail|protanopia', 0.1569],
  ['laguna|dark|warn^fail|tritanopia', 0.1009],
  ['laguna|light|pass^fail|deuteranopia', 0.0524],
  ['laguna|light|pass^fail|protanopia', 0.1534],
  ['laguna|light|pass^fail|tritanopia', 0.2588],
  ['laguna|light|pass^warn|deuteranopia', 0.1207],
  ['laguna|light|pass^warn|protanopia', 0.0655],
  ['laguna|light|pass^warn|tritanopia', 0.1907],
  ['laguna|light|warn^fail|deuteranopia', 0.1357],
  ['laguna|light|warn^fail|protanopia', 0.1930],
  ['laguna|light|warn^fail|tritanopia', 0.1255],
  ['magnolia-dark|dark|pass^fail|deuteranopia', 0.1360],
  ['magnolia-dark|dark|pass^fail|protanopia', 0.2194],
  ['magnolia-dark|dark|pass^fail|tritanopia', 0.2327],
  ['magnolia-dark|dark|pass^warn|deuteranopia', 0.1081],
  ['magnolia-dark|dark|pass^warn|protanopia', 0.0616],
  ['magnolia-dark|dark|pass^warn|tritanopia', 0.1931],
  ['magnolia-dark|dark|warn^fail|deuteranopia', 0.1815],
  ['magnolia-dark|dark|warn^fail|protanopia', 0.2089],
  ['magnolia-dark|dark|warn^fail|tritanopia', 0.1285],
  ['magnolia-dark|light|pass^fail|deuteranopia', 0.0433],
  ['magnolia-dark|light|pass^fail|protanopia', 0.1341],
  ['magnolia-dark|light|pass^fail|tritanopia', 0.2145],
  ['magnolia-dark|light|pass^warn|deuteranopia', 0.0856],
  ['magnolia-dark|light|pass^warn|protanopia', 0.0459],
  ['magnolia-dark|light|pass^warn|tritanopia', 0.1911],
  ['magnolia-dark|light|warn^fail|deuteranopia', 0.1166],
  ['magnolia-dark|light|warn^fail|protanopia', 0.1402],
  ['magnolia-dark|light|warn^fail|tritanopia', 0.0969],
  ['magnolia|dark|pass^fail|deuteranopia', 0.1360],
  ['magnolia|dark|pass^fail|protanopia', 0.2194],
  ['magnolia|dark|pass^fail|tritanopia', 0.2327],
  ['magnolia|dark|pass^warn|deuteranopia', 0.1081],
  ['magnolia|dark|pass^warn|protanopia', 0.0616],
  ['magnolia|dark|pass^warn|tritanopia', 0.1931],
  ['magnolia|dark|warn^fail|deuteranopia', 0.1815],
  ['magnolia|dark|warn^fail|protanopia', 0.2089],
  ['magnolia|dark|warn^fail|tritanopia', 0.1285],
  ['magnolia|light|pass^fail|deuteranopia', 0.0433],
  ['magnolia|light|pass^fail|protanopia', 0.1341],
  ['magnolia|light|pass^fail|tritanopia', 0.2145],
  ['magnolia|light|pass^warn|deuteranopia', 0.0856],
  ['magnolia|light|pass^warn|protanopia', 0.0459],
  ['magnolia|light|pass^warn|tritanopia', 0.1911],
  ['magnolia|light|warn^fail|deuteranopia', 0.1166],
  ['magnolia|light|warn^fail|protanopia', 0.1402],
  ['magnolia|light|warn^fail|tritanopia', 0.0969],
  ['mustard-dark|dark|pass^fail|deuteranopia', 0.0572],
  ['mustard-dark|dark|pass^fail|protanopia', 0.1669],
  ['mustard-dark|dark|pass^fail|tritanopia', 0.2650],
  ['mustard-dark|dark|pass^warn|deuteranopia', 0.0351],
  ['mustard-dark|dark|pass^warn|protanopia', 0.0510],
  ['mustard-dark|dark|pass^warn|tritanopia', 0.2166],
  ['mustard-dark|dark|warn^fail|deuteranopia', 0.0881],
  ['mustard-dark|dark|warn^fail|protanopia', 0.1245],
  ['mustard-dark|dark|warn^fail|tritanopia', 0.0745],
  ['mustard-dark|light|pass^fail|deuteranopia', 0.0450],
  ['mustard-dark|light|pass^fail|protanopia', 0.1241],
  ['mustard-dark|light|pass^fail|tritanopia', 0.2607],
  ['mustard-dark|light|pass^warn|deuteranopia', 0.0807],
  ['mustard-dark|light|pass^warn|protanopia', 0.0475],
  ['mustard-dark|light|pass^warn|tritanopia', 0.1914],
  ['mustard-dark|light|warn^fail|deuteranopia', 0.0532],
  ['mustard-dark|light|warn^fail|protanopia', 0.1099],
  ['mustard-dark|light|warn^fail|tritanopia', 0.0849],
  ['mustard|dark|pass^fail|deuteranopia', 0.0572],
  ['mustard|dark|pass^fail|protanopia', 0.1669],
  ['mustard|dark|pass^fail|tritanopia', 0.2650],
  ['mustard|dark|pass^warn|deuteranopia', 0.0351],
  ['mustard|dark|pass^warn|protanopia', 0.0510],
  ['mustard|dark|pass^warn|tritanopia', 0.2166],
  ['mustard|dark|warn^fail|deuteranopia', 0.0881],
  ['mustard|dark|warn^fail|protanopia', 0.1245],
  ['mustard|dark|warn^fail|tritanopia', 0.0745],
  ['mustard|light|pass^fail|deuteranopia', 0.0450],
  ['mustard|light|pass^fail|protanopia', 0.1241],
  ['mustard|light|pass^fail|tritanopia', 0.2607],
  ['mustard|light|pass^warn|deuteranopia', 0.0807],
  ['mustard|light|pass^warn|protanopia', 0.0475],
  ['mustard|light|pass^warn|tritanopia', 0.1914],
  ['mustard|light|warn^fail|deuteranopia', 0.0532],
  ['mustard|light|warn^fail|protanopia', 0.1099],
  ['mustard|light|warn^fail|tritanopia', 0.0849],
  ['onyx-dark|dark|pass^fail|deuteranopia', 0.0249],
  ['onyx-dark|dark|pass^fail|protanopia', 0.1297],
  ['onyx-dark|dark|pass^fail|tritanopia', 0.2540],
  ['onyx-dark|dark|pass^warn|deuteranopia', 0.0623],
  ['onyx-dark|dark|pass^warn|protanopia', 0.0611],
  ['onyx-dark|dark|pass^warn|tritanopia', 0.1889],
  ['onyx-dark|dark|warn^fail|deuteranopia', 0.0813],
  ['onyx-dark|dark|warn^fail|protanopia', 0.1189],
  ['onyx-dark|dark|warn^fail|tritanopia', 0.0757],
  ['onyx-dark|light|pass^fail|deuteranopia', 0.0423],
  ['onyx-dark|light|pass^fail|protanopia', 0.1273],
  ['onyx-dark|light|pass^fail|tritanopia', 0.2445],
  ['onyx-dark|light|pass^warn|deuteranopia', 0.0936],
  ['onyx-dark|light|pass^warn|protanopia', 0.0466],
  ['onyx-dark|light|pass^warn|tritanopia', 0.1621],
  ['onyx-dark|light|warn^fail|deuteranopia', 0.0838],
  ['onyx-dark|light|warn^fail|protanopia', 0.1533],
  ['onyx-dark|light|warn^fail|tritanopia', 0.1082],
  ['onyx|dark|pass^fail|deuteranopia', 0.0249],
  ['onyx|dark|pass^fail|protanopia', 0.1297],
  ['onyx|dark|pass^fail|tritanopia', 0.2540],
  ['onyx|dark|pass^warn|deuteranopia', 0.0623],
  ['onyx|dark|pass^warn|protanopia', 0.0611],
  ['onyx|dark|pass^warn|tritanopia', 0.1889],
  ['onyx|dark|warn^fail|deuteranopia', 0.0813],
  ['onyx|dark|warn^fail|protanopia', 0.1189],
  ['onyx|dark|warn^fail|tritanopia', 0.0757],
  ['onyx|light|pass^fail|deuteranopia', 0.0423],
  ['onyx|light|pass^fail|protanopia', 0.1273],
  ['onyx|light|pass^fail|tritanopia', 0.2445],
  ['onyx|light|pass^warn|deuteranopia', 0.0936],
  ['onyx|light|pass^warn|protanopia', 0.0466],
  ['onyx|light|pass^warn|tritanopia', 0.1621],
  ['onyx|light|warn^fail|deuteranopia', 0.0838],
  ['onyx|light|warn^fail|protanopia', 0.1533],
  ['onyx|light|warn^fail|tritanopia', 0.1082],
]);

/** Every trio pair on every palette, both modes, three deficiencies. */
function measure() {
  const out = new Map();
  for (const theme of listAllThemes()) {
    const vars = mergedVars(theme);
    for (const [mode, isDark] of [['light', false], ['dark', true]]) {
      const hex = (t) => {
        const v = resolveTokenExpr(vars[t], vars, isDark);
        return /^#[0-9a-f]{6}$/i.test(String(v).trim()) ? String(v).trim() : null;
      };
      for (let i = 0; i < TRIO.length; i++) {
        for (let j = i + 1; j < TRIO.length; j++) {
          const a = hex(TRIO[i]); const b = hex(TRIO[j]);
          if (!a || !b) continue;
          for (const type of TYPES) {
            out.set(`${theme}|${mode}|${TRIO[i]}^${TRIO[j]}|${type}`,
                    oklabDistance(simulate(a, type), simulate(b, type)));
          }
        }
      }
    }
  }
  return out;
}

const now = measure();

describe('CVD status-trio separation (frozen distances)', () => {
  test('every frozen pair still resolves', () => {
    const missing = [...CVD_FROZEN.keys()].filter((k) => !now.has(k));
    assert.deepEqual(missing, [],
      `frozen CVD pairs no longer produced — a palette or token was renamed:\n  ${missing.join('\n  ')}`);
  });

  test('a pair at or above the collapse floor still clears it', () => {
    const collapsed = [];
    for (const [k, frozen] of CVD_FROZEN) {
      if (frozen < COLLAPSE) continue;
      const v = now.get(k);
      if (v != null && v < COLLAPSE) collapsed.push(`${k}  ${frozen.toFixed(4)} -> ${v.toFixed(4)} (floor ${COLLAPSE})`);
    }
    assert.deepEqual(collapsed, [],
      `${collapsed.length} status pair(s) fell through the CVD collapse floor:\n  ${collapsed.join('\n  ')}`);
  });

  test('a pair already below the floor does not erode further', () => {
    const eroded = [];
    for (const [k, frozen] of CVD_FROZEN) {
      if (frozen >= COLLAPSE) continue;
      const v = now.get(k);
      if (v != null && v < frozen - EROSION_TOLERANCE) eroded.push(`${k}  ${frozen.toFixed(4)} -> ${v.toFixed(4)}`);
    }
    assert.deepEqual(eroded, [],
      `${eroded.length} already-collapsed pair(s) eroded further:\n  ${eroded.join('\n  ')}`);
  });

  test('the frozen table is not stale', () => {
    const extra = [...now.keys()].filter((k) => !CVD_FROZEN.has(k));
    assert.deepEqual(extra, [],
      `pairs measured but not frozen — add them:\n  ${extra.join('\n  ')}`);
    assert.equal(CVD_FROZEN.size, now.size);
  });

  test('coverage: every palette is scanned', () => {
    assert.ok(listAllThemes().length >= 30);
    assert.equal(now.size, listAllThemes().length * 2 * 3 * 3);
  });
});
