// The palette rows the Studio actually ships, as generated by
// tools/build-landing-tokens.js. Parsed rather than hand-copied so the contrast
// assertions below track the real themes instead of a stale snapshot.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { lintTheme, lintThemeCoarse, MUTED_INK, tooltipShell } from './lint-theme.js';

const HERE = dirname(fileURLToPath(import.meta.url));

type Row = { palette: string; mode: string; vars: Record<string, string> };

function paletteRows(): Row[] {
	const css = readFileSync(join(HERE, '../styles/lattice-tokens.generated.css'), 'utf8');
	const rows: Row[] = [];
	for (const m of css.matchAll(/\[data-palette="([^"]+)"\]\[data-mode="(light|dark)"\]\{([^}]*)\}/g)) {
		const vars: Record<string, string> = {};
		for (const d of m[3].matchAll(/--([a-z0-9-]+):\s*(#[0-9A-Fa-f]{6})/g)) vars[d[1]] = d[2];
		rows.push({ palette: m[1], mode: m[2], vars });
	}
	return rows;
}

const relLum = (hex: string) => {
	const c = (hex.replace('#', '').match(/../g) as string[])
		.map((x) => Number.parseInt(x, 16) / 255)
		.map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
	return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const contrast = (a: string, b: string) => {
	const [l1, l2] = [relLum(a), relLum(b)];
	return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
};
describe('lintTheme', () => {
	it('kills the stock severity rail, glyph background and squiggle image', () => {
		// The whole visible defect in the bug report is stock interior chrome: a 5px
		// #d11/orange left rail on the card and CodeMirror's fixed-color SVG
		// squiggle. Both must be explicitly cleared, not merely overpainted.
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic'].borderLeft).toBe('none');
		for (const sev of ['error', 'warning', 'info', 'hint']) {
			expect(lintTheme[`.cm-lintRange-${sev}`].backgroundImage).toBe('none');
		}
		expect(lintTheme['.cm-lint-marker'].backgroundImage).toBe('none');
	});

	it('routes every color through a token — no hex literals outside the mask data URIs', () => {
		// HARD RULE #3's discipline: a palette-blind surface. The only `#` allowed
		// is inside a `url("data:image/svg+xml,…")` mask, where `stroke='%23000'`
		// is an alpha carrier — a mask uses the image's alpha, never its color.
		for (const [selector, decls] of Object.entries(lintTheme)) {
			for (const [prop, value] of Object.entries(decls)) {
				if (String(value).startsWith('url("data:image/svg+xml')) continue;
				expect(`${selector} { ${prop}: ${value} }`).not.toMatch(/#[0-9a-f]{3,8}\b/i);
			}
		}
	});

	it('never references the undefined --db-sev-* tokens', () => {
		// These were referenced by the Playground and defined nowhere in the repo,
		// so their hex fallbacks won on every palette. Severity now comes from
		// --fail / --warn, which the themes actually define.
		const all = JSON.stringify(lintTheme);
		expect(all).not.toContain('--db-sev');
		expect(lintTheme['.cm-lintRange-error'].textDecorationColor).toBe('var(--fail)');
		expect(lintTheme['.cm-lint-marker-warning'].backgroundColor).toBe('var(--warn)');
	});

	it('carries severity on shape and word, not hue alone', () => {
		// WCAG 1.4.1 / the a11y-* palettes, where the severity tokens collapse
		// toward one gray and color is worth nothing.
		const err = lintTheme['.cm-tooltip-lint > li.cm-diagnostic-error::before'];
		const warn = lintTheme['.cm-tooltip-lint > li.cm-diagnostic-warning::before'];
		expect(err.maskImage).not.toBe(warn.maskImage); // distinct silhouettes
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-error::after'].content).toBe("'Error'");
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-warning::after'].content).toBe("'Warning'");
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-info::after'].content).toBe("'Note'");
		// The severity WORD is heading ink, not the severity hue — so it stays
		// legible where the hue is not.
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic::after'].color).toBe('var(--text-heading)');
	});

	it('re-reads the package DOM as meta / message / action', () => {
		// @codemirror/lint emits text -> button(s) -> source and we do not fork it;
		// grid placement is the whole mechanism, so the row assignments are the
		// contract. Actions carry no explicit row: they auto-flow to 3..n, which is
		// what lets 0..n buttons land cleanly.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticSource'].gridRow).toBe('1');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticText'].gridRow).toBe('2');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticAction'].gridColumn).toBe('1 / -1');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticAction'].gridRow).toBeUndefined();
	});

	it('keeps the fix button on the accent pair and never shifts its fill', () => {
		// --on-accent is the curated per-theme answer to "accent has no contrast
		// guarantee". Hover/press must therefore not move the fill: both obvious
		// shifts break somewhere across the palette set.
		const btn = lintTheme['.cm-tooltip-lint .cm-diagnosticAction'];
		expect(btn.backgroundColor).toBe('var(--accent)');
		expect(btn.color).toBe('var(--on-accent)');
		for (const state of [':hover', ':active']) {
			const rule = lintTheme[`.cm-tooltip-lint .cm-diagnosticAction${state}`];
			expect(rule.backgroundColor).toBeUndefined();
			expect(rule.boxShadow).toContain('var(--accent)');
		}
	});

	it('preserves the blank line lint-core puts between message and fix prose', () => {
		// lint-core composes `${message}\n\nFix: ${fix}` for findings with no
		// one-click action; anything but pre-wrap collapses that separation.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticText'].whiteSpace).toBe('pre-wrap');
	});

	it('exports coarse-pointer rules SEPARATELY so a merge cannot drop the iOS zoom guard', () => {
		// Both consuming themes own an '@media (pointer: coarse)' key for the 16px
		// .cm-content lift. A theme object is a flat map, so a lint module carrying
		// its own copy of that key would replace theirs on spread.
		expect(lintTheme['@media (pointer: coarse)']).toBeUndefined();
		expect(lintThemeCoarse['.cm-tooltip-lint .cm-diagnosticAction'].minHeight).toBe('44px');
	});

	it('clears the gutter marker with content, not just backgroundImage', () => {
		// The package draws this marker as `content: url(<svg>)` with a hardcoded
		// #f87 / #fe8 fill, which makes the div a REPLACED element — a background
		// then paints BEHIND the stock glyph instead of replacing it, giving a
		// two-tone bullseye. `backgroundImage` is the right lever for the squiggle
		// (genuinely a background image) and the wrong one here.
		for (const sev of ['error', 'warning', 'info']) {
			expect(lintTheme[`.cm-lint-marker-${sev}`].content, `${sev} marker must clear content`).toBe('none');
		}
		expect(lintTheme['.cm-lint-marker'].content).toBe('none');
	});

	it('keeps the severity silhouettes visible under forced colors', () => {
		// Shape is this design's primary severity channel and it is carried by
		// background-color — which forced-colors mode overrides to Canvas, making
		// both the card glyph and the gutter disc the same color as what they sit
		// on. The gutter has no second channel, and its stock `content:` SVG (which
		// forced-colors WOULD have preserved) is cleared above, so without this the
		// gutter is empty in High Contrast — worse than the package shipped.
		// The @media value is a selector map, not a declaration map — narrow it.
		const fc = lintTheme['@media (forced-colors: active)'] as Record<string, Record<string, string>>;
		expect(fc).toBeDefined();
		// System color keywords are the sanctioned escape hatch and ARE honored.
		expect(fc['.cm-lint-marker'].backgroundColor).toBe('CanvasText');
		expect(fc['.cm-tooltip-lint > li.cm-diagnostic::before'].backgroundColor).toBe('CanvasText');
	});

	it('does not block the scroll chain with overscroll-behavior', () => {
		// `contain` blocks chaining once this box is exhausted, which is the wrong
		// default for a transient popup over the thing the reader wants to move.
		// NOTE the honest scope: removing it did NOT by itself make the editor scroll
		// under the pointer (measured — the tooltip is position:fixed and so is not in
		// .cm-scroller's chain at all). This pins the declaration, not a behavior; see
		// the comment on `.cm-tooltip-lint` in lint-theme.js.
		expect(lintTheme['.cm-tooltip-lint'].overscrollBehavior).toBeUndefined();
	});

	it('keeps coarse-pointer rules to target and type size, never width', () => {
		// A coarse pointer means fingers — a target-size argument at ANY width. It is
		// not a license to widen the card: relaxing max-width here produced an 893px
		// full-bleed banner on every touchscreen laptop and landscape tablet, the
		// opposite of the 340px "sit beside the code" rule. The narrow cap already
		// carries `calc(100vw - 28px)`, so real phones need no override.
		// Sizing the GLYPH up on touch is fine and expected; what must never appear
		// is a width override on the popup container itself.
		for (const [selector, decls] of Object.entries(lintThemeCoarse)) {
			for (const prop of ['width', 'maxWidth', 'minWidth']) {
				expect(Object.keys(decls), `${selector} must not size the popup container in a pointer query`).toSatisfy(
					(keys: string[]) => !keys.includes(prop) || !selector.replace(/::?[a-z-]+$/, '').endsWith('.cm-tooltip-lint'),
				);
			}
		}
		// Stated positively: the container carries no coarse-pointer rule at all.
		expect(lintThemeCoarse['.cm-tooltip-lint']).toBeUndefined();
	});

	it('scopes the inner-list radius so the two spread orders cannot disagree', () => {
		// On the gutter path the <ul> IS the .cm-tooltip, so an unconditional 7px on
		// .cm-tooltip-lint collided with tooltipShell's 8px at equal specificity and
		// the winner depended on which object each consumer spread first — which
		// differed, producing 7px on one surface and 8px on the other from ONE
		// shared module.
		expect(lintTheme['.cm-tooltip-lint'].borderRadius).toBeUndefined();
		expect(lintTheme['.cm-tooltip-lint:not(.cm-tooltip)'].borderRadius).toBe('7px');
	});

	it('gives BOTH consumers the tooltip shell', () => {
		// The lint card styles only the popup's interior and lets `.cm-tooltip` carry
		// the fill — which works only if every consuming surface actually themes that
		// shell. The Studio did and the Playground did not, so the Playground's popup
		// fell through to @codemirror/view's base `&light .cm-tooltip{background:#f5f5f5}`
		// on every palette AND in dark mode (--text-body on #f5f5f5 is 1.32:1).
		// It is a bare `.cm-tooltip`, not `.cm-tooltip.cm-tooltip-lint`, on purpose:
		// @codemirror/lint has TWO tooltip paths, and only the gutter-marker one puts
		// both classes on the same element — the squiggle hover puts `.cm-tooltip` on a
		// HoverTooltipHost wrapper whose `<ul>` gets `cm-tooltip-section` instead.
		expect(Object.keys(tooltipShell)).toEqual(['.cm-tooltip']);
		expect(tooltipShell['.cm-tooltip'].backgroundColor).toBe('var(--bg)');
		for (const file of ['../components/studio/editor-theme.ts', '../playground/editor.js']) {
			const src = readFileSync(join(HERE, file), 'utf8');
			expect(src, `${file}: must spread the shared tooltip shell`).toContain('...tooltipShell,');
			// And must not re-declare it locally, which is how the two drifted before.
			expect(src.match(/^\s*'\.cm-tooltip':\s*\{/m), `${file}: don't redeclare .cm-tooltip`).toBeNull();
		}
	});

	it('is spread BEFORE each consumer’s coarse-pointer block', () => {
		// Ordering is load-bearing and invisible: a theme object compiles to a
		// stylesheet in key order, and lintThemeCoarse targets the same selectors as
		// lintTheme at the same specificity. Placed first, the coarse rules lose to
		// the base rules they exist to override — the fix pill measured 28px instead
		// of 44px on a real coarse pointer until the block moved last. Nothing else
		// catches this: the object is valid, both surfaces build, every other unit
		// test passes, and only a touch device shows the defect.
		for (const file of ['../components/studio/editor-theme.ts', '../playground/editor.js']) {
			const src = readFileSync(join(HERE, file), 'utf8');
			const spread = src.indexOf('...lintTheme,');
			const media = src.indexOf("'@media (pointer: coarse)'");
			expect(spread, `${file}: expected a ...lintTheme spread`).toBeGreaterThan(-1);
			expect(media, `${file}: expected a coarse-pointer block`).toBeGreaterThan(-1);
			expect(media, `${file}: the coarse block must come AFTER ...lintTheme`).toBeGreaterThan(spread);
		}
	});

	// This test used to assert the OPPOSITE — that bare `--text-muted` drops below 3:1
	// on at least one shipped palette, which is what justified mixing it 55% into
	// `--text-body`. #1715 made that premise false: `--text-muted` is now the AA-floored
	// TEXT half of a split role and clears 4.5:1 on every palette-mode against both
	// surfaces. So the mix is gone and the token is read directly; the assertion is
	// inverted to pin the contract that replaced it, rather than deleted.
	it('reads --text-muted directly, because it now carries an AA floor', () => {
		const rows = paletteRows();
		expect(rows.length).toBeGreaterThan(20); // sanity: the sheet really parsed
		const failures: string[] = [];
		let measured = 0;
		for (const { palette, mode, vars } of rows) {
			const { bg, 'text-muted': muted } = vars;
			if (!bg || !muted) continue;
			measured++;
			const r = contrast(muted, bg);
			if (r < 4.5) failures.push(`${palette}/${mode} ${r.toFixed(2)}:1`);
		}
		expect(measured).toBeGreaterThan(20); // not vacuous
		expect(failures).toEqual([]);
		// And the rule id / Note glyph must actually use it.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticSource'].color).toBe(MUTED_INK);
		expect(MUTED_INK).toBe('var(--text-muted)');
	});

	it('keeps severity tokens above 3:1 against the popup fill on every palette', () => {
		// The card sits on --bg (the shell fill it inherits), so --fail / --warn
		// are measured there, not against --bg-alt.
		const bad: string[] = [];
		for (const { palette, mode, vars } of paletteRows()) {
			for (const token of ['fail', 'warn']) {
				if (!vars[token] || !vars.bg) continue;
				const ratio = contrast(vars[token], vars.bg);
				if (ratio < 3) bad.push(`${palette}/${mode} --${token} ${ratio.toFixed(2)}:1`);
			}
		}
		expect(bad).toEqual([]);
	});
});
