// The palette rows the Studio actually ships, as generated by
// tools/build-landing-tokens.js. Parsed rather than hand-copied so the contrast
// assertions below track the real themes instead of a stale snapshot.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { lintTheme, lintThemeCoarse, MUTED_INK } from './lint-theme.js';

const HERE = dirname(fileURLToPath(import.meta.url));

type Row = { palette: string; mode: string; vars: Record<string, string> };

function paletteRows(): Row[] {
	const css = readFileSync(join(HERE, '../styles/lattice-tokens.generated.css'), 'utf8');
	const rows: Row[] = [];
	for (const m of css.matchAll(/\[data-palette="([^"]+)"\]\[data-mode="(light|dark)"\]\{([^}]*)\}/g)) {
		const vars: Record<string, string> = {};
		for (const d of m[3].matchAll(/--([a-z0-9-]+):\s*(#[0-9A-Fa-f]{6})/g)) vars[d[1]] = d[2];
		rows.push({ palette: m[1], mode: m[2], vars });
	}
	return rows;
}

const relLum = (hex: string) => {
	const c = (hex.replace('#', '').match(/../g) as string[])
		.map((x) => Number.parseInt(x, 16) / 255)
		.map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
	return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const contrast = (a: string, b: string) => {
	const [l1, l2] = [relLum(a), relLum(b)];
	return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
};
// srgb `color-mix(in srgb, A p%, B)` — the exact form MUTED_INK uses.
const mix = (a: string, b: string, p: number) => {
	const A = (a.replace('#', '').match(/../g) as string[]).map((x) => Number.parseInt(x, 16));
	const B = (b.replace('#', '').match(/../g) as string[]).map((x) => Number.parseInt(x, 16));
	return `#${A.map((v, i) => Math.round(v * p + B[i] * (1 - p)).toString(16).padStart(2, '0')).join('')}`;
};

describe('lintTheme', () => {
	it('kills the stock severity rail, glyph background and squiggle image', () => {
		// The whole visible defect in the bug report is stock interior chrome: a 5px
		// #d11/orange left rail on the card and CodeMirror's fixed-color SVG
		// squiggle. Both must be explicitly cleared, not merely overpainted.
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic'].borderLeft).toBe('none');
		for (const sev of ['error', 'warning', 'info', 'hint']) {
			expect(lintTheme[`.cm-lintRange-${sev}`].backgroundImage).toBe('none');
		}
		expect(lintTheme['.cm-lint-marker'].backgroundImage).toBe('none');
	});

	it('routes every color through a token — no hex literals outside the mask data URIs', () => {
		// HARD RULE #3's discipline: a palette-blind surface. The only `#` allowed
		// is inside a `url("data:image/svg+xml,…")` mask, where `stroke='%23000'`
		// is an alpha carrier — a mask uses the image's alpha, never its color.
		for (const [selector, decls] of Object.entries(lintTheme)) {
			for (const [prop, value] of Object.entries(decls)) {
				if (String(value).startsWith('url("data:image/svg+xml')) continue;
				expect(`${selector} { ${prop}: ${value} }`).not.toMatch(/#[0-9a-f]{3,8}\b/i);
			}
		}
	});

	it('never references the undefined --db-sev-* tokens', () => {
		// These were referenced by the Playground and defined nowhere in the repo,
		// so their hex fallbacks won on every palette. Severity now comes from
		// --fail / --warn, which the themes actually define.
		const all = JSON.stringify(lintTheme);
		expect(all).not.toContain('--db-sev');
		expect(lintTheme['.cm-lintRange-error'].textDecorationColor).toBe('var(--fail)');
		expect(lintTheme['.cm-lint-marker-warning'].backgroundColor).toBe('var(--warn)');
	});

	it('carries severity on shape and word, not hue alone', () => {
		// WCAG 1.4.1 / the a11y-* palettes, where the severity tokens collapse
		// toward one gray and color is worth nothing.
		const err = lintTheme['.cm-tooltip-lint > li.cm-diagnostic-error::before'];
		const warn = lintTheme['.cm-tooltip-lint > li.cm-diagnostic-warning::before'];
		expect(err.maskImage).not.toBe(warn.maskImage); // distinct silhouettes
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-error::after'].content).toBe("'Error'");
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-warning::after'].content).toBe("'Warning'");
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic-info::after'].content).toBe("'Note'");
		// The severity WORD is heading ink, not the severity hue — so it stays
		// legible where the hue is not.
		expect(lintTheme['.cm-tooltip-lint > li.cm-diagnostic::after'].color).toBe('var(--text-heading)');
	});

	it('re-reads the package DOM as meta / message / action', () => {
		// @codemirror/lint emits text -> button(s) -> source and we do not fork it;
		// grid placement is the whole mechanism, so the row assignments are the
		// contract. Actions carry no explicit row: they auto-flow to 3..n, which is
		// what lets 0..n buttons land cleanly.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticSource'].gridRow).toBe('1');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticText'].gridRow).toBe('2');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticAction'].gridColumn).toBe('1 / -1');
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticAction'].gridRow).toBeUndefined();
	});

	it('keeps the fix button on the accent pair and never shifts its fill', () => {
		// --on-accent is the curated per-theme answer to "accent has no contrast
		// guarantee". Hover/press must therefore not move the fill: both obvious
		// shifts break somewhere across the palette set.
		const btn = lintTheme['.cm-tooltip-lint .cm-diagnosticAction'];
		expect(btn.backgroundColor).toBe('var(--accent)');
		expect(btn.color).toBe('var(--on-accent)');
		for (const state of [':hover', ':active']) {
			const rule = lintTheme[`.cm-tooltip-lint .cm-diagnosticAction${state}`];
			expect(rule.backgroundColor).toBeUndefined();
			expect(rule.boxShadow).toContain('var(--accent)');
		}
	});

	it('preserves the blank line lint-core puts between message and fix prose', () => {
		// lint-core composes `${message}\n\nFix: ${fix}` for findings with no
		// one-click action; anything but pre-wrap collapses that separation.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticText'].whiteSpace).toBe('pre-wrap');
	});

	it('exports coarse-pointer rules SEPARATELY so a merge cannot drop the iOS zoom guard', () => {
		// Both consuming themes own an '@media (pointer: coarse)' key for the 16px
		// .cm-content lift. A theme object is a flat map, so a lint module carrying
		// its own copy of that key would replace theirs on spread.
		expect(lintTheme['@media (pointer: coarse)']).toBeUndefined();
		expect(lintThemeCoarse['.cm-tooltip-lint .cm-diagnosticAction'].minHeight).toBe('44px');
	});

	it('is spread BEFORE each consumer’s coarse-pointer block', () => {
		// Ordering is load-bearing and invisible: a theme object compiles to a
		// stylesheet in key order, and lintThemeCoarse targets the same selectors as
		// lintTheme at the same specificity. Placed first, the coarse rules lose to
		// the base rules they exist to override — the fix pill measured 28px instead
		// of 44px on a real coarse pointer until the block moved last. Nothing else
		// catches this: the object is valid, both surfaces build, every other unit
		// test passes, and only a touch device shows the defect.
		for (const file of ['../components/studio/editor-theme.ts', '../playground/editor.js']) {
			const src = readFileSync(join(HERE, file), 'utf8');
			const spread = src.indexOf('...lintTheme,');
			const media = src.indexOf("'@media (pointer: coarse)'");
			expect(spread, `${file}: expected a ...lintTheme spread`).toBeGreaterThan(-1);
			expect(media, `${file}: expected a coarse-pointer block`).toBeGreaterThan(-1);
			expect(media, `${file}: the coarse block must come AFTER ...lintTheme`).toBeGreaterThan(spread);
		}
	});

	it('lifts recessive ink past 3:1 on every palette, which --text-muted alone does not', () => {
		const rows = paletteRows();
		expect(rows.length).toBeGreaterThan(20); // sanity: the sheet really parsed
		const failures: string[] = [];
		let mutedWouldFail = 0;
		for (const { palette, mode, vars } of rows) {
			const { bg, 'text-muted': muted, 'text-body': body } = vars;
			if (!bg || !muted || !body) continue;
			if (contrast(muted, bg) < 3) mutedWouldFail++;
			const lifted = contrast(mix(muted, body, 0.55), bg);
			if (lifted < 3) failures.push(`${palette}/${mode} ${lifted.toFixed(2)}:1`);
		}
		// The defect this guards against is real, not hypothetical: bare
		// --text-muted drops below 3:1 on at least one shipped palette.
		expect(mutedWouldFail).toBeGreaterThan(0);
		expect(failures).toEqual([]);
		// And the rule id / Note glyph must actually use the lifted ink.
		expect(lintTheme['.cm-tooltip-lint .cm-diagnosticSource'].color).toBe(MUTED_INK);
		expect(MUTED_INK).toBe('color-mix(in srgb, var(--text-muted) 55%, var(--text-body))');
	});

	it('keeps severity tokens above 3:1 against the popup fill on every palette', () => {
		// The card sits on --bg (the shell fill it inherits), so --fail / --warn
		// are measured there, not against --bg-alt.
		const bad: string[] = [];
		for (const { palette, mode, vars } of paletteRows()) {
			for (const token of ['fail', 'warn']) {
				if (!vars[token] || !vars.bg) continue;
				const ratio = contrast(vars[token], vars.bg);
				if (ratio < 3) bad.push(`${palette}/${mode} --${token} ${ratio.toFixed(2)}:1`);
			}
		}
		expect(bad).toEqual([]);
	});
});
