// GENERATED by tools/build-theme-catalog.js from themes/*.manifest.json — DO NOT EDIT.
// Run `npm run build` (or `node tools/build-theme-catalog.js`) to regenerate;
// `theme-catalog:check` fails the build when this drifts from the manifests.
//
// The manifests are the single declaration of which palettes exist and what each one
// is. See engineering/decisions/2026-08-09-theme-token-contract.md.

/** Brand palettes the picker surfaces first (manifest `tier: "curated"`). */
export const CURATED = ['indaco', 'cuoio', 'burgundy', 'laguna', 'crepuscolo', 'atelier', 'carbone', 'onyx'];

/** The remaining brand palettes (manifest `tier: "more"`). */
export const MORE_THEMES = ['ardesia', 'brina', 'carta', 'concrete', 'magnolia', 'mustard'];

/** The curated color-vision palettes (manifest `cvd`). */
export const A11Y_THEMES = ['a11y-achromatopsia', 'a11y-deuteranopia', 'a11y-protanopia', 'a11y-tritanopia'];

/** Every palette the Studio can drive via `data-palette` — curated + more + the AA color-blind set. */
export const BUILTIN_PALETTES = [...CURATED, ...MORE_THEMES, ...A11Y_THEMES];

/** Each listed palette's picker dot (manifest `swatch`). */
export const PALETTE_DOTS: Record<string, string> = {
	indaco: '#006FA8',
	cuoio: '#7A5A10',
	burgundy: '#742532',
	laguna: '#006D77',
	crepuscolo: '#5B3D8C',
	atelier: '#1A1A18',
	carbone: '#7DE38A',
	onyx: '#000000',
	ardesia: '#1F1F1F',
	brina: '#3D6A82',
	carta: '#38598C',
	concrete: '#6B6B68',
	magnolia: '#A04A55',
	mustard: '#8C6A18',
	'a11y-achromatopsia': '#4D4D4D',
	'a11y-deuteranopia': '#004982',
	'a11y-protanopia': '#9C6900',
	'a11y-tritanopia': '#006D2F',
};

/**
 * Each listed palette's FAMILY (manifest `family`) — what the site chrome groups by.
 *
 * This replaced `name.startsWith('a11y-')`. A filename prefix is a naming convention,
 * not a declaration: it silently mis-groups any user theme whose name happens to begin
 * `a11y-`, and it cannot be checked against anything. `family` is declared in the
 * manifest and proved against the file by `checkThemeRoles`.
 */
export const THEME_FAMILY: Record<string, 'brand' | 'a11y'> = {
	indaco: 'brand',
	cuoio: 'brand',
	burgundy: 'brand',
	laguna: 'brand',
	crepuscolo: 'brand',
	atelier: 'brand',
	carbone: 'brand',
	onyx: 'brand',
	ardesia: 'brand',
	brina: 'brand',
	carta: 'brand',
	concrete: 'brand',
	magnolia: 'brand',
	mustard: 'brand',
	'a11y-achromatopsia': 'a11y',
	'a11y-deuteranopia': 'a11y',
	'a11y-protanopia': 'a11y',
	'a11y-tritanopia': 'a11y',
};

/** True for the curated color-vision palettes. Unknown names (a user's own theme) are
 *  NOT a11y — the group is the curated set, not everything named like it. */
export const isA11yPalette = (name: string): boolean => THEME_FAMILY[name] === 'a11y';
